Rename old references to BlockHeaderHash and BlockHeight
ZcashFoundation/zebra pull request #1002
Opened 2020-09-02 20:31 UTC by oxarbitrage

Closes https://github.com/ZcashFoundation/zebra/issues/968 if merged.

2020-09-03 00:15 UTC, yaahc approved these changes, later dismissed
:+1:

2020-09-03 21:53 UTC, dconnolly commented on book/src/dev/rfcs/0002-parallel-verification.md
> +    performs verification on the block, and responds with a `Hash` on
```suggestion
    performs verification on the block, and responds with a `block::Hash` on
```

2020-09-03 21:59 UTC, dconnolly commented on zebra-network/src/protocol/external/message.rs
> +        /// `Hash` of the last desired block.
```suggestion
        /// `block::Hash` of the last desired block.
```

2020-09-03 22:16 UTC, teor2345 commented on zebra-state/src/lib.rs
> +//! * Hash -> Block
```suggestion
//! * block::Hash -> Block
```

2020-09-03 22:18 UTC, teor2345 requested changes, later dismissed
Looks good, thanks for doing this work!

We need to change every BlockHeaderHash to block::Hash, because Hash is also a standard library trait.

2020-09-03 23:07 UTC, oxarbitrage commented
I was in doubt in regards to that but forgot to ask. Thanks for the suggestions for it, applied at https://github.com/ZcashFoundation/zebra/pull/1002/commits/f776dbf51f38915cf0d2b1fe7f3a39e163137cac

2020-09-04 02:36 UTC, yaahc approved these changes

2020-09-04 22:40 UTC, merged

2020-09-04 22:40 UTC, yaahc commented
ty again @oxarbitrage