Fix inconsistencies related to best chain order in RFC and state impl
ZcashFoundation/zebra pull request #1267
Opened 2020-11-06 23:02 UTC by yaahc

## Motivation

Prior to this PR we realized that the RFC had been drafted with the assumption that chains would be ordered from best to worst in `NonFinalizedState`. This assumption was incorrect, since `BTreeSet` only ever orders values in ascending order. This discrepancy was noticed and fixed in the code, but there were still some inconsistencies that needed to be cleaned up.

## Solution

This PR updates all the incorrect or confusing comments about chain ordering in the RFC and code.

The code in this pull request has:
  - [ ] Documentation Comments
  - [ ] Unit Tests and Property Tests

## Review

@teor2345

## Related Issues

- [Tracking Issue](https://github.com/ZcashFoundation/zebra/issues/1250)

## Follow Up Work

2020-11-06 23:03 UTC, yaahc commented
blocked until https://github.com/ZcashFoundation/zebra/pull/1258 merges

2020-11-06 23:04 UTC, yaahc commented on zebra-state/src/service/memory_state/non_finalized_state.rs
> +            .rev()
this isn't strictly necessary but I thought it would be best for us to iterate in best chain order when searching for hashes.

2020-11-09 21:56 UTC, teor2345 requested changes
@yaahc can you rebase the chain order PR so it only contains relevant changes?
Then I can do a review.

I think the "Reorganize memory_state to avoid giant test module" commit has been merged to main.

2020-11-09 23:31 UTC, teor2345 approved these changes
Looks great, thanks for updating the RFC.

2020-11-09 23:53 UTC, merged