Add tests for QueuedBlocks
ZcashFoundation/zebra pull request #1268
Opened 2020-11-06 23:51 UTC by yaahc

## Motivation

Prior to this PR we implemented the `QueuedBlock` type according to RFC0005 but did not add tests.

## Solution

This PR adds whatever unit and property tests seem appropriate for sufficiently testing the behaviour of `QueuedBlocks`.

The code in this pull request has:
  - [ ] Documentation Comments
  - [ ] Unit Tests and Property Tests

## Review

@teor2345

## Related Issues

- [Tracking Issue](https://github.com/ZcashFoundation/zebra/issues/1250)

## Follow Up Work

2020-11-06 23:52 UTC, yaahc commented
blocked until https://github.com/ZcashFoundation/zebra/pull/1258 merges

2020-11-09 21:53 UTC, teor2345 requested changes
@yaahc can you rebase this PR so it only contains relevant changes?
Then I can do a review.

I think the "Reorganize memory_state to avoid giant test module" commit has been merged to main.

2020-11-09 23:38 UTC, teor2345 requested changes
These tests look good for `queue` and `dequeue_children`.

Should we also have tests for `prune_by_height`?
(Let's put those tests in a separate PR, so we can finish up this PR and merge it.)

This PR is failing with compilation errors, did you drop a commit, or forget to commit some files?

2020-11-10 19:30 UTC, yaahc commented
blocked until https://github.com/ZcashFoundation/zebra/pull/1266 merges

2020-11-16 23:31 UTC, teor2345 approved these changes
Looks great, let's merge :-)

2020-11-16 23:31 UTC, merged