Add a Nix derivation for zebrad
ZcashFoundation/zebra pull request #1479
Opened 2020-12-08 10:34 UTC by teor2345

## Motivation

We need to know `zebrad`'s dependencies, and Nix derivations explicitly describe all the dependencies needed to build a piece of software.

Also, Nix users might appreciate this derivation for `zebrad`.

## Solution

Write a Nix derivation that builds `zebrad`.

## Review

@hdevalence has NixOS.

This PR can merge any time after the first alpha release.

## Follow Up Work

There's possibly a cleaner way to do this using `carnix` or the standard Nix Rust tooling. But I don't know if they support the Mozilla Rust overlay, which we need for rustc 1.48.

2020-12-08 10:35 UTC, teor2345 commented
Blocked by the first alpha release.

2020-12-08 10:38 UTC, teor2345 commented on zebrad/nix/zebrad.nix
> +      clang
```suggestion
      # stable updates automatically, select a specific Rust version using:
      #(rustChannelOf { channel = "1.48"; }).rust
      nixpkgs.latest.rustChannels.stable.rust
      # zebra can use any C++ compiler
      clang
```

2020-12-08 10:38 UTC, teor2345 commented on zebrad/nix/zebrad.nix
> +      llvmPackages.libclang
```suggestion
      # bindgen requires libclang
      llvmPackages.libclang
```

2020-12-08 15:31 UTC, dconnolly commented
Neat!

2020-12-14 08:08 UTC, rex4539 requested changes
<details>

```
/Users/rex/rex4539-zebra-nix/zebrad/nix on branch zebrad-nix rex@MacBook-Pro-2018% nix-shell --pure zebrad.nix --run 'zebrad start'
unpacking 'https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz'...
these derivations will be built:
  /nix/store/4ix92iqkdl1kmbpb1qd70m3hh7dgznpw-rust-1.48.0-x86_64-apple-darwin.tar.xz.drv
  /nix/store/ybgn3x0dd843r0xvnq3fx3y7vlr83paf-rust.drv
  /nix/store/mwdvznslyw08lmjin7n5n4xysm44cb1w-rust-1.48.0-2020-11-16-7eac88abb.drv
these paths will be fetched (143.44 MiB download, 720.10 MiB unpacked):
  /nix/store/084qyzx135na3iiqf0hm7ffzv1s94dfp-openssl-1.1.1h
  /nix/store/0ajmkksxkhm7q5sir18nsr8z6pd4w2ma-curl-7.73.0
  /nix/store/0i2mmzbwa3zddbrjcs2p5gjdwgnjqd86-curl-7.73.0-bin
  /nix/store/0q2f9x0f28a3c2325mdhj2kn2qzm888k-libc++-7.1.0
  /nix/store/0rfj7ihn0c8y1z2765i8c8vckbn2x1xs-gawk-5.1.0
  /nix/store/1jljpkadyz98w3yrricrjb62pz25d7w6-gzip-1.10
  /nix/store/2c86b5v2fddbd4l68jglysdqqmdhbjbr-ncurses-6.2-man
  /nix/store/2d9pv0sq9pvma8nqpcwc3miwp44b0g95-libiconv-osx-10.12.6
  /nix/store/2wkq38n95pfcz9ygf30s52rmzi3q9w24-nghttp2-1.41.0-lib
  /nix/store/3fa3w3c5hk5a86i4825sik7kyk13kcc0-cctools-port-949.0.1
  /nix/store/3fjvppl7f8c6x7dr7czhz8vl1kvvwkky-bash-interactive-4.4-p23-doc
  /nix/store/4gvnrs7dl19ih4pvj51d4z2m3crnb5m3-mirrors-list
  /nix/store/570rn44fhng3ihk2axjy51sgy2fbjcrs-lndir-1.0.3
  /nix/store/6p03akh1rxrpxbmkny8pzw002k5jq859-readline-7.0p5
  /nix/store/6v17p59kc0g144qq6llyv4w873axc89w-libkrb5-1.18
  /nix/store/6yxk925rwjyf2kc5l4r76xpjn5lyjazq-libtapi-1000.10.8
  /nix/store/7qz0f05k8wbcqja1zpfkl2k5y8scd0hr-ed-1.16
  /nix/store/8jh0vv8j9l5rrxwdray1b5hzvms2r2f7-zlib-1.2.11
  /nix/store/8r6qgv5ihwkwwa4r4ydjjb0h3hk4viwi-bash-4.4-p23
  /nix/store/8vdglnlk8cxfvz17ixvqcpyw7n9zvsl9-patch-2.7.6
  /nix/store/9rmh3l51xqsry6hsw1c1ahsgd0chlf5n-llvm-7.1.0-lib
  /nix/store/akxyah7f2yf1029dnis92framf62fs7c-libffi-3.3
  /nix/store/ar5wpj78ha6nn38f0dp0xdpz6pm2av1q-openssl-1.1.1h-dev
  /nix/store/c3a1zip68rr57sivvdlqczj3r7ybj1rl-coreutils-8.32
  /nix/store/cbkabcjrs98cyj72ch8m6qq6xy67g8zz-libc++abi-7.1.0
  /nix/store/cw16irj36bx2g1sw6vzv65bgxr3sdm6n-cctools-binutils-darwin-wrapper-949.0.1
  /nix/store/dpi6zy87bi34vkb0mk0va8rq8d1y0yn0-gettext-0.21
  /nix/store/dsm3jzgwppfrs4h24764pxj7l5nd4299-c-ares-1.17.1
  /nix/store/dvmqknys52kjh3hqqh0rsaigh2pjb1dm-ncurses-6.2
  /nix/store/fhc1yw9p188xdm8akrnhq0mdmxiyx69r-gnugrep-3.6
  /nix/store/gdafjxz9p66pm7z2pqa9djg0in828rzv-gnused-4.8
  /nix/store/h0xcqd05vx266wig1v6nkdjn7d07hagq-nghttp2-1.41.0-bin
  /nix/store/h9cbnj7s03znb9q2br9wb2klqsrjfgsg-libev-4.33
  /nix/store/h9dsbqf5n4dzqqi6pfvysbqwcjmxddf1-stdenv-darwin
  /nix/store/hcgdb8dpjw77qgwp2pds28ggrdcnj5fx-binutils-2.31.1
  /nix/store/hk17jddr0ndwfbcqvyd8x9nsxppv3plh-curl-7.73.0
  /nix/store/i6546mzqq2kyvzs41q6p2cjhsfnjqaqw-libxml2-2.9.10
  /nix/store/i84krgpd7wwh81h3rjgm68aynp1j4fla-xz-5.2.5
  /nix/store/i87544wyzsxgnpykqsbbs8caic2a3rrx-adv_cmds-osx-10.5.8-locale
  /nix/store/ia2qh5ady5rjxsmxw4pvcin2136rfzlc-swift-corefoundation
  /nix/store/ir73qgimvg3zfgsqpdl1dhgb9522b0j6-compiler-rt-7.1.0
  /nix/store/j0rxgw5sxac2n2j5bb88lm9d87c9bfhx-clang-7.1.0-lib
  /nix/store/j3n06v02i4g9xs0ha4igncdw1w272kzh-zlib-1.2.11-dev
  /nix/store/j7hpvjc7xi2bb0k7wrdh5cr18nisa4mf-bzip2-1.0.6.0.1
  /nix/store/jrgkaxq2zf2g2zbl865jkly3dyykinam-clang-wrapper-7.1.0
  /nix/store/k0yqjvz195jar243br55pnkrjpksrk00-nghttp2-1.41.0
  /nix/store/k6pvhhm8jx73wlc651x2an47iv70wzd2-bash-interactive-4.4-p23-man
  /nix/store/k7zay6c2c1ynax2hk4abnyhbn9ngrgn5-stdenv-darwin
  /nix/store/kbv0gm6kzsa49gd7hs1kyfb87pcgnxxh-ICU-osx-10.10.5
  /nix/store/lf5ah0irwzxyk3iy6v327i2549f688ch-compiler-rt-7.1.0-dev
  /nix/store/m0zmsfjvh04m6vvb7zzml7gh5cfgc8gc-nss-cacert-3.57
  /nix/store/mvywbssz6ji525cwlq9viaawbp37gfdx-clang-7.1.0
  /nix/store/nhn56y54cjxz2ng3lbxx91w3f1gspwin-libssh2-1.9.0
  /nix/store/nx5h48mnz9jwjw5s02fi67j66pzriq3p-pcre-8.44
  /nix/store/p0946l8cx9jkfm7986mrzgsfxbbw3inb-Libsystem-osx-10.12.6
  /nix/store/pd852x17wab1glhw1ahqacsnlvcidr7a-cctools-binutils-darwin-949.0.1
  /nix/store/pz2zmgx6cxbsf4h8kd2bli7ar6lkb247-libssh2-1.9.0-dev
  /nix/store/r15mwdq69rcdx1qs0swzwcpzyzqpxp5k-nghttp2-1.41.0-dev
  /nix/store/r59jp75kj5i8m09d07khq8n0l73l8951-llvm-7.1.0
  /nix/store/rdijkdly5vaa17s2gkljki1jagpnibd6-bash-interactive-4.4-p23-info
  /nix/store/rvhi7243ln95qhd864x6j6mqkg1lp7q2-gnumake-4.3
  /nix/store/rwr1ylpivkcygm0nakf13377j96jqwg1-gnutar-1.32
  /nix/store/s7giafmjl1m5bx6dnb2cch6k58mhmfkz-nghttp2-1.41.0-lib
  /nix/store/sivfhpz4jqi5dn6aczakd3pc74wcdadl-xz-5.2.5-bin
  /nix/store/wlsq4dd3l8zlm380k26agjz9qqpf0vh5-ncurses-6.2-dev
  /nix/store/wmj4f285nchfr7figsm07kzgad6bj8m4-findutils-4.7.0
  /nix/store/wphaxkb5mlviqpdppyf81467wzs4bnva-openssl-1.1.1h-bin
  /nix/store/x5l2ffyi01f109rk44cihgv71af1jz7z-bash-interactive-4.4-p23
  /nix/store/xhd1q1q6jawr43869kq0hjsjvn1bfqsr-openssl-1.1.1h
  /nix/store/xhnbcm151zsk45x007vwicllycj7xxfl-bzip2-1.0.6.0.1-bin
  /nix/store/xj0lm0hd0vjjdbc5247j6hjcscmf30b4-diffutils-3.7
  /nix/store/xwii2rngzp6ivw03mdy5svnl5j3kkjv2-expand-response-params
  /nix/store/yj2bcpp6lbx1fa17qjlrljb6yypx7hhl-libssh2-1.9.0
  /nix/store/ykhcivbq7izqznf0b8ra156ngnjdb0ln-curl-7.73.0-dev
  /nix/store/z1pjlkm93fcc87xf14sdkjmkzcvx0qv7-gmp-6.2.1
  /nix/store/zd2njxldhrhwkq3f4lkkgcbh2xlvqpn6-bash-interactive-4.4-p23-dev
  /nix/store/zw1k2v10dhdd6y4hgxpz5nsygn44553j-curl-7.73.0-man
copying path '/nix/store/8r6qgv5ihwkwwa4r4ydjjb0h3hk4viwi-bash-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/3fjvppl7f8c6x7dr7czhz8vl1kvvwkky-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/p0946l8cx9jkfm7986mrzgsfxbbw3inb-Libsystem-osx-10.12.6' from 'https://cache.nixos.org'...
copying path '/nix/store/i87544wyzsxgnpykqsbbs8caic2a3rrx-adv_cmds-osx-10.5.8-locale' from 'https://cache.nixos.org'...
copying path '/nix/store/rdijkdly5vaa17s2gkljki1jagpnibd6-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/k6pvhhm8jx73wlc651x2an47iv70wzd2-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/j7hpvjc7xi2bb0k7wrdh5cr18nisa4mf-bzip2-1.0.6.0.1' from 'https://cache.nixos.org'...
copying path '/nix/store/zw1k2v10dhdd6y4hgxpz5nsygn44553j-curl-7.73.0-man' from 'https://cache.nixos.org'...
copying path '/nix/store/xhnbcm151zsk45x007vwicllycj7xxfl-bzip2-1.0.6.0.1-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/7qz0f05k8wbcqja1zpfkl2k5y8scd0hr-ed-1.16' from 'https://cache.nixos.org'...
copying path '/nix/store/xwii2rngzp6ivw03mdy5svnl5j3kkjv2-expand-response-params' from 'https://cache.nixos.org'...
copying path '/nix/store/0rfj7ihn0c8y1z2765i8c8vckbn2x1xs-gawk-5.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/rvhi7243ln95qhd864x6j6mqkg1lp7q2-gnumake-4.3' from 'https://cache.nixos.org'...
copying path '/nix/store/gdafjxz9p66pm7z2pqa9djg0in828rzv-gnused-4.8' from 'https://cache.nixos.org'...
copying path '/nix/store/1jljpkadyz98w3yrricrjb62pz25d7w6-gzip-1.10' from 'https://cache.nixos.org'...
copying path '/nix/store/cbkabcjrs98cyj72ch8m6qq6xy67g8zz-libc++abi-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/akxyah7f2yf1029dnis92framf62fs7c-libffi-3.3' from 'https://cache.nixos.org'...
copying path '/nix/store/0q2f9x0f28a3c2325mdhj2kn2qzm888k-libc++-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/2d9pv0sq9pvma8nqpcwc3miwp44b0g95-libiconv-osx-10.12.6' from 'https://cache.nixos.org'...
copying path '/nix/store/6v17p59kc0g144qq6llyv4w873axc89w-libkrb5-1.18' from 'https://cache.nixos.org'...
copying path '/nix/store/kbv0gm6kzsa49gd7hs1kyfb87pcgnxxh-ICU-osx-10.10.5' from 'https://cache.nixos.org'...
copying path '/nix/store/ir73qgimvg3zfgsqpdl1dhgb9522b0j6-compiler-rt-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/dpi6zy87bi34vkb0mk0va8rq8d1y0yn0-gettext-0.21' from 'https://cache.nixos.org'...
copying path '/nix/store/lf5ah0irwzxyk3iy6v327i2549f688ch-compiler-rt-7.1.0-dev' from  [...]

2021-02-15 20:03 UTC, dconnolly approved these changes
Is there a known/obvious way to test that this stays working as part of our CI?

2021-02-15 20:38 UTC, teor2345 commented on zebrad/nix/zebrad.nix
> +        --tag v1.0.0-alpha.0 \
For CI, we should build from a file path, not a remote tag.

2021-02-15 20:42 UTC, teor2345 commented
> Is there a known/obvious way to test that this stays working as part of our CI?

Install Nix using a GitHub action, then build the Nix derivation:
https://github.com/marketplace/actions/install-nix

Optional extras:
* run zebrad help, or something simple, to make sure the linking all works
* transition to building using cached Rust crates, if possible
* cache the built package to speed up rebuilds (only worth it if we can use cached rust crates): https://github.com/marketplace/actions/cache-install-nix-packages
* use this template repository: https://github.com/nix-dot-dev/getting-started-nix-template

2021-02-25 10:23 UTC, teor2345 commented
Instead of manually creating a nix derivation or nix-shell script, interested users should use crate2nix or cargo2nix to automatically generate the file.

So it doesn't look like we actually need to do any work to support this use case.

https://github.com/kolloch/crate2nix
https://github.com/cargo2nix/cargo2nix

These tools build each crate as a separate re-usable package, only rebuilding when dependencies change. So they might be a lot faster than sccache for CI, and dev workflows that clear caches. (sccache is less efficient than Nix, because it deals with dependencies at the file level, rather than the package level.)

2021-02-25 10:23 UTC, closed without merging