[WIP] Async DNS lookups
ZcashFoundation/zebra pull request #1662
Opened 2021-01-31 20:54 UTC by oxarbitrage

## Motivation

I am trying to replace `to_socket_addrs()` with my crated function `resolve()`. This is work in progress for https://github.com/ZcashFoundation/zebra/issues/1631

So i basically will want to replace https://github.com/oxarbitrage/zebra/blob/8a9a32b2f4f3e1e735def4ade717884885184243/zebra-network/src/config.rs#L46 with https://github.com/oxarbitrage/zebra/blob/8a9a32b2f4f3e1e735def4ade717884885184243/zebra-network/src/config.rs#L42 where `replace` is a new custom function that should return the same data.

`to_socket_addrs()` returns `Result<Iterator>` but `replace()` returns `Option<Iterator>` which are not the same. This can be a first issue.

Additionally i think there is something else, according to some hints i got from @teor2345 in discord something like this will need to be added to the combination:

https://github.com/ZcashFoundation/zebra/blob/4f172ab6747de137fc8c1ead27290b4c27816ad5/zebrad/src/components/inbound.rs#L257

Which makes the implementation even more complicated for my skills. Looking for some additional hints to make more progress here.
  
## Solution

Share the problem with others.

The code in this pull request has:
  - [ ] Documentation Comments
  - [ ] Unit Tests and Property Tests

## Review

I will like @yaahc or @teor2345 to take a look.

## Related Issues

https://github.com/ZcashFoundation/zebra/issues/1631

## Follow Up Work

None by now.

2021-02-01 03:06 UTC, teor2345 requested changes
Hi @oxarbitrage I've made some suggestions to help move you forward.

I've also tagged @yaahc in some questions that she's better able to answer.

2021-02-01 03:06 UTC, teor2345 commented on zebra-network/src/peer_set/initialize.rs
> +        add_initial_peers(initial_peers.await, connector, tx)
Calling `await` here blocks the main thread on DNS.

Instead, turn the `initial_peers_fut` into an async block, to move the work into the spawned task:
```rust
let initial_peers_fut = async {
    ...
}.boxed()
```

You might need to move the `connector` and `tx` clones out of the async block, so the future doesn't take ownership of the original `connector` and `peerset_tx`.

2021-02-01 03:06 UTC, teor2345 commented on zebra-network/src/config.rs
> +                tracing::warn!("Timeout trying to resolve {:?}: {:?}", s, e);
We try to keep fields separate in `tracing` messages:
https://docs.rs/tracing/0.1.22/tracing/#recording-fields

So that the tracing logs make sense, we need to give fields meaningful names.

Since we have multiple DNS servers, these errors can be logged at info-level.

```suggestion
                tracing::info!(?host, ?e, "DNS error resolving peer IP address");
                HashSet::new()
            }
            Err(e) => {
                tracing::info!(?host, ?e, "DNS timeout resolving peer IP address");
```

2021-02-01 03:06 UTC, teor2345 commented on zebra-network/src/config.rs
> +        let fut = tokio::time::timeout(Duration::from_nanos(1), fut);
Let's set a timeout of 5 seconds, and make it into a constant.

For example:
```rust
pub const DNS_LOOKUP_TIMEOUT: Duration = Duration::from_secs(5);
```

2021-02-01 03:06 UTC, teor2345 commented on zebra-network/src/config.rs
> +                None
You might need to take a generic type. And it might be easier to convert to a HashSet before returning.

Let's also be a bit clearer with the function and argument names, and document the function.

Since we've documented the function, we don't really need comments inside the function as well. We use comments inside functions to explain how complicated code works, or why code is written in a particular way.

(Sorry about the overlapping suggestions, I thought it would be easier to read them separately.)

```suggestion
    /// Resolves `host` into zero or more IP addresses.
    ///
    /// If `host` is a DNS name, performs DNS resolution with a timeout of a few
    seconds. If DNS resolution fails or times out, returns an empty list.
    async fn resolve_host<S: ToSocketAddrs>(host: S) -> HashSet<SocketAddr> {
        let fut = tokio::net::lookup_host(host);
        let fut = tokio::time::timeout(DNS_LOOKUP_TIMEOUT, fut);

        match fut.await {
            Ok(Ok(ips)) => ips.collect(),
            Ok(Err(e)) => {
                tracing::info!(?host, ?e, "DNS error resolving peer IP address");
                HashSet::new()
```

2021-02-01 03:06 UTC, teor2345 commented on zebra-network/src/config.rs
>              .flat_map(|s| s.to_socket_addrs())
Now you have a `resolve_host` function that takes a single `host` name, and returns a future that yields a list of zero or more addresses.

Next, you need to:
1. Run all the host name lookups concurrently
2. Collect the results
3. Log a warning if the combined list of results is empty

So you want code that looks a bit like this.

I've added comments to explain what each line does - please remove them if you copy and paste this code.
```rust
        use futures::stream::StreamExt;
        // See https://docs.rs/futures/0.3.12/futures/stream/trait.StreamExt.html
        let peer_addresses = peers
            // make the list of peers into an iterator
            .into_iter()
            // create a DNS resolution future for each peer
            .map(Config::resolve_host)
            // collect the DNS futures into a concurrent (unordered) stream of futures
            .collect::<futures::stream::FuturesUnordered<_>>()
            // combine the results of those futures into a HashSet<SocketAddr>
            .concat()
            // finally, run the futures concurrently, and get the result
            .await;

        if (peer_addresses.is_empty()) {
            tracing::warn!(?peers, ?peer_addresses, "empty peer list after DNS resolution");
        }
```

@yaahc might be able to help you get the errors from inside `resolve_host` to the final warning in this function. But let's get the simple version of this code working first.

2021-02-01 03:06 UTC, teor2345 commented on zebra-network/src/config.rs
You might need to replace the `std::net::ToSocketAddrs` import with `tokio::net::ToSocketAddrs`.

2021-02-01 13:33 UTC, oxarbitrage commented on zebra-network/src/config.rs
> +                tracing::warn!("Timeout trying to resolve {:?}: {:?}", s, e);
Thanks. I added this at https://github.com/ZcashFoundation/zebra/pull/1662/commits/8a0c173391102153bee50edfc1ee90e3fa69179e

2021-02-01 13:35 UTC, oxarbitrage commented on zebra-network/src/config.rs
> +                None
Agree on everything except for the generic type argument. I dont see a need to do that yet, i might change my mind later as i see some evidence on why it is better than the string. By now i added all the other suggestions at https://github.com/ZcashFoundation/zebra/pull/1662/commits/8a0c173391102153bee50edfc1ee90e3fa69179e

2021-02-01 15:52 UTC, oxarbitrage commented on zebra-network/src/config.rs
>              .flat_map(|s| s.to_socket_addrs())
Ok, this is great and where i am lacking the most. I will try to learn from this, thank you.

I applied it at https://github.com/ZcashFoundation/zebra/pull/1662/commits/65c4ed50a5e7f11c607a3a5c668a957fdc2facd2 where i also replaced the `ToSocketAddrs` argument from `parse_peers()` with a `String`.

2021-02-01 22:00 UTC, oxarbitrage commented on zebra-network/src/peer_set/initialize.rs
> +        add_initial_peers(initial_peers.await, connector, tx)
If we do this we get an error in https://github.com/ZcashFoundation/zebra/blob/19a31ebfc35a7286b2ce0f5faa425e8661be552f/zebra-network/src/peer_set/initialize.rs#L175

```
mismatched types

expected enum `std::result::Result`, found opaque type

note: expected struct `tokio::task::JoinHandle<std::result::Result<(), std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>>`
         found struct `tokio::task::JoinHandle<impl futures::Future>`
help: consider using `.await` here: `add_guard.await`rustc(E0308)
```
Adding `await` here as suggested by the compiler does not work.

2021-02-01 22:28 UTC, yaahc commented on zebra-network/src/peer_set/initialize.rs
> +        add_initial_peers(initial_peers.await, connector, tx)
@oxarbitrage I think you more or less had it, you just needed an extra await inside of the new async block. You still need to resolve the future within the async block, so you're gonna write something like this

```rust
async {
    // ...
    let initial_peers = initial_peers.await;
    add_initial_peers(initial_peers, connector, tx)
```

2021-02-01 22:38 UTC, yaahc commented on zebra-network/src/peer_set/initialize.rs
> +        add_initial_peers(initial_peers.await, connector, tx)
to clarify further, the issue was the missing _second_ await. You ended up trying to include a `JoinHandle<impl Future>` where it expected a `JoinHandle<Result<...>>`. If you leave out the `await` it doesn't resolve the future returned by `add_initial_peers` wihch means the return type for the entire async block is `Future<Item = impl Future>`, aka a Future that returns another Future. By resolving the inner future we make it so our async block's return type is the same as the inner future's return type, which lets us use it as a drop in replacement.

2021-02-01 22:42 UTC, oxarbitrage commented on zebra-network/src/peer_set/initialize.rs
> +        add_initial_peers(initial_peers.await, connector, tx)
Ok, that was dumb from my side. I got confused with the error but your fix works, i am having some issues with some borrow values but i will get them sorted out and push a commit. Thanks!

2021-02-01 22:55 UTC, oxarbitrage commented on zebra-network/src/peer_set/initialize.rs
> +        add_initial_peers(initial_peers.await, connector, tx)
So i added this at https://github.com/ZcashFoundation/zebra/pull/1662/commits/151641b8aed5096f28dccd520917f43ac12f3876
Maybe some of the clones can be avoided but it seems to be doing what we need. Thanks again @yaahc

2021-02-01 22:56 UTC, teor2345 commented on zebra-network/src/config.rs
> +                None
If we don't need the generic, we can just leave it out.

2021-02-01 22:57 UTC, teor2345 commented on zebra-network/src/config.rs
If we don't need the generic, we don't need this change.

2021-02-01 22:58 UTC, teor2345 commented on zebra-network/src/peer_set/initialize.rs
> +        add_initial_peers(initial_peers.await, connector, tx)
@yaahc or I can show you how to remove the clones, just to tidy up the code.

(But that's not an important change.)

2021-02-01 22:59 UTC, teor2345 commented on zebra-network/src/config.rs
> +        // See https://docs.rs/futures/0.3.12/futures/stream/trait.StreamExt.html
We don't need this comment :-)
```suggestion
```

2021-02-01 23:01 UTC, teor2345 commented on zebra-network/src/config.rs
> +    async fn parse_peers(peers: HashSet<String>) -> HashSet<SocketAddr> {
Let's document this function:
```suggestion
    /// Resolves `host` into zero or more IP addresses.
    ///
    /// If `host` is a DNS name, performs DNS resolution with a timeout of a few
    /// seconds. If DNS resolution fails or times out, returns an empty list.
    async fn resolve_peers(peers: HashSet<String>) -> HashSet<SocketAddr> {
```

2021-02-01 23:04 UTC, teor2345 commented on zebra-network/src/config.rs
> +    async fn parse_peers(peers: HashSet<String>) -> HashSet<SocketAddr> {
Let's document this function as well:
```suggestion
    /// Concurrently resolves `peers` into zero or more IP addresses, with a timeout
    /// of a few seconds on each DNS request.
    ///
    /// If DNS resolution fails or times out for all peers, returns an empty list.
    async fn parse_peers(peers: HashSet<String>) -> HashSet<SocketAddr> {
```

2021-02-01 23:05 UTC, teor2345 commented on zebra-network/src/constants.rs
> +/// [6.1.3.3  Efficient Resource Usage] from RFC [Requirements for Internet Hosts]
Just a minor tidy up - most RFCs are identified by number and title
```suggestion
/// [6.1.3.3  Efficient Resource Usage] from [RFC 1123: Requirements for Internet Hosts]
```

2021-02-03 00:47 UTC, teor2345 commented on zebra-network/src/config.rs
> +            .map(|s| Config::resolve_host(s))
This line uses deref-coercion to convert `&String` to `&str`:
https://doc.rust-lang.org/book/ch15-02-deref.html
https://doc.rust-lang.org/std/string/struct.String.html#deref

2021-02-03 00:48 UTC, teor2345 commented on zebra-network/src/peer_set/initialize.rs
> +        .boxed()
These clones are all needed, but if we put them in a block `{ ... }`, then we don't need to use special names for them.

The names are bound to the clones inside the block, but they are bound to the originals once the block ends.

2021-02-03 00:49 UTC, teor2345 approved these changes
I'm good with this now, but I'd like @oxarbitrage to check the changes I just made.

2021-02-03 00:57 UTC, oxarbitrage reviewed
Changes looks good to me.

2021-02-03 02:20 UTC, merged