Revert "Test: Revert "Refactor `connection.rs` to make `fail_with` errors impossible""
ZcashFoundation/zebra pull request #1817
Opened 2021-02-25 00:11 UTC by yaahc

Reverts ZcashFoundation/zebra#1803

The reverts will continue until moral (sync speed) improves

2021-03-04 00:28 UTC, dconnolly approved these changes

2021-03-04 00:28 UTC, dconnolly commented
Pending merge conflict fix

2021-03-04 01:09 UTC, teor2345 requested changes
This PR causes multiple errors during message processing, which slows down sync a lot.

We need to work out what's going wrong with the `Connection` state machine, and fix it.

I have some ideas for a design that would make this code a lot easier to maintain. @yaahc let's chat when you're ready to work on this?

2021-03-04 02:36 UTC, teor2345 commented
I also wonder if we should implement the sync/connection tests in #1592 before merging this PR.

2021-03-20 01:02 UTC, yaahc commented
So status report from where I left this. The issue with this PR currently is that it causes the sync component to restart syncing in response to mixed inventory errors. The previous version seems to somehow not error out in a way that restarts syncing when it encounters these same errors. The next steps are to figure out how the current version handles mixed inventory errors, and see how that differs from the refactor.

2021-03-22 20:48 UTC, teor2345 commented
It's also worth noting that these errors have an outsized impact because:
* they seem to trigger connection failure bugs like #1905 
* they restart the sync, causing a delay of at least a minute per error, and even more due to pipeline error persistence #1590
* Zebra should just split small mixed inv responses (merging those responses is a zcashd bug) #1768
* 
it's weird that the current connection code appears to be dropping some of these errors - or at least responding to them differently.

But regardless of the fragility of this code and its context, we still need to make sure the refactor performs as well as the previous code.

2021-03-31 00:56 UTC, teor2345 commented
We've decided to close this PR for now, see ticket #1610 for next steps.

2021-03-31 00:56 UTC, closed without merging