Jane/nu5
ZcashFoundation/zebra pull request #1823
Opened 2021-02-26 22:17 UTC by yaahc

## Motivation

We want to add a `NetworkUpgrade::NU5` network upgrade variant, and a network protocol version for `NU5`.

## Solution

This change updates various enums and constants to include variants for `NU5`.

The code in this pull request has:
  - [x] Documentation Comments
  - [x] Unit Tests and Property Tests

## Review

@teor2345 

## Related Issues

https://github.com/ZcashFoundation/zebra/issues/1797

## Follow Up Work

Need to implement actual `NU5` logic, currently we panic if `NU5` code paths get executed.

2021-02-27 16:45 UTC, oxarbitrage approved these changes, later dismissed
Looks good to me.

2021-03-01 00:32 UTC, teor2345 submitted a review, later dismissed
Approved with changes and suggestions

Here's what I checked:
* the consensus branch id matches the draft spec
* the external network protocol versions match the draft spec

Here's what I suggested:
* the specific change and ZIP for each `unimplemented!()`
* remove `unimplemented!()` where there is no suggested change

Here's what I committed:
*  add NU5 to the `protocol::version_consistent` test ae76f99

This change isn't required until we have a testnet or mainnet activation height for NU5, but we might as well do it now.

2021-03-01 00:32 UTC, teor2345 commented on zebra-chain/src/block/root_hash.rs
> +            NU5 => unimplemented!("NU5 upgrade is still in progress and not fully implemented"),
```suggestion
            Heartwood | Canopy => ChainHistoryRoot(ChainHistoryMmrRootHash(bytes)),
            NU5 => unimplemented!("NU5 uses hashAuthDataRoot as specified in ZIP-244"),
```

2021-03-01 00:32 UTC, teor2345 commented on zebra-chain/src/parameters/network_upgrade.rs
> +    /// The Zcash protocol after the NU5 upgrade.
```suggestion
    /// The Zcash protocol after the NU5 upgrade.
    ///
    /// Note: Network Upgrade 5 includes the Orchard Shielded Protocol, and
    /// other changes. The NU5 code name has not been chosen yet.
```

2021-03-01 00:32 UTC, teor2345 commented on zebra-chain/src/parameters/network_upgrade.rs
> +            NU5 => unimplemented!("NU5 upgrade is still in progress and not fully implemented"),
There are no proposed changes to block target spacing in NU5:
https://github.com/zcash/zips/pull/446/files#r583311733

```suggestion
            Blossom | Heartwood | Canopy | NU5 => POST_BLOSSOM_POW_TARGET_SPACING,
```

2021-03-01 00:32 UTC, teor2345 commented on zebra-chain/src/transaction/arbitrary.rs
> +                unimplemented!("NU5 upgrade is still in progress and not fully implemented")
```suggestion
                unimplemented!("NU5 upgrade can use v4 or v5 transactions, as specified in ZIP-225")
```

2021-03-01 00:32 UTC, teor2345 commented on zebra-chain/src/transaction/sighash.rs
> +            NU5 => unimplemented!("NU5 upgrade is still in progress and not fully implemented"),
```suggestion
            NU5 => unimplemented!("NU5 upgrade uses a new transaction digest algorithm, as specified in ZIP-244"),
```

2021-03-01 00:35 UTC, teor2345 commented on zebra-chain/src/transaction/sighash.rs
> +            NU5 => unimplemented!("NU5 upgrade uses a new transaction digest algorithm, as specified in ZIP-244"),
Rustfmt
```suggestion
            NU5 => unimplemented!(
                "NU5 upgrade uses a new transaction digest algorithm, as specified in ZIP-244"
            ),
```

2021-03-01 00:40 UTC, teor2345 commented
Since my suggestions were trivial, I went ahead and committed them.

2021-03-01 02:58 UTC, teor2345 commented
@oxarbitrage or @yaahc, can you double-check that:
- [ ] Each instance of `Canopy` in the codebase has a corresponding `NU5`

This only matters for non-wildcard matches.

2021-03-01 12:08 UTC, oxarbitrage submitted a review, later dismissed
Thank you for the last changes @teor2345 , looks a lot better.

2021-03-01 22:17 UTC, teor2345 commented
> @oxarbitrage or @yaahc, can you double-check that:
> 
>     * [ ]  Each instance of `Canopy` in the codebase has a corresponding `NU5`
> 
> 
> Let's focus on wildcard matches and other code that the compiler doesn't automatically pick up.

Has anyone double-checked this?

2021-03-01 22:18 UTC, teor2345 requested changes
We need to double-check that each instance of `Canopy` in the codebase has a corresponding `NU5`.

- [x] @teor
- [ ] @yaahc 
- [ ] @oxarbitrage

2021-03-02 19:50 UTC, oxarbitrage commented
We don't have an element for `NU5` in `MAINNET_ACTIVATION_HEIGHTS` and `TESTNET_ACTIVATION_HEIGHTS` because we don't know the exact block for this upgrade yet. However, we can add a placeholder there with block height `10_000_000` or something like that(with a `todo` comment to change it). If we do this or if we don't i think we should open a ticket to add(or modify) the block height for `NU5` when this info became available.

The rest looks good in regards to all the instances of `Canopy`(specially all matches) have a corresponding `NU5`.

2021-03-02 19:52 UTC, yaahc commented
@oxarbitrage you beat me to it but I just made a commit adding some `TODO` comments to the file, and I'll go ahead and add this follow up task to the checklist in the original issue

2021-03-02 20:21 UTC, teor2345 commented
> We don't have an element for `NU5` in `MAINNET_ACTIVATION_HEIGHTS` and `TESTNET_ACTIVATION_HEIGHTS` because we don't know the exact block for this upgrade yet. However, we can add a placeholder there with block height `10_000_000` or something like that(with a `todo` comment to change it).

We want to avoid implementing incorrect consensus rules, because:
* some Zebra instances might not be upgraded, so they will have the wrong rules
* people will get confused when they read our code

Zebra should work if some network upgrades don't have an activation height. So we can just add it when it is decided.

2021-03-02 20:22 UTC, teor2345 approved these changes
Looks great, let's merge!

2021-03-02 20:22 UTC, merged