Checkpoint on Canopy
ZcashFoundation/zebra pull request #1898
Opened 2021-03-12 21:13 UTC by oxarbitrage

## Motivation

We want to checkpoint in Canopy to avoid the development of some validation code. More details in https://github.com/ZcashFoundation/zebra/issues/1846 

## Solution

Change the mandatory checkpoint from Sapling to Canopy in the testnet and in the mainnet.

I synchronized zebra using this PR up to tip in 2 hours and 40 minutes. This is an improve (expected) from the last tries in the same machine of 3 hours.

In this PR mainnet checkpoints were upgraded while testnet ones were already passing Canopy so this was not needed.

## Review

@teor2345 

## Related Issues

If merged this PR will close https://github.com/ZcashFoundation/zebra/issues/1846

2021-03-14 22:13 UTC, teor2345 commented
> In this PR mainnet checkpoints were upgraded while testnet ones were already passing Canopy so this was not needed.

Please update both mainnet and testnet checkpoints for consistency. Otherwise, our testnet checkpoints will be very old.

2021-03-14 22:17 UTC, teor2345 requested changes
Looks good, just missing an update to the testnet checkpoints. (And a few typos.)

I already have that synced, so I'll start generating the list now, and push it to this branch when it's done.

I also want to checkout this PR, and make sure we've replaced every relevant instance of Sapling with Canopy.

2021-03-14 22:17 UTC, teor2345 commented on zebra-consensus/src/checkpoint/list/tests.rs
>  /// Check that the hard-coded lists cover the Sapling network upgrade
```suggestion
/// Check that the hard-coded lists cover the Canopy network upgrade
```

2021-03-14 22:17 UTC, teor2345 commented on zebra-consensus/src/checkpoint/list/tests.rs
> +    let sapling_activation = Canopy
```suggestion
    let canopy_activation = Canopy
```

2021-03-15 00:51 UTC, teor2345 commented
> > In this PR mainnet checkpoints were upgraded while testnet ones were already passing Canopy so this was not needed.
> 
> Please update both mainnet and testnet checkpoints for consistency. Otherwise, our testnet checkpoints will be very old.

I pushed this change.

In general, we want to keep both checkpoint lists up to date, whenever we change one of them.

2021-03-15 00:55 UTC, teor2345 commented
> I also want to checkout this PR, and make sure we've replaced every relevant instance of Sapling with Canopy.

There were lots of missing changes.

Please use an interactive search and replace tool to create future PRs like this.

I used the following commands:
```sh
fastmod Sapling Canopy
fastmod sapling canopy
fastmod sapling canopy .github
```

Then I checked each change to make sure that it was correct. (Sapling is the name of a network upgrade, and a shielded pool, so we can't just do an automatic search and replace.)

The `.github` command was required because `fastmod` ignores dotfiles by default.
(I also needed to remove smart quotes, due to a bug in `fastmod`'s unicode handling. See #1902.)

2021-03-15 00:55 UTC, teor2345 commented
@dconnolly this PR changes the cached tests to use Canopy, so it will require a cached state rebuild.

Can you show @oxarbitrage how to do that?

2021-03-15 01:02 UTC, teor2345 reviewed
@oxarbitrage can you check my changes to make sure they're ok?

I also added some follow-up tasks.

2021-03-15 01:02 UTC, teor2345 commented on book/src/dev/rfcs/0005-state-updates.md
> +1. If the block is a pre-Canopy block, panic.
I can't actually see where we do this check in the code, maybe we need to open a follow-up issue.

2021-03-15 01:06 UTC, teor2345 commented on book/src/dev/rfcs/0005-state-updates.md
> +1. If the block is a pre-Canopy block, panic.
This is now #1903

2021-03-15 12:18 UTC, oxarbitrage reviewed
- I didn't changed the RFCs in the initial PR because i wasn't sure if that was something we should do, for example i am unsure if a ZIP can be changed after is implemented. In this case i think is ok.
- I didn't added new testnet checkpoints by lack of time on Friday(had to sync a zcashd testnet), thanks for adding them.
- I missed some changes, thanks for the fixes.

Looks good.

2021-03-15 12:45 UTC, teor2345 approved these changes
@oxarbitrage has checked my changes, and I've checked his.

Leaving this PR open so @dconnolly can check the cached state changes if she wants.

2021-03-15 12:46 UTC, teor2345 commented
>     * I didn't changed the RFCs in the initial PR because i wasn't sure if that was something we should do, for example i am unsure if a ZIP can be changed after is implemented. In this case i think is ok.

In general, I don't think we need to spend a lot of effort updating RFCs - if there is a significant change, we should do a rewrite or a new RFC.

But in this case, it took only a few minutes to update. And I didn't want us to get confused between Sapling and Canopy checkpoints.

2021-03-18 00:12 UTC, teor2345 approved these changes
This is fine

2021-03-18 00:13 UTC, merged