Implement seamare, seamare-lint, cargo-seamare
ZcashFoundation/zebra pull request #1907
Opened 2021-03-15 14:36 UTC by WindSoilder

## Motivation

Handle for #1582

## Solution

Refer to the top level of **MVP checklist** of this issue:
 - [X] create three new crates in `zebra`
 - [X] copy the various lint trait definitions defined in guppy into seamare
 - [X] copy the [duplicate dependencies](https://github.com/diem/diem/blob/76576974dc47bada937c2851b62060a43fc0bd55/devtools/x/src/lint/guppy.rs#L262-L311) lint from diem into `seamare-lints/src/duplicate_deps.rs`
 - [X] In cargo-seamare: create a LintEngine that loads the package graph via guppy, takes a set of types that implement these various traits, and then executes each of the lints via the traits against the package graph

The code in this pull request has:
  - [X] Documentation Comments
  - [ ] Unit Tests and Property Tests

Since the code in this PR is most copy-paste from [x-linter](https://github.com/diem/diem/tree/main/devtools), here is one main difference between them:

`x-linter` is highly depends on [x-core](https://github.com/diem/diem/tree/main/devtools/x-core), which provide the core context for the linter to run, seamare doesn't make use of `x-core`, instead, it use a new simplied version [context](https://github.com/WindSoilder/zebra/blob/main/seamare/src/core_context.rs)

Here is the reason:

When we want to make use of [XCoreContext](https://github.com/diem/diem/blob/master/devtools/x-core/src/lib.rs#L38), `project_root` attribute is reauired.  In `x` implementation, the `project_root` is specified by [CARGO_MANIFEST_DIR](https://github.com/diem/diem/blob/main/devtools/x/src/utils.rs#L13), but it's useless when we want to run `cargo-seamare` inside another project.  And as the [comment point out](https://github.com/diem/diem/blob/master/devtools/x-core/src/lib.rs#L38), the `project-root` should be managed by this context, and it makes upstream code more easiler to use.

## Review

## Related Issues

#1582

## Follow Up Work

Handle for **Additional Goals** of the relative issue, add ut for entire seamare codebase.

2021-03-15 22:12 UTC, teor2345 commented
@yaahc can you review this PR when you get some time?

2021-03-15 23:52 UTC, yaahc commented
> @yaahc can you review this PR when you get some time?

on it

also cc @sunshowers

2021-03-16 21:58 UTC, yaahc requested changes
This looks perfect btw. Just need to clean up some of the `TODO` comments and the error handling a bit.

Additionally, as a basic test could you add a new job to our `ci.yml` github action that installs `cargo seamare` and then runs it against zebra?

Thank you again for the PR.

2021-03-16 21:58 UTC, yaahc commented on cargo-seamare/src/lint_engine.rs
> +// TODO: I don't know if we need `PackageLinter`, `FilePathLinter`, `ContentLinter`, but for now, let's keep them here.
```suggestion
```

:+1:

2021-03-16 21:58 UTC, yaahc commented on seamare/src/content.rs
> +// TODO: it's just copied from x-linter, maybe we don't need this `ContentLinter` and `ContentContext`?
```suggestion
```

I think we will want this eventually, the plan is to make `cargo seamare` and friends generally available to the rust community, so I expect further lints will get added in the future.

2021-03-16 21:58 UTC, yaahc commented on seamare/src/file_path.rs
> +// TODO: it's just coped from x-linter, maybe we don't need this `FilePathLinter` and `FilePathContext`?
```suggestion
```

Same as before, I think we will want these eventually so leave them in

2021-03-16 21:58 UTC, yaahc commented on seamare/src/package.rs
> +// TODO: it's just coped from x-linter, maybe we don't need this `PackageLinter` and `PackageContext`?
```suggestion
```

We will want this eventually I expect

2021-03-16 21:58 UTC, yaahc commented on seamare/src/core_context.rs
> +// TODO: maybe it's better to store `project_root` field like what x-linter does.
I'm assuming this is fine the way you wrote it but cc @sunshowers in case they know of a reason we'd want to match what x-linter does.

2021-03-16 21:58 UTC, yaahc commented on seamare/src/error.rs
> +    IO(#[from] std::io::Error),
I'm a little worried about these errors, can we remove the `From` impl from the first one and add a `.map_err(SeamareError::IO)` wherever necessary? ?

```suggestion
    IO(#[source] std::io::Error),
```

2021-03-16 21:58 UTC, yaahc commented on seamare/src/error.rs
> +    #[error("Build package graph failed")]
```suggestion
    #[error("unable to build package graph")]
```

2021-03-16 21:58 UTC, yaahc commented on seamare/src/error.rs
> +    Guppy(#[from] guppy::Error),
```suggestion
    Guppy(#[source] guppy::Error),
```

2021-03-17 04:40 UTC, WindSoilder commented
Because relative context needs to be keep inside seamare, there is one more thing need to note about the different:

`seamare/src/package::PackageContext` doesn't have `is_default_member` field, and don't have relative `is_default_member` fucntion.

But [x-lint PackageContext](https://github.com/diem/diem/blob/master/devtools/x-lint/src/package.rs#L27) does.

Here is the reason:

`is_default_member` only work for [OverlayFeatures](https://github.com/diem/diem/blob/main/devtools/x/src/lint/guppy.rs#L293) package linter, it seems that it's not required in `seamare` now.

If we need `is_default_member` field, we can implement it in another way.

2021-03-17 19:30 UTC, yaahc commented
> Hi, all of them except one `TODO` tag are resolved, but here is one update:

Awesome, ty

> Because relative context needs to be keep inside `seamare`, there is one more thing need to note about the difference:
> 
> `seamare/src/package::PackageContext` doesn't have `is_default_member` field, and don't have relative `is_default_member` fucntion.
> 
> But [x-lint PackageContext](https://github.com/diem/diem/blob/master/devtools/x-lint/src/package.rs#L27) does.
> 
> Here is the reason:
> 
> `is_default_member` only work for [OverlayFeatures](https://github.com/diem/diem/blob/main/devtools/x/src/lint/guppy.rs#L293) package linter, it seems that it's not required in `seamare` now. To make `copy-paste` action easiler, I just remove it for now...
> 
> If we need `is_default_member` field, we can implement it in another way.

Sounds good to me. We should be able to add this later when we need it so I'm not to worried about including that field at this stage.

2021-03-23 04:43 UTC, teor2345 commented
@yaahc @WindSoilder is there anything left to do on this PR, or should we just merge it?

Can you update the PR title and motivation with a summary of the tests that cargo-seamare does?

We'll need the summary for our changelog.

2021-03-23 07:37 UTC, WindSoilder commented
I thinks it's hanged on @sunshowers review, but I don't know when this can be done.

> Can you update the PR title and motivation with a summary of the tests that cargo-seamare does?

Update it.

2021-03-23 14:02 UTC, sunshowers commented
Ahh I'm going to try getting this done this week but please don't block on me, have a lot going on IRL at the moment

2021-03-24 00:04 UTC, teor2345 commented
> Ahh I'm going to try getting this done this week but please don't block on me, have a lot going on IRL at the moment

To be clear, this isn't urgent at all, take all the time you need.

I was just going through our PRs to make sure we all know where they're at.

2021-10-21 23:23 UTC, teor2345 commented
I'm going to mark this PR as draft, until the Zebra team decides how we want to move forward with it.
(Hopefully we'll have a DevOps person soon, and they can give it some attention.)

2021-10-26 01:48 UTC, teor2345 commented
I think we might end up using `cargo deny check bans`, instead of merging this PR:
https://embarkstudios.github.io/cargo-deny/checks/bans/index.html#use-case---duplicate-version-detection

But please let us know if you finish off this tool, and we'll check it out.

2021-10-26 01:48 UTC, closed without merging