Add external_addr to config (network section)
ZcashFoundation/zebra pull request #2035
Opened 2021-04-19 19:48 UTC by fanatid

## Motivation

Allow `zebrad` advertise address specified by user.

## Solution

Add `external_addr` to config (network section).

- In the diagram, I see that listen port (address) should be in AddressBook but I can not find code where `listen_addr` added to AddressBook. Can you help with this? https://github.com/ZcashFoundation/zebra/blob/2cecd52a106a8747f2510147481ceb3e372929a7/zebra-network/src/peer_set/candidate_set.rs#L46

The code in this pull request has:
  - [ ] Documentation Comments
  - [ ] Unit Tests and Property Tests

## Related Issues

#1890 

## Follow Up Work

Allow set only IP address in `listen_addr` (default port from `Network` enum).
https://github.com/ZcashFoundation/zebra/blob/2cecd52a106a8747f2510147481ceb3e372929a7/zebra-network/src/peer_set/initialize.rs#L127-L128

2021-04-19 20:50 UTC, teor2345 commented
> * In the diagram, I see that listen port (address) should be in AddressBook but I can not find code where `listen_addr` added to AddressBook. Can you help with this?

I think that diagram is a bit confusing, maybe we should say "Inbound Peer Connections to the zebrad listener port".

2021-04-19 20:58 UTC, teor2345 commented
> > * In the diagram, I see that listen port (address) should be in AddressBook but I can not find code where `listen_addr` added to AddressBook. Can you help with this?
> 
> I think that diagram is a bit confusing, maybe we should say "Inbound Peer Connections to the zebrad listener port".

#2036 might help here, I updated the docs.

2021-04-19 21:58 UTC, dconnolly commented
Looks like rustfmt doesn't like the space on one line, causing rustfmt job to fail

2021-04-20 23:24 UTC, teor2345 commented on zebra-network/src/peer/handshake.rs
> +            config.external_addr.unwrap_or(config.listen_addr),
Can you turn this into an `external_addr()` method on `Config`?
(And make `Config.external_addr` private or `pub(crate)`.)

That way, we'll always get the external address the right way.

(We'll also want to use the external address in #1892 and similar tickets.)

2021-04-20 23:33 UTC, teor2345 requested changes
I think we'll want to have separate IPv4 and IPv6 external addresses, and choose the external address based on the connection's IP version. (See #1890.)

We'll also want to add both external addresses (or the internal address) to Zebra's `Peers` responses, but that depends on #2035 merging:
https://github.com/ZcashFoundation/zebra/pull/2033/files#diff-3f14971a74a109913a4809bd1a77f4e0145e1edfa72aaded8f1fdcb2cc45f4f1R243-R244

As part of that change, we'll want to make the `AddressBook` ignore any null addresses  (`0.0.0.0` or `[::]`).

2021-04-20 23:37 UTC, teor2345 commented
> I think we'll want to have separate IPv4 and IPv6 external addresses, and choose the external address based on the connection's IP version. (See #1890.)

It might be simpler to allow a list of external addresses, and:
- choose a random one of the correct type for the `Version` response
- put them all in the `Peers` response

That way, we support multi-homed nodes.

2021-10-21 23:22 UTC, teor2345 commented
I'm going to mark this PR as draft until the Zebra team decides which changes we actually need here.

2021-12-28 01:18 UTC, teor2345 commented
We might merge this as part of ticket #3117 when we get to it.

2021-12-28 01:18 UTC, closed without merging