Block, BlockHeader and Block messages
ZcashFoundation/zebra pull request #21
Opened 2019-09-24 18:17 UTC by dconnolly

Resolves #7

2019-09-26 07:03 UTC, dconnolly commented on zebra-chain/src/block.rs
> +    solution: Vec<u8>,
This is not my favorite, so I might implement an `EquihashSolution` wrapper around `[u8; 1344]` with all the `Clone, Debug`, etc traits implemented.

2019-09-26 07:05 UTC, dconnolly commented on zebra-network/src/protocol/message.rs
> +        prev_block: BlockHeaderHash,
All these fields except the `txns` come out of `BlockHeader`, is there a better way to do this without straight-up serializing `BlockHeader` etc as the `Block` message?

2019-09-26 21:39 UTC, hdevalence commented on zebra-chain/src/block.rs
> +    // more explicit.
+1 to this terminology choice; I think it could be good to describe in the actual doc comment as well rather than just in the internal source comments.

2019-09-26 21:49 UTC, hdevalence commented on zebra-chain/src/block.rs
> +    solution: Vec<u8>,
+1; implementing a custom `Debug` has the upshot that it would allow us to do hex encoding of the bytes for the debug message (using `hex`).

2019-09-26 21:50 UTC, hdevalence commented on zebra-chain/src/block.rs
> +    pub fn hash(&self) -> [u8; 32] {
Since we have `impl From<BlockHeader> for BlockHeaderHash`, I think we don't need this function? We can just use `BlockHeaderHash::from(block_header)` or even `block_header.into()`.

2019-09-26 21:53 UTC, hdevalence commented on zebra-chain/src/block.rs
> +}
Should these impls (L29-L54) live with the `MerkleTree` definition in `merkle_tree.rs`?

2019-09-26 21:54 UTC, hdevalence commented on zebra-chain/src/merkle_tree.rs
> +    pub fn get_root(&self) -> Sha256 {
Is this a duplicate of `impl From<MerkleTree> for MerkleRootHash`?

2019-09-26 21:56 UTC, hdevalence commented on zebra-chain/src/note_commitment_tree.rs
> +// similar, it may be worth it to define a NoteCommitmentTree trait.
not a comment scoped to this PR, but branching point for further discussion in a separate issue: we may need a sprout note commitment tree, even if we checkpoint on sapling activation, in order to do sprout-on-groth16 proofs to move old sprout value.

2019-09-26 21:58 UTC, hdevalence commented on zebra-chain/src/transaction.rs
>      pub hash: [u8; 32],
Should this `[u8; 32]` have a newtype wrapper?

2019-09-26 22:03 UTC, hdevalence commented on zebra-network/src/protocol/message.rs
> +        prev_block: BlockHeaderHash,
Hmm, what if the `Block` variant of the `Message` enum just contains a `Block` object, and the message codec calls `Block::zcash_serialize`?

2019-09-26 22:04 UTC, hdevalence commented on zebra-chain/src/transaction.rs
> +/// fact a subset of unspent transaction outputs or 'UTXO's of the
```suggestion
/// fact a subset of unspent transaction outputs (or "UTXO"s) of the
```
nit

2019-09-26 22:05 UTC, hdevalence commented on zebra-chain/src/transaction.rs
> +// TODO: sanity check these doc comments
these seem good to me!

2019-09-26 22:07 UTC, hdevalence commented on zebra-chain/src/transaction.rs
>      pub hash: [u8; 32],
I guess this represents a transaction hash, so there should eventually be a transaction hash newtype (as with `BlockHeaderHash` etc), but since we don't already have a correct transaction object, it seems like we should circle back to remove this untyped hash when we do the transaction updates (rather than in this PR)?

2019-09-26 22:07 UTC, hdevalence commented on zebra-chain/src/transaction.rs
>      pub hash: [u8; 32],
(i.e., happy to mark as resolved)

2019-09-26 22:12 UTC, hdevalence commented on zebra-chain/src/block.rs
> +    solution: Vec<u8>,
I'm happy with merging the `Vec<u8>` version if you would rather circle back in a future PR?

2019-09-26 22:18 UTC, hdevalence commented
I think some of the `MerkleTree` impls should move into `merkle_tree.rs`, but other than that this LGTM!

2019-09-26 22:19 UTC, hdevalence requested changes
oops, forgot to put the preceding as a review status

2019-09-26 23:37 UTC, dconnolly commented on zebra-network/src/protocol/message.rs
> +        prev_block: BlockHeaderHash,
Love it. 💃

2019-09-26 23:38 UTC, dconnolly commented on zebra-chain/src/block.rs
> +}
Yeah I think you are correct.

2019-09-26 23:49 UTC, dconnolly commented on zebra-chain/src/block.rs
> +    pub fn hash(&self) -> [u8; 32] {
You're right, removing. I think this was a leftover artifact before we decided to do `BlockHeaderHash::from()` instead.

2019-09-27 03:06 UTC, dconnolly commented on zebra-chain/src/merkle_tree.rs
> +    pub fn get_root(&self) -> Sha256 {
I guess it is, hm.

2019-09-27 03:27 UTC, dconnolly commented on zebra-chain/src/transaction.rs
>      pub hash: [u8; 32],
#35 👍

2019-09-27 03:41 UTC, merged

2019-09-27 03:42 UTC, hdevalence commented on zebra-chain/Cargo.toml
> +#hex = "0.4" This conflicts with tracing-subscriber?
weird!

2019-09-27 03:46 UTC, hdevalence commented on zebra-network/src/protocol/codec.rs
> +                    .expect("Blocks must serialize.");
I think this one can error (unlike the hash-writer case, where we know the writer is infallible) if there's an error in the underlying writer, so maybe this bubble the error with `?`?

2019-09-27 03:47 UTC, dconnolly commented on zebra-chain/Cargo.toml
> +#hex = "0.4" This conflicts with tracing-subscriber?
muy weird