Add and use a function for mandatory checkpoint
ZcashFoundation/zebra pull request #2314
Opened 2021-06-15 19:11 UTC by oxarbitrage

## Motivation

We want to refactor the mandatory checkpoint code into a function. If merged this will close https://github.com/ZcashFoundation/zebra/issues/2305

## Solution

Add a function into `Network` implementation. Use it.

## Review

Anyone can review, is a minor cleanup change.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

2021-06-15 20:27 UTC, teor2345 requested changes
The mandatory checkpoint is also used in the non-finalised state and tests, see PRs #1898 and #2235:

https://github.com/ZcashFoundation/zebra/pull/2235/files#diff-a2e205e7f47ebdd654a97d9a69c10fed917af8f6f6174e8cce994d5506eeded3R84

https://github.com/ZcashFoundation/zebra/pull/1898/files#diff-1dd2c3997d949843524447be1a8bd5a91543678197b10926b091d9de8b95c570R257

https://github.com/ZcashFoundation/zebra/pull/1898/files#diff-b33295e5bb25fffe92ba36f21922285a10a387c43838477a2b1bcee48e9b3a4cR851

After you've done all your changes, do a search for "Canopy.activation_height" to make sure you haven't missed any.

2021-06-15 20:39 UTC, oxarbitrage commented
Apologies, the ticket was mentioning only https://github.com/ZcashFoundation/zebra/issues/1846 so i missed those changes. Will fix.

2021-06-15 22:36 UTC, teor2345 commented
When you do the fix, can you also fix the clippy warnings as well?

2021-06-15 23:32 UTC, oxarbitrage commented
> When you do the fix, can you also fix the clippy warnings as well?

Sure, i think i missed that because since some time there are a lot of clippy warnings in the networking code and other unrelated code. I know is unrelated here but do we have a ticket for that ?

2021-06-15 23:36 UTC, oxarbitrage commented
I also renamed a lot of acceptance tests (https://github.com/ZcashFoundation/zebra/pull/2314/commits/01a34385549976eac4f5d9f24b9185905ae18397) that were syncing up to canopy in favour of syncing up to the mandatory checkpoint. I hope I didn't go too far.

2021-06-15 23:41 UTC, teor2345 commented
> > When you do the fix, can you also fix the clippy warnings as well?
> 
> Sure, i think i missed that because since some time there are a lot of clippy warnings in the networking code and other unrelated code. I know is unrelated here but do we have a ticket for that ?

There aren't any clippy warnings in Zebra's CI on the current `main` branch. Our CI runs clippy on every feature in every Zebra crate, including test code. PRs can't merge until they pass clippy.

We run clippy on:
* Linux
* rustc 1.52.1

Is your Rust install up to date? Sometimes warnings get fixed or removed from clippy.
Are your PRs based off an old version of the `main` branch?

2021-06-15 23:41 UTC, teor2345 commented
> I also renamed a lot of acceptance tests ([01a3438](https://github.com/ZcashFoundation/zebra/commit/01a34385549976eac4f5d9f24b9185905ae18397)) that were syncing up to canopy in favour of syncing up to the mandatory checkpoint. I hope I didn't go too far.

This is great, feel free to update function names or docs, but they're not strictly required for this change.

2021-06-15 23:48 UTC, oxarbitrage commented
In regards to clippy, it must be something local (https://gist.github.com/oxarbitrage/8d741c1231335e97c50a06fc9b94ca65). Will research more.

2021-06-15 23:51 UTC, teor2345 commented
> In regards to clippy, it must be something local (https://gist.github.com/oxarbitrage/8d741c1231335e97c50a06fc9b94ca65). Will research more.

Your PR branch is up to date with our `main` branch.

What version of rustc are you using?

2021-06-15 23:55 UTC, oxarbitrage commented
> In regards to clippy, it must be something local (https://gist.github.com/oxarbitrage/8d741c1231335e97c50a06fc9b94ca65). Will research more.

Nevermind, i was in rust 1.51. Thanks.

2021-06-16 01:16 UTC, teor2345 requested changes
This looks good, we just need to update some feature names in the GitHub workflows as well.

2021-06-16 01:16 UTC, teor2345 commented on zebra-chain/src/parameters/network.rs
> +        // Currently this is Canopy for both networks.
Let's expand the docs a bit here, because it's the first place people will look when they see this method:
```suggestion
    /// Get the mandatory minimum checkpoint height for this network.
    ///
    /// Mandatory checkpoints are a Zebra-specific feature.
    /// If a Zcash consensus rule only applies before the mandatory checkpoint,
    /// Zebra can skip validation of that rule.
    pub fn mandatory_checkpoint_height(&self) -> Height {
        // Currently this is the Canopy activation height for both networks.
```

2021-06-16 01:16 UTC, teor2345 commented on zebrad/Cargo.toml
> +test_sync_past_mandatory_checkpoint_testnet = []
This change is ok, but it also needs an update to the GitHub workflows:
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/regenerate-stateful-test-disks.yml#L68
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/regenerate-stateful-test-disks.yml#L69
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/test.yml#L72

If you're using `fastmod`, it skips hidden files and directories like `.github` by default.
You can use `fastmod --hidden` to change them as well, but you'll need `fastmod` version 0.4.2.

2021-06-18 00:05 UTC, teor2345 approved these changes
Looks good, let's merge

2021-06-18 00:05 UTC, merged