Reject connections from outdated peers
ZcashFoundation/zebra pull request #2519
Opened 2021-07-23 01:29 UTC by jvff

## Motivation

### Specifications

### Designs

## Solution

## Review

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

2021-07-23 02:41 UTC, teor2345 requested changes
The core of this approach looks good.

But I think we could tweak it to reduce its impact on other code.

Minimising interface changes:
1. Define a minimal trait in `zebra-chain`, and implement it on the `BestTipHeight` struct in `zebra-state`
    - minimises changes in `zebra-chain`
    - unfortunately the extra `tokio` dependency causes CI issues, it's a bit of a long story
2. The trait only needs a method to get the state's best tip height
    - the caller doesn't care if the tip is finalized or not
3. Create the `BestTipHeight` when initializing the state
    - callers only have to change how they handle the return value

Minimising test changes:
4. Move `create_state_service` to `zebra_state::init_test`
    - test modules that use the state can switch to `init_test` instead
5. Update the non-finalized watch channel at the end of `validate_and_commit`
    - the `NonFinalizedState` doesn't need to change at all
6. Make the watch channel optional in `FinalizedState`
    - existing tests only need an extra `None` argument
7. Make `with_best_tip_height` optional in `zebra_network`
    - existing tests just work

When we do the mempool work, we might need to add extra trait methods, or change the watch channels. But let's keep it really simple for now.

2021-07-23 22:24 UTC, jvff commented
*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKCE1eEx-bH6Fq9lgy:-MfKCE1f4vofTjGVWmWv:bw1xrja) (no related file):*
> Define a minimal trait in `zebra-chain`, and implement it on the `BestTipHeight` struct in `zebra-state`

I like this idea. I also wonder if it would make sense to have some sort of `MinimumVersion` trait in `zebra-network`, with an `impl` for `T: BestTipHeight`. But this is probably something to consider in the future.

---


<!-- Sent from Reviewable.io -->

2021-07-23 22:24 UTC, jvff commented
*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKERzm6om4ywMYlR4Q:-MfKERzm6om4ywMYlR4R:b-q75qgv) (no related file):*
> Move `create_state_service` to `zebra_state::init_test`

This turned out more complicated than I expected. The `zebra_state` doesn't have a `proptest-impl` feature defined, so it's not easy to export that function to `zebra-consensus`.

I added the feature, and that resulted in compilation issues because parts of the code are `#[cfg(test)]` and parts are `#[cfg(any(test, feature = "proptest-impl"))]`. (I wonder if there's a clippy lint for using undefined Cargo features :thinking: )

To try to make it compile, I had to reorganize part of the test code, and still add some `#[cfg(test)]` to private functions inside an `arbitrary` module to remove unused warnings.

Maybe this is something I should in a separate PR that should be merged before this one?

---


<!-- Sent from Reviewable.io -->

2021-07-23 22:24 UTC, jvff commented
*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKLV4cANPKP35YoUfY:-MfKLV4cANPKP35YoUfZ:b-xf0yz6) (no related file):*
> Update the non-finalized watch channel at the end of `validate_and_commit`

You mean `StateService::validate_and_commit`? Won't this lead to updating the `watch` channel with the not-necessarily best chain tip?

Or should I always do `best_tip.send(self.mem.best_tip().0)`?

---


<!-- Sent from Reviewable.io -->

2021-07-23 22:38 UTC, jvff commented
*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-MfKQVQM-3m_v6MPse-0:by6hsb4) (no related file):*
After thinking about this some more, I was wondering if it would make sense to change the approach, and have a `BestTipHeight` type that's the _sender_ endpoint, instead of the _receiver_ endpoint as it is now. That means that it would be an internal type, and the receiver endpoint would just be a `watch::Receiver<block::Height>`. The `BestTipHeight` would have a `set_finalized_height` and `set_non_finalized_height`, and just make sure to update the `watch::Sender<block::Height>` when appropriate.

There would only be one `BestTipHeight` instance, inside `StateService`. The `set_finalized_height` would be called inside the `queue_and_commit_non_finalized` method and the `set_non_finalized_height` would be called in the `validate_and_commit` method (using `self.mem.best_tip().0`).

What do you think of this approach?

I'm also kind of tempted to some sort of `zebra_network::HandshakeValidator` trait and a `zebra_network::MinimumVersionChecker` type that wraps the `watch::Sender<block::Height>` and implements the trait. That might help with testing, because we could use a default `Accept` type of `HandshakeValidator`. But this might be too much for now?

---


<!-- Sent from Reviewable.io -->

2021-07-27 00:17 UTC, teor2345 reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-Mf_FLjFD02KS0efBTbj:b-v2ay87) (no related file):*
> After thinking about this some more, I was wondering if it would make sense to change the approach, and have a `BestTipHeight` type that's the _sender_ endpoint, instead of the _receiver_ endpoint as it is now. That means that it would be an internal type, and the receiver endpoint would just be a `watch::Receiver<block::Height>`. The `BestTipHeight` would have a `set_finalized_height` and `set_non_finalized_height`, and just make sure to update the `watch::Sender<block::Height>` when appropriate.

I like this approach.

On Friday, I couldn't work out how to fit it into the existing state data structures and methods. But I think I can see how it could work now.

> There would only be one `BestTipHeight` instance, inside `StateService`. The `set_finalized_height` would be called inside the `queue_and_commit_non_finalized` method

Do you mean `FinalizedState::queue_and_commit_finalized`?

We know the latest finalized tip height once this loop finishes:
https://github.com/ZcashFoundation/zebra/blob/544be14c7034e24bdef75a7ebafba16a14b4abd9/zebra-state/src/service/finalized_state.rs#L136-L140

We'd need to pass a `&mut BestTipHeight` to `FinalizedState::queue_and_commit_finalized`, but that seems like it would work.

> and the `set_non_finalized_height` would be called in the `validate_and_commit` method (using `self.mem.best_tip().0`).

That would work, but we might want to wait until all the ready queued blocks have been processed, for consistency and performance.

We know the latest non-finalized tip height after this line in `StateService::queue_and_commit_non_finalized`:
https://github.com/ZcashFoundation/zebra/blob/bfc3e4a46cd8033869216951833750ddceccc285/zebra-state/src/service.rs#L152

> What do you think of this approach?

I think it keeps most of the changes contained in the state. And it reduces the number of channels.

Let's try it and see how it goes?

> I'm also kind of tempted to some sort of `zebra_network::HandshakeValidator` trait and a `zebra_network::MinimumVersionChecker` type that wraps the `watch::Sender<block::Height>` and implements the trait. That might help with testing, because we could use a default `Accept` type of `HandshakeValidator`. But this might be too much for now?

I think this is a good idea for a future ticket.

For now, we could just use `Option<watch::Sender<block::Height>>`, and use the default version if it is `None`.

---


<!-- Sent from Reviewable.io -->

2021-07-27 00:19 UTC, teor2345 reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKLV4cANPKP35YoUfY:-Mf_K9JQ1F1blwy3t0sj:b-dwj8m) (no related file):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

> Update the non-finalized watch channel at the end of `validate_and_commit`

You mean `StateService::validate_and_commit`? Won't this lead to updating the `watch` channel with the not-necessarily best chain tip?

Or should I always do `best_tip.send(self.mem.best_tip().0)`?
</blockquote></details>

Good catch on this one - yes, we need to use the best tip height, not the latest or highest height.

---


<!-- Sent from Reviewable.io -->

2021-07-29 00:56 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 0 of 25 files reviewed, 1 unresolved discussion (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-Mfjk_xK3jy1uAM_FdKS:bo8jo9f) (no related file):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

> After thinking about this some more, I was wondering if it would make sense to change the approach, and have a `BestTipHeight` type that's the _sender_ endpoint, instead of the _receiver_ endpoint as it is now. That means that it would be an internal type, and the receiver endpoint would just be a `watch::Receiver<block::Height>`. The `BestTipHeight` would have a `set_finalized_height` and `set_non_finalized_height`, and just make sure to update the `watch::Sender<block::Height>` when appropriate.

I like this approach.

On Friday, I couldn't work out how to fit it into the existing state data structures and methods. But I think I can see how it could work now.

> There would only be one `BestTipHeight` instance, inside `StateService`. The `set_finalized_height` would be called inside the `queue_and_commit_non_finalized` method

Do you mean `FinalizedState::queue_and_commit_finalized`?

We know the latest finalized tip height once this loop finishes:
https://github.com/ZcashFoundation/zebra/blob/544be14c7034e24bdef75a7ebafba16a14b4abd9/zebra-state/src/service/finalized_state.rs#L136-L140

We'd need to pass a `&mut BestTipHeight` to `FinalizedState::queue_and_commit_finalized`, but that seems like it would work.

> and the `set_non_finalized_height` would be called in the `validate_and_commit` method (using `self.mem.best_tip().0`).

That would work, but we might want to wait until all the ready queued blocks have been processed, for consistency and performance.

We know the latest non-finalized tip height after this line in `StateService::queue_and_commit_non_finalized`:
https://github.com/ZcashFoundation/zebra/blob/bfc3e4a46cd8033869216951833750ddceccc285/zebra-state/src/service.rs#L152

> What do you think of this approach?

I think it keeps most of the changes contained in the state. And it reduces the number of channels.

Let's try it and see how it goes?

> I'm also kind of tempted to some sort of `zebra_network::HandshakeValidator` trait and a `zebra_network::MinimumVersionChecker` type that wraps the `watch::Sender<block::Height>` and implements the trait. That might help with testing, because we could use a default `Accept` type of `HandshakeValidator`. But this might be too much for now?

I think this is a good idea for a future ticket.

For now, we could just use `Option<watch::Sender<block::Height>>`, and use the default version if it is `None`.
</blockquote></details>

I updated the PR with this approach. It's still missing tests, so I'll keep it as draft for now. Let me know what you think :+1: 

---


<!-- Sent from Reviewable.io -->

2021-07-29 02:07 UTC, teor2345 reviewed
> Reviewed 2 of 23 files at r1, 18 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 20 of 25 files reviewed, 8 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-Mfk-gEjEKktLRilnTsB:b-jy53mi) (no related file):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I updated the PR with this approach. It's still missing tests, so I'll keep it as draft for now. Let me know what you think :+1: 
</blockquote></details>

I think we're missing a few places where the finalized tip needs updating.
I'd like to focus on those in the next revision, so we know if this design will work.

I also noted some places where we could make the design more accurate, or reduce the size of this PR.
But they are only worth doing if we can get the finalized tip height to work.

---
___
*[zebra-network/src/isolated.rs, line 61 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfjsPoF0Jio53abmBOq:-MfjsPoF0Jio53abmBOr:bpk21bk) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-network/src/isolated.rs#L61)):*
> ```XML
>         }))
>         .with_user_agent(user_agent)
>         .with_best_tip_height(best_tip_height)
> ```

Can we make `with_best_tip_height` optional, so we don't have to change this module at all?

(This also makes the changes to the network tests smaller.)
___
*[zebra-state/src/service.rs, line 75 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfjzgEi6hnZyVgIL1L1:-MfjzgEi6hnZyVgIL1L2:b-vqqplc) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service.rs#L75)):*
> ```XML
>     pub fn new(config: Config, network: Network) -> (Self, watch::Receiver<block::Height>) {
>         let (best_tip_height, best_tip_height_receiver) = BestTipHeight::new();
>         let disk = FinalizedState::new(&config, network);
> ```

What happens if the finalized state already has blocks in it?
___
*[zebra-state/src/service.rs, line 176 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfjw1ip-QAtvhzxhf1n:-Mfjw1ip-QAtvhzxhf1o:bc1xz4e) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service.rs#L176)):*
> ```XML
>         self.queued_blocks.prune_by_height(finalized_tip_height);
>         self.best_tip_height
>             .set_finalized_height(finalized_tip_height);
> ```

What about checkpointed blocks?

They get committed in `FinalizedState::queue_and_commit_finalized`, rather than this method.
___
*[zebra-state/src/service.rs, line 195 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfju7EN2_hEZV8PL825:-Mfju7EO8AwpMmB0a3fh:b-xv3phf) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service.rs#L195)):*
> ```XML
> 
>         self.best_tip_height
>             .set_best_non_finalized_height(self.mem.best_tip().map(|(height, _hash)| height));
> ```

For consistency, can we set both heights in the same place in `queue_and_commit_non_finalized`?

If we set both heights in the same place, future changes should account for them both.
___
*[zebra-state/src/service/best_tip_height.rs, line 5 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfjwJWFExPM5TDGrVEJ:-MfjwJWFExPM5TDGrVEK:b-24khtx) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service/best_tip_height.rs#L5)):*
Documentation typo - could be confusing.

> ```
> /// A helper type to determine the best chain tip block height.
> ```
___
*[zebra-state/src/service/best_tip_height.rs, line 14 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfjwW5yEXn6eb14CHRq:-MfjwW5yEXn6eb14CHRr:b-8fx2u7) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service/best_tip_height.rs#L14)):*
> ```XML
>     non_finalized: Option<block::Height>,
>     sender: watch::Sender<block::Height>,
>     // TODO: Replace this with a `watch::Sender::borrow` call once Tokio is updated to 1.0.0
> ```

:+1: 
___
*[zebra-state/src/service/best_tip_height.rs, line 30 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfk-QTE1uCbsqNgfZf8:-Mfk-QTF9tA2uiGAfMyT:b-8qpzgf) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service/best_tip_height.rs#L30)):*
> ```XML
>                 non_finalized: None,
>                 sender,
>                 active_value: genesis_height,
> ```

When Zebra starts with an empty state, the finalized tip height is actually `None`, because we haven't downloaded the genesis block yet.

Can we use `Option<block::Height>` and initialize it to `None`?
(This comment applies to the channel and the BestTipHeight's fields.)
___
*[zebra-state/tests/basic.rs, line 84 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfjs5PyBjAiLInkheCc:-Mfjs5PzCRnFmRRJDCa7:behj7we) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/tests/basic.rs#L84)):*
Optional: Is this code is equivalent to `zebra_state::init_test`?

It uses a temporary directory which auto-deletes, the same as the ephemeral config.
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         let storage_guard = TempDir::new("")?;
>         let cache_dir = storage_guard.path().to_owned();
>         let (service, _) = zebra_state::init(
>             Config {
>                 cache_dir,
> ```
</details>



<!-- Sent from Reviewable.io -->

2021-07-30 01:22 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 9 of 25 files reviewed, 7 unresolved discussions (waiting on @jvff and @teor2345)

___
*[zebra-state/src/service.rs, line 75 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfjzgEi6hnZyVgIL1L1:-Mfo3xZH94tICpmh3kL0:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service.rs#L75)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

What happens if the finalized state already has blocks in it?
</blockquote></details>

Done.
___
*[zebra-state/src/service.rs, line 176 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfjw1ip-QAtvhzxhf1n:-MfoERwE4pB7ou93Rr07:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service.rs#L176)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

What about checkpointed blocks?

They get committed in `FinalizedState::queue_and_commit_finalized`, rather than this method.
</blockquote></details>

Done.
___
*[zebra-state/src/service.rs, line 195 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfju7EN2_hEZV8PL825:-Mfopp083xs46R8j3a7F:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service.rs#L195)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

For consistency, can we set both heights in the same place in `queue_and_commit_non_finalized`?

If we set both heights in the same place, future changes should account for them both.


</blockquote></details>

Done.
___
*[zebra-state/src/service/best_tip_height.rs, line 5 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfjwJWFExPM5TDGrVEJ:-MfoEg-5E0j8z9t-NuJL:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service/best_tip_height.rs#L5)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Documentation typo - could be confusing.

> ```
> /// A helper type to determine the best chain tip block height.
> ```

</blockquote></details>

Done.
___
*[zebra-state/src/service/best_tip_height.rs, line 30 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfk-QTE1uCbsqNgfZf8:-MfoEjGz2y8LATYMG23u:b1zrcg9) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service/best_tip_height.rs#L30)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

When Zebra starts with an empty state, the finalized tip height is actually `None`, because we haven't downloaded the genesis block yet.

Can we use `Option<block::Height>` and initialize it to `None`?
(This comment applies to the channel and the BestTipHeight's fields.)
</blockquote></details>

Done, but I kept the setter method to receive just a `block::Height` instead of `Option<block::Height>`. My reasoning is that the finalized height should only be `None` while the finalized state is empty, and that it should never be cleared (i.e., set to `None`). But I can change that if this is incorrect or unnecessarily cautious.
___
*[zebra-state/tests/basic.rs, line 84 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfjs5PyBjAiLInkheCc:-MfoTh4H5z1p7boLZe6v:b-gqj4tx) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/tests/basic.rs#L84)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Optional: Is this code is equivalent to `zebra_state::init_test`?

It uses a temporary directory which auto-deletes, the same as the ephemeral config.

> ```
>         let storage_guard = TempDir::new("")?;
>         let cache_dir = storage_guard.path().to_owned();
>         let (service, _) = zebra_state::init(
>             Config {
>                 cache_dir,
> ```

</blockquote></details>

Done. Yep, it's exactly the same! However, I did notice that the `TempDir` guard in the ephemeral `Config` is dropped really soon. Doesn't that mean that the directory is deleted before it's used? :thinking: 
___
*[zebra-network/src/isolated.rs, line 61 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfjsPoF0Jio53abmBOq:-MfoQyNh1JoWxXHHaaTF:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-network/src/isolated.rs#L61)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Can we make `with_best_tip_height` optional, so we don't have to change this module at all?

(This also makes the changes to the network tests smaller.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-30 01:24 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 9 of 25 files reviewed, 7 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-Mfp-QO62qD479WqnAyR:b-3wns6c) (no related file):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

I think we're missing a few places where the finalized tip needs updating.
I'd like to focus on those in the next revision, so we know if this design will work.

I also noted some places where we could make the design more accurate, or reduce the size of this PR.
But they are only worth doing if we can get the finalized tip height to work.
</blockquote></details>

Updated :+1: 

---


<!-- Sent from Reviewable.io -->

2021-07-30 05:11 UTC, teor2345 reviewed
> Reviewed 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: all files reviewed, 9 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-MfpalMf7HSeT5FAriB0:b-d8bt86) (no related file):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Updated :+1: 
</blockquote></details>

This design and code looks good.

Required changes:
* we're using the heights of valid and invalid finalized blocks, but we only want valid block heights
* add one or two tests

I'd like to merge on my Monday, so you can move on to other work on your Monday.

We will add a lot more tests as part of the mempool work, so we just need basic coverage for now.

I also made a bunch of very minor API style suggestions. If you have time, feel free to fix them, otherwise feel free to ignore them, or open a follow-up ticket. Some of the changes might make testing easier.

---
___
*[zebra-network/src/peer/handshake.rs, line 428 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfpf-XY-MZQZs5Qwguh:-Mfpf-XY-MZQZs5Qwgui:bwe1skn) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-network/src/peer/handshake.rs#L428)):*
Optional: Can we just pass `self.best_tip_height` to `Handshake`, instead of creating a fake channel?

If we update the channel type as part of the mempool work, we'll also have to make changes to the fake channel's type.
That's ok, and we could merge this code as-is.

But I'd like to avoid the extra work - unless `Option<watch::Receiver<Option<Height>>` is much harder to use.

> ```
> self.best_tip_height,
> ```
___
*[zebra-network/src/peer/handshake.rs, line 585 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpcshY0d-0Jx70f3F3:-MfpcshY0d-0Jx70f3F4:b-3c0qlv) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-network/src/peer/handshake.rs#L585)):*
> ```XML
>     // network upgrades and could lead to chain forks or slower block propagation.
>     let height = best_tip_height.borrow().unwrap_or(block::Height(0));
>     let min_version = Version::min_remote_for_height(config.network, height);
> ```

Optional: Can we handle `Option<Height>` in `min_remote_for_height` instead?

We could merge this code as-is - it works fine, and returns the correct minimum version for `None`.

But we're also going to need to handle `None` heights when we disconnect from existing peers, so I'd prefer to do that all in the same place. And I'd like to avoid the habit of substituting `Height(0)` for `None`, it will get us into trouble eventually!

There's no need to push `Option<Height>` any further up the call stack, because the correct version for an empty state is just Zebra's minimum network protocol version: `Version::initial_min_for_network`.

```
let min_version = Version::min_remote_for_height(config.network,  best_tip_height.borrow());
```
___
*[zebra-network/src/peer_set/initialize/tests/vectors.rs, line 115 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpeZldCAVMOHg-nCqz:-MfpeZldCAVMOHg-nCr-:b8n96wb) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-network/src/peer_set/initialize/tests/vectors.rs#L115)):*
Optional: Can we just skip creating the channel here? It's now optional.

I'd like to avoid creating an unused channel for every zebra-network test we write.

Again, this is just a cleanup, and we could merge the code if you want.

> ```
>  let (_peer_service, address_book) = init(config, inbound_service, None).await;
> ```
___
*[zebra-state/src/service.rs, line 679 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpflCu4fdp3UpqAZ89:-MfpflCu4fdp3UpqAZ8A:bz6kvfy) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-state/src/service.rs#L679)):*
> ```XML
>                 self.pending_utxos.check_against(&finalized.new_outputs);
>                 self.disk.queue_and_commit_finalized((finalized, rsp_tx));
>                 self.best_tip_height.set_finalized_height(finalized_height);
> ```

Blocker: This code updates the finalized tip height for valid and invalid blocks.

Before and after NU5, block commits can fail due to database errors.

After NU5, malicious peers can modify the authorizing data in v5 transactions without changing the transaction ID. So we need to check the block commitment in the finalized state, and return an error if the check fails. For more details, see the last paragraph of:
https://github.com/ZcashFoundation/zebra/issues/2134#issuecomment-888709631

Can we use the finalized state's tip height here, rather than the block height?
___
*[zebra-state/src/service/best_tip_height.rs, line 30 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfk-QTE1uCbsqNgfZf8:-Mfpk_zB23m0kbNX8y97:bysxu8p) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/src/service/best_tip_height.rs#L30)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done, but I kept the setter method to receive just a `block::Height` instead of `Option<block::Height>`. My reasoning is that the finalized height should only be `None` while the finalized state is empty, and that it should never be cleared (i.e., set to `None`). But I can change that if this is incorrect or unnecessarily cautious.
</blockquote></details>

I think the required fix to the finalized tip update might impact the types here.

But you're correct, both the finalized and non-finalized state are `None` when empty. Then after they are populated, they are never reset to `None`.
So it would be ok to take a `Height` and ignore `None` in the caller, or take `Option<Height>` and ignore it in these methods.

I have a slight preference for consistent method arguments, and for ignoring `None` inside the methods. That way, the "ignore None" code is all in the same module.

But I really don't mind either way, as long as the code is correct.
___
*[zebra-state/src/service/best_tip_height.rs, line 60 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpmglO4yx4W8GGGOih:-MfpmglO4yx4W8GGGOii:b-toq7yq) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-state/src/service/best_tip_height.rs#L60)):*
> ```XML
>     /// height that was sent.
>     fn update(&mut self) {
>         let new_value = self.non_finalized.max(self.finalized);
> ```

Required Test: `Option::max` is tricky to get right, so let's make sure that we get `Some` if one of the heights is `None`.

I'm pretty sure that `max(None, Some)` is `Some`, but `min(None, Some)` is `None`, because `Option` is defined as `{ None, Some(T) }`.

For details, see: https://doc.rust-lang.org/std/cmp/trait.Ord.html#derivable
___
*[zebra-state/tests/basic.rs, line 84 at r2](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfjs5PyBjAiLInkheCc:-Mfpik37BnN9DemA9DKE:b-y0chrp) ([raw file](https://github.com/zcashfoundation/zebra/blob/ee4e2fcd9dc7646677fcd5e361dabf76da40b396/zebra-state/tests/basic.rs#L84)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done. Yep, it's exactly the same! However, I did notice that the `TempDir` guard in the ephemeral `Config` is dropped really soon. Doesn't that mean that the directory is deleted before it's used? :thinking: 
</blockquote></details>

We just use `TempDir` to generate the path - the directory is deleted immediately. Then RocksDB creates the directory, and the finalized state manually deletes it on drop.

It's a bit messy, but we were trying to do low-risk changes at the time. Also I think I understand lifetimes much better now.


 [...]

2021-07-30 22:49 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 17 of 29 files reviewed, 7 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-MftaJn3Bz0SXkM-unPr:b-ozmden) (no related file):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

This design and code looks good.

Required changes:
* we're using the heights of valid and invalid finalized blocks, but we only want valid block heights
* add one or two tests

I'd like to merge on my Monday, so you can move on to other work on your Monday.

We will add a lot more tests as part of the mempool work, so we just need basic coverage for now.

I also made a bunch of very minor API style suggestions. If you have time, feel free to fix them, otherwise feel free to ignore them, or open a follow-up ticket. Some of the changes might make testing easier.
</blockquote></details>

I updated the PR to apply the suggestions and to start writing the tests. Unfortunately, I haven't finished them yet :( But I pushed the current status and I added a comment on the test that's incomplete with what I'm trying to solve.

Let me know what you think of the tests. I thought that it might make sense to add a similar test that finalizes and commits blocks in an unordered way, but I'm not sure if that's too much and how much work it would take :thinking: 

---
___
*[zebra-network/src/peer/handshake.rs, line 428 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mfpf-XY-MZQZs5Qwguh:-MfqffLV8dXawnU1aXoV:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-network/src/peer/handshake.rs#L428)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Optional: Can we just pass `self.best_tip_height` to `Handshake`, instead of creating a fake channel?

If we update the channel type as part of the mempool work, we'll also have to make changes to the fake channel's type.
That's ok, and we could merge this code as-is.

But I'd like to avoid the extra work - unless `Option<watch::Receiver<Option<Height>>` is much harder to use.

> ```
> self.best_tip_height,
> ```

</blockquote></details>

Done.
___
*[zebra-network/src/peer/handshake.rs, line 585 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpcshY0d-0Jx70f3F3:-MfqakBbELTxo9qjRDCw:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-network/src/peer/handshake.rs#L585)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Optional: Can we handle `Option<Height>` in `min_remote_for_height` instead?

We could merge this code as-is - it works fine, and returns the correct minimum version for `None`.

But we're also going to need to handle `None` heights when we disconnect from existing peers, so I'd prefer to do that all in the same place. And I'd like to avoid the habit of substituting `Height(0)` for `None`, it will get us into trouble eventually!

There's no need to push `Option<Height>` any further up the call stack, because the correct version for an empty state is just Zebra's minimum network protocol version: `Version::initial_min_for_network`.

```
let min_version = Version::min_remote_for_height(config.network,  best_tip_height.borrow());
```
</blockquote></details>

Done.
___
*[zebra-network/src/peer_set/initialize/tests/vectors.rs, line 115 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpeZldCAVMOHg-nCqz:-Mfqev_A2HCPg77wHghI:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-network/src/peer_set/initialize/tests/vectors.rs#L115)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Optional: Can we just skip creating the channel here? It's now optional.

I'd like to avoid creating an unused channel for every zebra-network test we write.

Again, this is just a cleanup, and we could merge the code if you want.

> ```
>  let (_peer_service, address_book) = init(config, inbound_service, None).await;
> ```

</blockquote></details>

Done.
___
*[zebra-state/src/service.rs, line 679 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpflCu4fdp3UpqAZ89:-Mfqign6DOPdvbFrzdmJ:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-state/src/service.rs#L679)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Blocker: This code updates the finalized tip height for valid and invalid blocks.

Before and after NU5, block commits can fail due to database errors.

After NU5, malicious peers can modify the authorizing data in v5 transactions without changing the transaction ID. So we need to check the block commitment in the finalized state, and return an error if the check fails. For more details, see the last paragraph of:
https://github.com/ZcashFoundation/zebra/issues/2134#issuecomment-888709631

Can we use the finalized state's tip height here, rather than the block height?

</blockquote></details>

Done.
___
*[zebra-state/src/service/best_tip_height.rs, line 60 at r3](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfpmglO4yx4W8GGGOih:-MftZmR4B-g6Z83fT6k2:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/799e4d45980423738610861ada45a09cc43f76ad/zebra-state/src/service/best_tip_height.rs#L60)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Required Test: `Option::max` is tricky to get right, so let's make sure that we get `Some` if one of the heights is `None`.

I'm pretty sure that `max(None, Some)` is `Some`, but `min(None, Some)` is `None`, because `Option` is defined as `{ None, Some(T) }`.

For details, see: https://doc.rust-lang.org/std/cmp/trait.Ord.html#derivable
</blockquote></details>

Done.
___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-Mft_I21B5zHzMeoHgu_:b-l7q0ka) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
> ```XML
>             );
> 
>             todo!("Commit each finalized block");
> ```

FYI: Still haven't finished this test. It still needs to:

1. Commit finalized blocks (I guess I just need to send a `Request::CommitFinalizedBlock`?)
2. Commit non-finalized blocks (`Request::CommitBlock`?)
3. Finalize blocks (is there a way to force this, or do I have to send the block again with `Request::CommitFinalizedBlock`?)
4. Get it running in an `async` environment. I tried to get the whole test working as an `async fn` and `#[tokio::test]`, but I couldn't get it to work. I'll have to investigate more later.


<!-- Sent from Reviewable.io -->

2021-08-02 06:37 UTC, teor2345 reviewed
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: all files reviewed, 3 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-Mg4QwVjAi75Ava1iNRT:bn9hc8j) (no related file):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I updated the PR to apply the suggestions and to start writing the tests. Unfortunately, I haven't finished them yet :( But I pushed the current status and I added a comment on the test that's incomplete with what I'm trying to solve.

Let me know what you think of the tests. I thought that it might make sense to add a similar test that finalizes and commits blocks in an unordered way, but I'm not sure if that's too much and how much work it would take :thinking: 
</blockquote></details>

I think the goals of the state chain test are a bit too big for the time we have available.
Can you focus that test on the new best tip interface?

We already have tests for unordered commits, and for the best tip of multiple chains, so there's no need to re-test that code.

We've made the zebra-network changes really small, so I don't think we need to test them right now.
Can you open a ticket for a proptest for the minimum peer version at various heights?

---
___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-Mg4V9ec5FGJvUu5McTt:bpducx) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
I'd suggest using the `StateService` and its methods directly, like the existing tests.

> Commit finalized blocks (I guess I just need to send a Request::CommitFinalizedBlock?)

https://github.com/ZcashFoundation/zebra/blob/f9c06205766547011fd3181b88aacef2400e0c80/zebra-state/src/service/finalized_state/tests/prop.rs#L29

> Commit non-finalized blocks (Request::CommitBlock?)

https://github.com/ZcashFoundation/zebra/blob/f9c06205766547011fd3181b88aacef2400e0c80/zebra-state/src/service/non_finalized_state/tests/prop.rs#L164-L172

> Finalize blocks (is there a way to force this, or do I have to send the block again with Request::CommitFinalizedBlock?)

If you use `PreparedChain`, then every chain is longer than `MIN_TRANSPARENT_COINBASE_MATURITY`.
So some blocks will automatically be finalized when `count` is large enough.

> Get it running in an async environment. I tried to get the whole test working as an async fn and #[tokio::test], but I couldn't get it to work. I'll have to investigate more later.

Can we avoid this complexity in this test, by using the `StateService` and its methods directly?
We already have tests for the state's async methods.

If your tests trigger the minimum non-finalized height assertion, feel free to move that assertion into the `Request::CommitBlock` handler. (Or some intermediate method.)
___
*[zebra-state/src/service/tests.rs, line 358 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mg4TTL13JN85s8CRsq5:-Mg4TTL13JN85s8CRsq6:bb0zk97) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L358)):*
> ```XML
> }
> 
> fn ordered_blockchain_state_strategy() -> impl Strategy<
> ```

I'm not sure if the `ordered_blockchain_state_strategy` is going to pass state contextual validation. Even if it does right now, it probably won't continue to pass as we add new features.

Can you use a single `PreparedChain` instead, with no forks?
It's used by existing tests, so it will keep on working when we make changes.

You can use the random `count` argument to choose the number of blocks to use from the chain:
https://github.com/ZcashFoundation/zebra/blob/f9c06205766547011fd3181b88aacef2400e0c80/zebra-state/src/service/non_finalized_state/tests/prop.rs#L160

Generating a blockchain with arbitrary forks is a good idea, but it belongs in another ticket, when we have more time.


<!-- Sent from Reviewable.io -->

2021-08-02 22:09 UTC, jvff commented
___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-Mg7uOVY6oCvr9_Jqz1B:b-11f7z6) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

I'd suggest using the `StateService` and its methods directly, like the existing tests.

> Commit finalized blocks (I guess I just need to send a Request::CommitFinalizedBlock?)

https://github.com/ZcashFoundation/zebra/blob/f9c06205766547011fd3181b88aacef2400e0c80/zebra-state/src/service/finalized_state/tests/prop.rs#L29

> Commit non-finalized blocks (Request::CommitBlock?)

https://github.com/ZcashFoundation/zebra/blob/f9c06205766547011fd3181b88aacef2400e0c80/zebra-state/src/service/non_finalized_state/tests/prop.rs#L164-L172

> Finalize blocks (is there a way to force this, or do I have to send the block again with Request::CommitFinalizedBlock?)

If you use `PreparedChain`, then every chain is longer than `MIN_TRANSPARENT_COINBASE_MATURITY`.
So some blocks will automatically be finalized when `count` is large enough.

> Get it running in an async environment. I tried to get the whole test working as an async fn and #[tokio::test], but I couldn't get it to work. I'll have to investigate more later.

Can we avoid this complexity in this test, by using the `StateService` and its methods directly?
We already have tests for the state's async methods.

If your tests trigger the minimum non-finalized height assertion, feel free to move that assertion into the `Request::CommitBlock` handler. (Or some intermediate method.)

</blockquote></details>

I'm having some trouble with this test. I'm running into a failed assertion: `contextual validation requires at least 28 (POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN) blocks` :(


<!-- Sent from Reviewable.io -->

2021-08-02 23:10 UTC, teor2345 reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: all files reviewed, 3 unresolved discussions (waiting on @jvff and @teor2345)

___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-Mg86ucR5W61-ZOQl13j:b-gxidnp) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm having some trouble with this test. I'm running into a failed assertion: `contextual validation requires at least 28 (POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN) blocks` :(
</blockquote></details>

Can you move that assertion and the minimum non-finalized height assertion to the `Request::CommitBlock` handler?
https://github.com/ZcashFoundation/zebra/blob/4f96a4bb403ac23351446230fcdb2016954ee884/zebra-state/src/service.rs#L638

It's not a perfect solution. But it keeps checking those assertions for `StateService as tower::Service` callers, which is what we need in production.


<!-- Sent from Reviewable.io -->

2021-08-03 01:29 UTC, teor2345 reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: all files reviewed, 2 unresolved discussions (waiting on @teor2345)

___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-Mg8bqcOB_46P6oHbq9O:b964c5k) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Can you move that assertion and the minimum non-finalized height assertion to the `Request::CommitBlock` handler?
https://github.com/ZcashFoundation/zebra/blob/4f96a4bb403ac23351446230fcdb2016954ee884/zebra-state/src/service.rs#L638

It's not a perfect solution. But it keeps checking those assertions for `StateService as tower::Service` callers, which is what we need in production.
</blockquote></details>

We're almost there, it looks like you missed moving the assertion that's actually failing:
https://github.com/ZcashFoundation/zebra/blob/7218aec19f724c5b76b609b8546b0fd28916c661/zebra-state/src/service.rs#L213-L220


<!-- Sent from Reviewable.io -->

2021-08-03 01:37 UTC, teor2345 reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: all files reviewed, 4 unresolved discussions (waiting on @jvff and @teor2345)

___
*[zebra-state/src/service/tests.rs, line 282 at r5](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mg8dHle6P1ytUwLwdtZ:-Mg8dHlfC8c7no3HYHKV:b-qhr6zo) ([raw file](https://github.com/zcashfoundation/zebra/blob/d17ee46c219ca500b25a76f6e3b23163c33d79e6/zebra-state/src/service/tests.rs#L282)):*
Just noting that this comment will need updating after the test is finished.

> ```
> /// Test that the best tip height is updated accordingly.
> ```
___
*[zebra-state/src/service/tests.rs, line 294 at r5](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mg8dx6rEWXCDhRSDQfu:-Mg8dx6s2jbTBHIF_w0N:b-hj4kag) ([raw file](https://github.com/zcashfoundation/zebra/blob/d17ee46c219ca500b25a76f6e3b23163c33d79e6/zebra-state/src/service/tests.rs#L294)):*
The genesis block needs to be committed to the finalized state, so you'll have to do something like this before splitting the chain:

> ```
>         let count = max(count, 1);
> ```


<!-- Sent from Reviewable.io -->

2021-08-04 01:49 UTC, teor2345 reviewed
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 29 of 31 files reviewed, 4 unresolved discussions (waiting on @jvff and @teor2345)

___
*[zebra-state/src/service/tests.rs, line 315 at r5](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgDq6ME2L00ejpoorgz:-MgDq6ME2L00ejpoorh-:b-jeduop) ([raw file](https://github.com/zcashfoundation/zebra/blob/d17ee46c219ca500b25a76f6e3b23163c33d79e6/zebra-state/src/service/tests.rs#L315)):*
This line and the similar line below the non-finalized loop seem redundant, because the check happens at the end of each loop, after `expected_height` is modified:
> ```
> prop_assert_eq!(*best_tip_height.borrow(), expected_height);
> ```


<!-- Sent from Reviewable.io -->

2021-08-05 01:34 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 28 of 31 files reviewed, 5 unresolved discussions (waiting on @jvff and @teor2345)

___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-MgItwZj5cMRwphLYO49:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

We're almost there, it looks like you missed moving the assertion that's actually failing:
https://github.com/ZcashFoundation/zebra/blob/7218aec19f724c5b76b609b8546b0fd28916c661/zebra-state/src/service.rs#L213-L220
</blockquote></details>

Done.
___
*[zebra-state/src/service/tests.rs, line 358 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mg4TTL13JN85s8CRsq5:-MgItSBO2ba3DFP3IBKY:b-5kptj9) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L358)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

I'm not sure if the `ordered_blockchain_state_strategy` is going to pass state contextual validation. Even if it does right now, it probably won't continue to pass as we add new features.

Can you use a single `PreparedChain` instead, with no forks?
It's used by existing tests, so it will keep on working when we make changes.

You can use the random `count` argument to choose the number of blocks to use from the chain:
https://github.com/ZcashFoundation/zebra/blob/f9c06205766547011fd3181b88aacef2400e0c80/zebra-state/src/service/non_finalized_state/tests/prop.rs#L160

Generating a blockchain with arbitrary forks is a good idea, but it belongs in another ticket, when we have more time.
</blockquote></details>

Done, updated to use the chain in the test vectors. I'll open a ticket for testing with arbitrary forks :+1:
___
*[zebra-state/src/service/tests.rs, line 282 at r5](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mg8dHle6P1ytUwLwdtZ:-MgItkEk9Hva1R62tfjG:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/d17ee46c219ca500b25a76f6e3b23163c33d79e6/zebra-state/src/service/tests.rs#L282)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Just noting that this comment will need updating after the test is finished.

> ```
> /// Test that the best tip height is updated accordingly.
> ```

</blockquote></details>

Done.
___
*[zebra-state/src/service/tests.rs, line 294 at r5](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mg8dx6rEWXCDhRSDQfu:-MgItno0CmbMiSSl-v0q:b-3qwgi4) ([raw file](https://github.com/zcashfoundation/zebra/blob/d17ee46c219ca500b25a76f6e3b23163c33d79e6/zebra-state/src/service/tests.rs#L294)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

The genesis block needs to be committed to the finalized state, so you'll have to do something like this before splitting the chain:

> ```
>         let count = max(count, 1);
> ```

</blockquote></details>

Done, in the `continuous_empty_blocks_from_test_vectors` helper function.
___
*[zebra-state/src/service/tests.rs, line 315 at r5](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgDq6ME2L00ejpoorgz:-MgItHOn1DrpCqdEPsih:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/d17ee46c219ca500b25a76f6e3b23163c33d79e6/zebra-state/src/service/tests.rs#L315)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

This line and the similar line below the non-finalized loop seem redundant, because the check happens at the end of each loop, after `expected_height` is modified:
> ```
> prop_assert_eq!(*best_tip_height.borrow(), expected_height);
> ```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-05 22:58 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 26 of 31 files reviewed, 4 unresolved discussions (waiting on @jvff and @teor2345)

*[a discussion](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MfKQVQM-3m_v6MPse--:-MgNXLwU4WY2ZPcnB6Wv:b8dllw0) (no related file):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

I think the goals of the state chain test are a bit too big for the time we have available.
Can you focus that test on the new best tip interface?

We already have tests for unordered commits, and for the best tip of multiple chains, so there's no need to re-test that code.

We've made the zebra-network changes really small, so I don't think we need to test them right now.
Can you open a ticket for a proptest for the minimum peer version at various heights?
</blockquote></details>

Done, opened issue #2572.

---
___
*[zebra-state/src/service/tests.rs, line 358 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mg4TTL13JN85s8CRsq5:-MgN4RnS6h9mUqY-f_2H:b-gewn5e) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L358)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done, updated to use the chain in the test vectors. I'll open a ticket for testing with arbitrary forks :+1:
</blockquote></details>

I also opened #2571 to consider adding tests with non-finalized chain forks.


<!-- Sent from Reviewable.io -->

2021-08-06 09:49 UTC, teor2345 requested changes
> Reviewed 1 of 3 files at r7, 2 of 3 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 30 of 31 files reviewed, 4 unresolved discussions (waiting on @jvff and @teor2345)

___
*[zebra-state/src/service.rs, line 536 at r9](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgPqFwx-jougYKvVSvD:-MgPqFwx-jougYKvVSvE:b-9m2dxo) ([raw file](https://github.com/zcashfoundation/zebra/blob/032611c21f169ad9c8ca78d807ca3a3a0a0d131d/zebra-state/src/service.rs#L536)):*
I think we'll have to delete this assertion entirely, and rely on the production-only assertion at:
https://github.com/ZcashFoundation/zebra/blob/14532e44c1fed09168eecbf43b5e8ea2d135119f/zebra-state/src/service/check.rs#L73-L85
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         // required by check_contextual_validity, moved here to make testing easier
>         let relevant_chain = self.any_ancestor_blocks(block.block.header.previous_block_hash);
>         assert!(
>             relevant_chain.len() >= POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN,
>             "contextual validation requires at least 28 \
>             (POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN) blocks"
>         );
> ```
</details>

___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-MgPqPtVBtcwgitVB2Hk:bu1pnri) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This didn't quite work the way I expected. Now Zebra panics if a peer gossips a new block (via the inbound service) before it commits 28 blocks.

Let's delete this specific assertion - it's redundant anyway. I've left a comment there as well.

```
   The application panicked (crashed).
   Message:  contextual validation requires at least 28 (POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN) blocks
   Location: zebra-state/src/service.rs:536
   
   Metadata:
   Zcash network: Mainnet
   git commit: 5de4530
...
   
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
     
      0: zebra_state::service::state
         at zebra-state/src/service.rs:672
      1: zebrad::components::inbound::downloads::download_and_verify with hash=00000000013537fd78bb7ac86324cabf77d6c189cc867abec5d5d0e1a0193f67
         at zebrad/src/components/inbound/downloads.rs:170
      2: zebrad::components::inbound::inbound
         at zebrad/src/components/inbound.rs:226
```
https://github.com/ZcashFoundation/zebra/pull/2519/checks?check_run_id=3257291864#step:11:680
___
*[zebra-state/src/service/tests.rs, line 322 at r9](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgPmhVq24WQLOmfny7Y:-MgPmhVq24WQLOmfny7Z:b-nvv5ic) ([raw file](https://github.com/zcashfoundation/zebra/blob/032611c21f169ad9c8ca78d807ca3a3a0a0d131d/zebra-state/src/service/tests.rs#L322)):*
Nit: typo

> ```
> the genesis block
> ```
___
*[zebra-state/src/service/tests.rs, line 352 at r9](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgPnRAw1da2ZdxmFUAZ:-MgPnRAw1da2ZdxmFUA_:b-fe525p) ([raw file](https://github.com/zcashfoundation/zebra/blob/032611c21f169ad9c8ca78d807ca3a3a0a0d131d/zebra-state/src/service/tests.rs#L352)):*
You might want `1..=blocks.len()` here, so that we test with an entirely finalized chain:
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.split_off

This isn't particularly important though.

> ```
>             let finalized_blocks_count = 1..blocks.len();
>             ...
>             let non_finalized_blocks = blocks.split_off(finalized_blocks_count);
> ```


<!-- Sent from Reviewable.io -->

2021-08-06 09:51 UTC, teor2345 requested changes
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 30 of 31 files reviewed, 4 unresolved discussions (waiting on @jvff and @teor2345)

___
*[zebra-state/src/service.rs, line 536 at r9](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgPqFwx-jougYKvVSvD:-MgPrklK4znmm8HUGZjN:b-kq7eac) ([raw file](https://github.com/zcashfoundation/zebra/blob/032611c21f169ad9c8ca78d807ca3a3a0a0d131d/zebra-state/src/service.rs#L536)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

I think we'll have to delete this assertion entirely, and rely on the production-only assertion at:
https://github.com/ZcashFoundation/zebra/blob/14532e44c1fed09168eecbf43b5e8ea2d135119f/zebra-state/src/service/check.rs#L73-L85

> ```
>         // required by check_contextual_validity, moved here to make testing easier
>         let relevant_chain = self.any_ancestor_blocks(block.block.header.previous_block_hash);
>         assert!(
>             relevant_chain.len() >= POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN,
>             "contextual validation requires at least 28 \
>             (POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN) blocks"
>         );
> ```

</blockquote></details>

To be clear, we only want to delete the `POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN` assertion.

The `block.height > self.network.mandatory_checkpoint_height(),` assertion is checked by the chain verifier, so it can stay.


<!-- Sent from Reviewable.io -->

2021-08-06 14:42 UTC, jvff reviewed
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: 29 of 31 files reviewed, 2 unresolved discussions (waiting on @teor2345)

___
*[zebra-state/src/service.rs, line 536 at r9](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgPqFwx-jougYKvVSvD:-MgQuTci-4FIIsYmm7iW:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/032611c21f169ad9c8ca78d807ca3a3a0a0d131d/zebra-state/src/service.rs#L536)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

To be clear, we only want to delete the `POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN` assertion.

The `block.height > self.network.mandatory_checkpoint_height(),` assertion is checked by the chain verifier, so it can stay.
</blockquote></details>

Done.
___
*[zebra-state/src/service/tests.rs, line 311 at r4](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-Mft_I20CLET-1UmIXqB:-MgQpIxxEEq0820NGV-7:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/a9b1533e85030e97dc5fdaaab723b5b93f6b3c45/zebra-state/src/service/tests.rs#L311)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

This didn't quite work the way I expected. Now Zebra panics if a peer gossips a new block (via the inbound service) before it commits 28 blocks.

Let's delete this specific assertion - it's redundant anyway. I've left a comment there as well.

```
   The application panicked (crashed).
   Message:  contextual validation requires at least 28 (POW_AVERAGING_WINDOW + POW_MEDIAN_BLOCK_SPAN) blocks
   Location: zebra-state/src/service.rs:536
   
   Metadata:
   Zcash network: Mainnet
   git commit: 5de4530
...
   
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
     
      0: zebra_state::service::state
         at zebra-state/src/service.rs:672
      1: zebrad::components::inbound::downloads::download_and_verify with hash=00000000013537fd78bb7ac86324cabf77d6c189cc867abec5d5d0e1a0193f67
         at zebrad/src/components/inbound/downloads.rs:170
      2: zebrad::components::inbound::inbound
         at zebrad/src/components/inbound.rs:226
```
https://github.com/ZcashFoundation/zebra/pull/2519/checks?check_run_id=3257291864#step:11:680
</blockquote></details>

Done.
___
*[zebra-state/src/service/tests.rs, line 322 at r9](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgPmhVq24WQLOmfny7Y:-MgQS8Mk9QJS11SfTD3-:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/032611c21f169ad9c8ca78d807ca3a3a0a0d131d/zebra-state/src/service/tests.rs#L322)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

Nit: typo

> ```
> the genesis block
> ```

</blockquote></details>

Done.
___
*[zebra-state/src/service/tests.rs, line 352 at r9](https://reviewable.io/reviews/zcashfoundation/zebra/2519#-MgPnRAw1da2ZdxmFUAZ:-MgQa-SB5ZY_bDu6dug5:b-896fix) ([raw file](https://github.com/zcashfoundation/zebra/blob/032611c21f169ad9c8ca78d807ca3a3a0a0d131d/zebra-state/src/service/tests.rs#L352)):*
<details><summary><i>Previously, teor2345 (teor) wrote…</i></summary><blockquote>

You might want `1..=blocks.len()` here, so that we test with an entirely finalized chain:
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.split_off

This isn't particularly important though.

> ```
>             let finalized_blocks_count = 1..blocks.len();
>             ...
>             let non_finalized_blocks = blocks.split_off(finalized_blocks_count);
> ```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-08 22:12 UTC, teor2345 approved these changes
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jvff)



<!-- Sent from Reviewable.io -->

2021-08-08 23:52 UTC, merged

2021-08-09 11:01 UTC, mpguerra commented
Should this one have closed #1334 or is there a follow up PR to be done?