Implement extra arithmetic operations for Amount
ZcashFoundation/zebra pull request #2577
Opened 2021-08-06 08:51 UTC by teor2345

## Motivation

To modify generated amounts, we need some extra operations on `Amount`.
We also need to extend existing operations to both `NonNegative` and `NegativeAllowed` amounts.

This is part of tickets #2381 and #1895, but it doesn't close those tickets.

## Solution

- extend `Ord` to cover `NonNegative` amounts
  - we could allow comparing `NegativeAllowed` and `NonNegative`, but I haven't needed that yet 
- extend `Mul` to cover `NegativeAllowed`
  - `impl TryFrom<i128> for Amount<C>`
    - put `TryFrom` impls in integer size order
- extend `Div` to cover `NonNegative`
- extend `Neg` to cover `NonNegative`
  - this change conflicts with #2569, happy to go with either PR here

## Review

@oxarbitrage and I are working on implementing value pools.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs

This code will be tested once the rest of PR #2566 is merged.

2021-08-08 15:57 UTC, oxarbitrage requested changes
I think the code looks good in general, assuming everything in here is really needed.

- [ ] Please remove the implementation of `Neg` for `Amount` as it is being discussed in more detail in https://github.com/ZcashFoundation/zebra/pull/2569

- [ ] Plase explain more about the introduction of `i128` and why we need it.

2021-08-08 23:22 UTC, teor2345 commented
>     * Plase explain more about the introduction of `i128` and why we need it.

Done in 7d4bd427

2021-08-09 00:08 UTC, teor2345 commented
I also made the following extra changes, because they were useful for implementing #2566, or diagnosing issues in #2566:

amount::Error

- rename an amount::Error variant to Constraint, so it's clearer
- add extra detail to some errors
- make some amount arithmetic expectations explicit, rather than using `as` or an unchecked operator
- make amount::Error field order consistent

ValueBalance & ValueBalanceError

- impl `Neg` for `ValueBalance`
- add specific pool variants to `ValueBalanceError`

2021-08-09 13:12 UTC, oxarbitrage approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zcashfoundation/zebra/2577)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @teor2345)



<!-- Sent from Reviewable.io -->

2021-08-09 13:13 UTC, merged