Add transactions that failed verification to the mempool rejected list
ZcashFoundation/zebra pull request #2821
Opened 2021-10-01 20:50 UTC by conradoplg

## Motivation

When a mempool-bound transaction fails verification it should be added to the mempool rejected list, so that we can avoid reverifying it again if we receive it again.

### Specifications

### Designs

## Solution

Add a new error type, `TransactionDownloadVerifyError` and make the downloader return it.

When a download/verify task is done, add the tx to the rejected list if needed, depending on the error returned.

## Review

This is not yet ready because it's missing:

- Tests
- Checking if rationale for rejecting or not in each case is correct (feedback welcome)
- I think that his PR must be accepted together with https://github.com/ZcashFoundation/zebra/issues/1186 (otherwise Zebra will reject transactions forever), so maybe the PR for that can be merged into here before this can be merged.

I think @teor2345 may want to take a look.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

2021-10-05 00:05 UTC, teor2345 requested changes, later dismissed
I'm adding a blocking review to this PR, so we don't accidentally merge it.
(We are still deciding if we want to do #2694, which blocks this PR.)

If we decide to go ahead with this PR, we should make these changes:

- Implement rejections as two separate lists:
  - Invalid at this block: `Invalid` and `SpendConflict`
  - Invalid until rollback: `Expired`
- Limit the size of each list to 40,000 entries

2021-10-06 19:07 UTC, conradoplg commented
> I'm adding a blocking review to this PR, so we don't accidentally merge it. (We are still deciding if we want to do #2694, which blocks this PR.)
> 
> If we decide to go ahead with this PR, we should make these changes:
> 
> * Implement rejections as two separate lists:
>   
>   * Invalid at this block: `Invalid` and `SpendConflict`
>   * Invalid until rollback: `Expired`
> * Limit the size of each list to 40,000 entries

This will conflict with #2833 so I suggest merging this as-is and doing these tasks in #2833 or in a separate PR; or waiting for #2833 to be merged and rebasing this on top and implementing these tasks. I don't mind either way. @teor2345 what do you think?

2021-10-06 20:48 UTC, teor2345 commented
> > If we decide to go ahead with this PR, we should make these changes:
> > 
> > * Implement rejections as two separate lists:
> >   
> >   * Invalid at this block: `Invalid` and `SpendConflict`
> >   * Invalid until rollback: `Expired`
> > * Limit the size of each list to 40,000 entries
> 
> This will conflict with #2833 so I suggest merging this as-is and doing these tasks in #2833 or in a separate PR; or waiting for #2833 to be merged and rebasing this on top and implementing these tasks. I don't mind either way. @teor2345 what do you think?

I was planning on doing some of that split in #2694, and then whatever is left over we can do in #2821.

2021-10-06 21:11 UTC, conradoplg commented
> I was planning on doing some of that split in #2694, and then whatever is left over we can do in #2821.

Sounds good, so I'll resume working on this PR when those other PRs merge (or at least are out of draft)

2021-10-07 20:21 UTC, teor2345 commented
> Sounds good, so I'll resume working on this PR when those other PRs merge (or at least are out of draft)

The list split got done in previous PRs, so we can start working on this again.

2021-10-07 20:57 UTC, conradoplg commented
It should be ready for final review @teor2345

2021-10-07 21:07 UTC, teor2345 approved these changes
This looks really good, thanks for the refactors!

2021-10-07 21:34 UTC, merged

2021-10-08 16:42 UTC, dconnolly reviewed
👍