Make block metrics more accurate
ZcashFoundation/zebra pull request #2835
Opened 2021-10-06 05:08 UTC by teor2345

## Motivation

Some of our block metrics names were very confusing.
And some block metrics were updated, even if the block failed contextual validation.

Closes #2832.

## Solution

Error handling:
- Check for contextual validation success before updating metrics

Metrics bug fixes:
- Make the generic zcash block metrics apply to all blocks

New and renamed metrics:
- Add metrics for Zebra full block verification
- Add metrics for all finalized blocks
- Rename checkpoint-specific metrics to clarify their meaning
- Update metric names in dashboards

Dashboard improvements:
- Add the new block metrics to the block verification dashboard

## Review

@conradoplg opened the ticket.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

2021-10-06 05:12 UTC, teor2345 commented on zebra-consensus/src/block.rs
> +                    metrics::counter!("state.full_verifier.committed.block.count", 1);
```suggestion
                    // Update the metrics if semantic and contextual validation passes
                    metrics::counter!("state.full_verifier.committed.block.count", 1);
```

2021-10-06 20:22 UTC, conradoplg requested changes
That's very helpful :+1: 

There is just a typo, some minor grafana visual adjustments (that I added here by setting them in the GUI, exporting the JSON and looking at the diff, so beware! But should be OK), and an optional suggestion for organizing some metrics

2021-10-06 20:22 UTC, conradoplg commented on zebra-state/src/service/finalized_state.rs
> +        metrics::gauge!("state.checkoint.queued.max.height", self.max_queued_height);
```suggestion
        metrics::gauge!("state.checkpoint.queued.max.height", self.max_queued_height);
```

2021-10-06 20:22 UTC, conradoplg commented on zebra-state/src/service/finalized_state.rs
> +                "state.checkpoint.finalized.block.height",
I suggest moving these metrics to `CheckpointVerifier`, to match the `state.full_verifier.committed` metrics in `BlockVerifier`.

Or the other way around, moving `state.full_verifier.committed` metrics to the `FinalizedState`. (Maybe to `queue_and_commit_non_finalized`, and moving the above `state.checkpoint.finalized` metrics to `queue_and_commit_finalized`. It's confusing, sorry :sweat_smile: )

I think this would make it easier to find and reason about them, but it's optional.

2021-10-06 20:22 UTC, conradoplg commented on grafana/block_verification.json
>            "format": "short",
```suggestion
          "format": "none",
```

Shows the entire height instead of e.g. "1.3 M"

2021-10-06 20:22 UTC, conradoplg commented on grafana/block_verification.json
>            "format": "short",
```suggestion
          "format": "none",
```

Same

2021-10-06 20:23 UTC, conradoplg commented on grafana/block_verification.json
> +      "decimals": 6,
```suggestion
      "decimals": 0,
```

Forgot this one. Looks prettier without decimals since it's a block height :grin:

2021-10-06 20:25 UTC, teor2345 commented on grafana/block_verification.json
>            "format": "short",
Aha, I was looking for this setting!

2021-10-06 20:26 UTC, teor2345 commented on zebra-state/src/service/finalized_state.rs
> +        metrics::gauge!("state.checkoint.queued.max.height", self.max_queued_height);
I should have done a search and replace 🙃

2021-10-06 20:28 UTC, teor2345 commented on zebra-state/src/service/finalized_state.rs
> +                "state.checkpoint.finalized.block.height",
I think moving these metrics into the state is required for the gauges to be correct.

Otherwise, the futures could execute out of order, and set the gauge to an older value. (This is a particular issue with checkpoint verification, where hundreds of blocks are being committed to the state at the same time.)

2021-10-06 22:55 UTC, dconnolly submitted a review, later dismissed

2021-10-06 22:55 UTC, dconnolly submitted a review, later dismissed

2021-10-07 00:20 UTC, teor2345 commented on zebra-state/src/service/finalized_state.rs
> +                "state.checkpoint.finalized.block.height",
Here's what I did to fix this up:
* move the height gauges to the state, and update them based on the best tip
* move the verified block counts to the state
* continue to count all verified blocks on all non-finalized chains (not just the best chain)

2021-10-07 00:34 UTC, dconnolly submitted a review, later dismissed

2021-10-07 13:24 UTC, conradoplg approved these changes

2021-10-07 13:42 UTC, merged