Use `tokio-stream` crate to replace usages of Tokio types that were `Stream`s
ZcashFoundation/zebra pull request #2922
Opened 2021-10-20 22:55 UTC by jvff

## Motivation

This is part of the update to use Tokio version 1 (#2200), and must be merged together with the other PRs.

Newer versions of Tokio have removed some `impl Stream` from some types, so they have to either be used differently or have them wrapped in helper types from a separate `tokio-stream` crate.

## Solution

Wrappers from the `tokio-stream` crate were used to fix a few usages of Tokio types that were previously `Stream`s.

## Review

Anyone from the team can review this, but it shouldn't be merged yet.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

2021-10-30 13:22 UTC, oxarbitrage reviewed
I think this looks fine and i can approve, however is hard to do so while depending on others pieces. We need to at least make a reference to the PR that will fix the build errors.

https://github.com/ZcashFoundation/zebra/pull/2933 is merged and it fixed some of the errors but there are more. If they can be fixed here we can maybe consider this as a standalone pull request.

2021-11-01 02:10 UTC, teor2345 reviewed
These code changes seem fine.

Is this the only crate that uses tokio streams?

2021-11-01 02:15 UTC, teor2345 requested changes
One of our tests uses `tokio::StreamExt`:
https://github.com/ZcashFoundation/zebra/blob/e9d2ba835ec40de89370a188f7ebc9801769b8e0/zebra-consensus/src/checkpoint/tests.rs#L11

This is a blocking change.

2021-11-01 17:24 UTC, jvff commented
> One of our tests uses `tokio::StreamExt`:
> 
> https://github.com/ZcashFoundation/zebra/blob/e9d2ba835ec40de89370a188f7ebc9801769b8e0/zebra-consensus/src/checkpoint/tests.rs#L11
> 
> This is a blocking change.

This is unrelated to `tokio-stream`, and is fixed by #2920 (see commit [becd6ca](https://github.com/ZcashFoundation/zebra/pull/2920/commits/becd6ca71b29c2032a16063684a12ae05743c926)).

2021-11-01 22:04 UTC, teor2345 approved these changes, later dismissed
> This is unrelated to tokio-stream, and is fixed by #2920 (see commit becd6ca).

Thanks, that makes sense!

2021-11-02 17:16 UTC, oxarbitrage approved these changes

2021-11-02 18:57 UTC, jvff commented
Merged through #2994.

2021-11-02 18:57 UTC, closed without merging