Update `metrics` to version 0.17
ZcashFoundation/zebra pull request #2937
Opened 2021-10-21 22:16 UTC by jvff

## Motivation

This is part of the update to use Tokio version 1 (#2200), and must be merged together with the other PRs.

The version of the `metrics` crate used by Zebra doesn't support the new version of Tokio. More specifically, `metrics` depends on Hyper 0.14, which has the same issue. Just like in #2936, either a new version of the runtime must run beside the old version of the runtime, or the dependency has to be updated.

## Solution

Update `metrics` to `0.17.0`. This also requires the `metrics-exporter-prometheus` to be updated to `0.6.1`.

## Review

Anyone from the team can review this, but it shouldn't be merged yet.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

2021-10-21 23:33 UTC, teor2345 reviewed
Let's just use the new `String` support in `metrics`.

This is a blocking change, because we risk breaking some metrics by manually tweaking expanded macro code.

2021-10-21 23:33 UTC, teor2345 commented on zebrad/src/components/metrics.rs
> +                        recorder.increment_counter(&METRIC_KEY, 1);
The latest version of `increment_counter!` supports owned `String` values:
https://docs.rs/metrics/0.17.0/metrics/macro.increment_counter.html

So we can replace all this code with something like:
```rust
metrics::increment_counter!(format!("{}.build.info", env!("CARGO_PKG_NAME")), 1);
```

2021-10-25 20:23 UTC, jvff commented on zebrad/src/components/metrics.rs
> +                        recorder.increment_counter(&METRIC_KEY, 1);
Done.

2021-10-25 21:36 UTC, teor2345 reviewed
Let's delete an outdated comment.

2021-10-25 21:36 UTC, teor2345 commented on zebrad/src/components/metrics.rs
>                      // using concat!() to build the name.
Outdated comment: Let's delete these 4 comment lines, because we just removed the manually expanded macro.

2021-10-26 13:09 UTC, jvff commented on zebrad/src/components/metrics.rs
>                      // using concat!() to build the name.
Done.

2021-10-26 21:29 UTC, teor2345 requested changes
This version update is incomplete - other crates also use metrics.

For example:
https://github.com/ZcashFoundation/zebra/blob/a166964a34a35ceae4646661aecbf8af5cdc7182/zebra-network/Cargo.toml#L31

This is a merge blocker.

Please check for similar missed updates in other PRs.
You might find `cargo deny check bans` useful here:
https://embarkstudios.github.io/cargo-deny/checks/bans/index.html#use-case---duplicate-version-detection

2021-10-26 21:29 UTC, teor2345 commented on zebrad/src/components/metrics.rs
> +                    metrics::increment_counter!(format!("{}.build.info", env!("CARGO_PKG_NAME")));
I think we're also missing the `version => CARGO_PKG_VERSION` label here from the expanded macro.

2021-11-01 02:05 UTC, teor2345 requested changes
This PR is missing `metrics` updates in some Zebra crates.
This is a merge blocker.

2021-11-01 17:34 UTC, jvff commented
> This PR is missing `metrics` updates in some Zebra crates. This is a merge blocker.

Oops, I had fixed this in my `full-update-to-tokio-1.12.0` branch but forgot to cherry-pick into this PR :(

2021-11-01 22:07 UTC, teor2345 approved these changes
The dependencies seem fine here.

`cargo deny check bans` will find any duplicates as long as we put PR #2987 in the rollup PR.

2021-11-02 16:21 UTC, dconnolly approved these changes
🎉

2021-11-02 16:23 UTC, dconnolly commented
Once this is merged, we will be able to delete https://github.com/ZcashFoundation/metrics 🎉

2021-11-02 18:57 UTC, jvff commented
Merged through #2994.

2021-11-02 18:57 UTC, closed without merging

2021-11-03 03:10 UTC, teor2345 commented
> Once this is merged, we will be able to delete https://github.com/ZcashFoundation/metrics 🎉

I archived the `ZcashFoundation/metrics` repository, so that builds of older Zebra releases would continue working.

If we need to use it again, we should rename the main branch, so we keep the commits that older Zebra releases depend on.