Verify Halo2 proofs as part of V5 transaction verification
ZcashFoundation/zebra pull request #3039
Opened 2021-11-08 22:54 UTC by dconnolly

## Motivation

We need to verify Halo2 proofs for V5 transactions.

## Solution

Now that we have an async batch Halo2 verifier service, we can call that from our transaction verifier service.

Our current test vectors do not have V5 transactions with verifiable Halo2 proofs. 👀

Resolves #2105 

## Review

Anyone can verify.

Our current test vectors do not have V5 transactions with verifiable Halo2 proofs, the halo2 verifier service is currently verifying that it can verify the proofs by themselves, but reviewer can decide if that is sufficient to merge this PR or if we want to block on V5 transactions w/ Halo2 proofs.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

2021-11-09 19:15 UTC, conradoplg requested changes, later dismissed
Looks good! There's just a small suggestion.

I'll leave this unapproved to make sure https://github.com/ZcashFoundation/zebra/pull/2645 is merged first.

2021-11-09 19:15 UTC, conradoplg commented on zebra-consensus/src/transaction.rs
> +
You can remove this line: https://github.com/ZcashFoundation/zebra/blob/e0d9463a3554b1e52a7a8aeb6cb8408f9f513d63/zebra-consensus/src/transaction.rs#L509

2021-11-10 20:32 UTC, jvff approved these changes, later dismissed

2021-11-14 23:50 UTC, teor2345 requested changes
I'm a bit confused by the GitHub diff in this PR, it seems to include some changes that were reverted in PR #2645.

Can you rebase it after PR #2645 merges?

2021-11-17 00:16 UTC, dconnolly commented
> I'm a bit confused by the GitHub diff in this PR, it seems to include some changes that were reverted in PR #2645.
> 
> Can you rebase it after PR #2645 merges?

This should be fixed now

2021-11-17 03:32 UTC, teor2345 approved these changes, later dismissed
Looks good, but squashing the previous PR caused conflicts.

I'll see if I can push a rebased PR.

2021-11-17 03:39 UTC, teor2345 approved these changes
Looks good, and the diff is much smaller now!

2021-11-17 05:54 UTC, merged