Automatically download and load sprout parameters
ZcashFoundation/zebra pull request #3085
Opened 2021-11-22 02:53 UTC by teor2345

## Motivation

Zebra needs to download the Sprout parameters, so we can verify Sprout spend proofs.

## TODO

Avoid using ~700 MB of RAM for the Sprout parameter download in https://github.com/zcash/librustzcash/pull/459

## Solution

- Add a Sprout download API in https://github.com/zcash/librustzcash/pull/459
- Use that API to download Sprout parameters
- Load the Sprout parameters using the existing API

Closes #3037

## Review

@oxarbitrage can review this PR.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

Most of the tests will be written as part of #322.

## Follow Up Work

- #322

2021-11-24 02:26 UTC, teor2345 commented
The macOS failure seems like a transient network error, so I restarted the jobs:
https://github.com/ZcashFoundation/zebra/runs/4306193160?check_suite_focus=true#step:14:1254

2021-11-24 18:50 UTC, conradoplg requested changes
Looks good, I'm just not sure why CI is failing. It seems the download is incomplete somehow, but an error wasn't raised during download? :thinking:

2021-11-24 20:31 UTC, teor2345 commented
> Looks good, I'm just not sure why CI is failing. It seems the download is incomplete somehow, but an error wasn't raised during download? 🤔

Here's what I think is happening:

I'm opening connections for both parts at the same time, but I start by only reading from the first one. So by the time the first connection finishes, the second one has timed out.

I can fix it, I just need to open each connection when we start reading from it. Rather than at the start.

Also maybe I'm dropping the second connection's timeout error. Or maybe `minreq` is.

2021-11-24 23:19 UTC, conradoplg commented
> Here's what I think is happening:
> 
> I'm opening connections for both parts at the same time, but I start by only reading from the first one. So by the time the first connection finishes, the second one has timed out.
> 
> I can fix it, I just need to open each connection when we start reading from it. Rather than all at once.
> 
> Also maybe I'm dropping the second connection's timeout error. Or maybe `minreq` is.

That makes sense and it seems better to fix it. But I'm not sure it was the cause for the failure because the file had 524909077 bytes, but the first part has 524288000 bytes (621077 bytes less). So it somehow failed just after the second download started :thinking: 
Though it sounds like the kind of issue that may simply disappear if you apply that fix.

2021-11-24 23:57 UTC, teor2345 commented
> > Here's what I think is happening:
> > I'm opening connections for both parts at the same time, but I start by only reading from the first one. So by the time the first connection finishes, the second one has timed out.
> > I can fix it, I just need to open each connection when we start reading from it. Rather than all at once.
> > Also maybe I'm dropping the second connection's timeout error. Or maybe `minreq` is.
> 
> That makes sense and it seems better to fix it. But I'm not sure it was the cause for the failure because the file had 524909077 bytes, but the first part has 524288000 bytes (621077 bytes less). So it somehow failed just after the second download started 🤔 Though it sounds like the kind of issue that may simply disappear if you apply that fix.

The downloads are buffered in the network, kernel, C library, Rust library, and download code. So I'm not surprised there are some extra bytes.

I've also seen failures at exactly 524288000 bytes, it might vary based on timing.

2021-11-25 01:14 UTC, teor2345 commented
> It seems the download is incomplete somehow, but an error wasn't raised during download? 🤔

The incomplete downloads should be fixed now.

I don't know why the download finishes rather than raising an error. All the `zcash_proofs` reader implementations propagate the error correctly.

It's possible `minreq` doesn't return an error in this case, or it's being eaten by one of the readers in the stack. But our code works correctly regardless.

2021-11-25 07:02 UTC, teor2345 commented
The large checkpoints tests are consistently failing due to timeouts.
We were hashing the parameters twice, I've skipped that, let's see how it goes.

We might also need:
- the startup fixes in PR #3104, or
- a debug option that disables the parameter pre-loading (so we can just have one `zebrad` load the parameters)

2021-11-25 15:10 UTC, conradoplg approved these changes

2021-11-25 16:26 UTC, merged