Update the State RFC to match the current database format
ZcashFoundation/zebra pull request #3139
Opened 2021-12-03 06:14 UTC by teor2345

## Motivation

This PR brings Zebra's State RFC up-to-date with the current database format. (Including upcoming Sprout changes.)

This is unexpected client planning work in sprint 24.

## Review

Anyone can review this low-priority PR.

### Reviewer Checklist

  - [ ] Design makes sense
  - [ ] Design matches implementation

## Follow Up Work

- #3137

2021-12-09 19:47 UTC, conradoplg requested changes
Looks good, there are a couple of suggestions for the history tree which is the encoding of a `NonEmptyHistoryTree` struct

2021-12-09 19:47 UTC, conradoplg commented on book/src/dev/rfcs/0005-state-updates.md
> +| `history_tree`                 | `block::Height`        | `zcash_history::Entry`               | Delete  |
```suggestion
| `history_tree`                 | `block::Height`        | `NonEmptyHistoryTree`               | Delete  |
```

2021-12-09 19:47 UTC, conradoplg commented on book/src/dev/rfcs/0005-state-updates.md
> +- `zcash_history::Entry`: `bincode` using `serde`, using `zcash_history`'s `serde` implementation
```suggestion
- `NonEmptyHistoryTree`: `bincode` using `serde`, using `zcash_history`'s `serde` implementation
```

2021-12-09 20:43 UTC, teor2345 commented on book/src/dev/rfcs/0005-state-updates.md
> +| `history_tree`                 | `block::Height`        | `NonEmptyHistoryTree`               | Delete  |
```suggestion
| `orchard_note_commitment_tree` | `block::Height`        | `orchard::tree::NoteCommitmentTree`  | Delete  |
| `history_tree`                 | `block::Height`        | `NonEmptyHistoryTree`                | Delete  |
```

2021-12-10 00:20 UTC, conradoplg approved these changes

2021-12-10 00:22 UTC, conradoplg commented
I'll leave syncing up to you since there seems to be other stuff being merged right now

2021-12-10 13:35 UTC, merged