Document the consensus rules for Section 3.6
ZcashFoundation/zebra pull request #3338
Opened 2022-01-12 22:14 UTC by upbqdn

## Motivation

Each consensus rule from Zcash Protocol Specification should be documented in Zebra for the upcoming audit.

## Solution

This PR documents the consensus rules stated in Section 3.6 of the specification.

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs

Closes #3211.

2022-01-18 22:23 UTC, upbqdn commented
Since #3283 was merged, this PR is ready for review.

2022-01-20 17:42 UTC, conradoplg requested changes

2022-01-20 17:42 UTC, conradoplg commented on zebra-chain/src/sapling/shielded_data.rs
> +    /// <https://zips.z.cash/protocol/protocol.pdf#spendsandoutputs>
I think this would fit better above this line https://github.com/ZcashFoundation/zebra/blob/9734ea10149321b53ef37039078aea3546d2a7d8/zebra-consensus/src/transaction.rs#L801
we already document other rules in that function

2022-01-24 14:28 UTC, upbqdn commented
Oops, I didn't notice Clippy is unhappy until now. I'll fix it.

2022-01-24 18:18 UTC, conradoplg approved these changes
Looks good

2022-01-24 22:51 UTC, teor2345 commented
The Zcash parameter download timed out. `PARAMETER_DOWNLOAD_TIMEOUT` is 60 minutes, but we only run CI for 30 minutes. This is probably an issue with the remote website.

@Mergifyio refresh

2022-01-24 22:54 UTC, teor2345 commented
Oops

@Mergifyio update

2022-01-24 23:27 UTC, merged