fix(actions): run coverage collection when pushing to main
ZcashFoundation/zebra pull request #3561
Opened 2022-02-16 22:03 UTC by dconnolly

## Motivation

During refactoring, we accidentally disabled Coverage collection on #main meaning we compare coverage diffs on PRs in an inconsistent manner.

## Solution

Trigger on push to main as well.

Resolves #3533

## Review

@gustavovalverde

2022-02-18 08:22 UTC, gustavovalverde commented
ping @dconnolly

2022-02-21 21:17 UTC, dconnolly commented
@gustavovalverde can you review?

2022-02-21 22:42 UTC, gustavovalverde commented
I still see the pending suggestions. Are we leaving it like this?

2022-02-21 22:45 UTC, dconnolly commented
> I still see the pending suggestions. Are we leaving it like this?

Oh! I can't see any suggestions or convos?

<img width="809" alt="image" src="https://user-images.githubusercontent.com/552961/155034740-1bafb319-1652-4d52-8a4d-e7c131f713bc.png">

2022-02-21 23:06 UTC, gustavovalverde commented
lmao? 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/16890942/155036283-0c708b89-1090-4ddf-b471-e927c1d266a5.png">

2022-02-21 23:30 UTC, teor2345 commented
> lmao?
> <img alt="image" width="644" src="https://user-images.githubusercontent.com/16890942/155036283-0c708b89-1090-4ddf-b471-e927c1d266a5.png">

@gustavovalverde can you submit the review, so everyone can see your pending suggestions?

You can just do a comment review.

2022-02-21 23:36 UTC, gustavovalverde requested changes

2022-02-21 23:36 UTC, gustavovalverde commented on .github/workflows/coverage.patch.yml
> +      - main
```suggestion
```

We don't require this on pushes, it just needed for `pull_request` events, it might create an unexpected behavior with push.

2022-02-21 23:36 UTC, gustavovalverde commented on .github/workflows/coverage.yml
> +      - main
```suggestion
  push:
    branches:
      - main
    paths:
      - '**/*.rs'
      - '**/*.txt'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'codecov.yml'
      - '.github/workflows/coverage.yml'
```

2022-02-21 23:36 UTC, gustavovalverde commented on .github/workflows/coverage.yml
> +      - main
We just want to run on push to main on this specific path changes

2022-02-21 23:38 UTC, gustavovalverde commented
Oh, that was embarrassing 😓

2022-02-21 23:38 UTC, gustavovalverde commented
Oh, that was embarrassing 😓

2022-02-22 09:44 UTC, gustavovalverde approved these changes

2022-02-22 09:48 UTC, merged

2022-02-22 16:36 UTC, dconnolly commented
👍👍👍