fix(ci): deploy full sync tests to europe-west1
ZcashFoundation/zebra pull request #3771
Opened 2022-03-07 22:03 UTC by dconnolly

## Motivation

We want to spread out our test deployments to avoid gcloud resource limits.

## Solution

Deploy the long, full sync tests to a different gcloud region/zone, europe-west1 (Belgium). No other workflows are currently using this region.

## Review

@gustavovalverde 

### Reviewer Checklist

  - [ ] `test-full-sync.yml` successfully deploys and completes to new region

2022-03-07 22:14 UTC, teor2345 requested changes
> Deploy the long, full sync tests to a different gcloud region/zone, europe-west1 (Belgium). No other workflows are currently using this region.

Is this region faster for full syncs?

Full syncs are currently our slowest job, so we should put them in the fastest region. (And move other jobs if needed.)

Can you do some testing to find the fastest region?
(Currently `us-central1-a` is at 99.99% at the 6 hour timeout.)

2022-03-08 12:45 UTC, gustavovalverde commented
@dconnolly @teor2345  I saw the issue on the PR that failed, it was because of the `pd-extreme` quota. Moving the full sync test to another region won't solve it, as this is the only test requiring this type of SSD disk (other deployments are not impacting this quota)

I few days ago I requested a quota increase to Google. I'll cc you in the email thread.

2022-03-08 13:05 UTC, gustavovalverde commented
If we'd like to fix this ASAP, we can change the SSD to `pd-ssd` instead of `pd-extreme`, or consider https://github.com/ZcashFoundation/zebra/pull/3766 to reduce the amount of `full sync` instances created on a single PR and running in parallel

2022-03-09 21:23 UTC, dconnolly commented
> If we'd like to fix this ASAP, we can change the SSD to `pd-ssd` instead of `pd-extreme`, or consider #3766 to reduce the amount of `full sync` instances created on a single PR and running in parallel

Yeah let's close this one and switch to pd-ssd

2022-03-09 21:23 UTC, closed without merging

2022-03-09 22:38 UTC, teor2345 commented
> > If we'd like to fix this ASAP, we can change the SSD to `pd-ssd` instead of `pd-extreme`, or consider #3766 to reduce the amount of `full sync` instances created on a single PR and running in parallel
> 
> Yeah let's close this one and switch to pd-ssd

I'd like to try #3766 and the quota increase first.

`pd-ssd` might cause performance issues.