fix(ci): only run full sync workflow on ✅ review
ZcashFoundation/zebra pull request #3772
Opened 2022-03-07 22:15 UTC by dconnolly

## Motivation

We're hitting GitHub rate limits often, causing tests and build to fail spuriously.

## Solution

Instead of running the full sync test workflow every time a review is submitted, only run the build job (and its dependent test job) when the review has the 'accepted' value.

## Review

### Reviewer Checklist

  - [ ] test-full-sync.yml is skipped unless a ✅ review is submitted

2022-03-07 22:18 UTC, teor2345 requested changes
Mergify doesn't submit an approved review, so the full sync test won't run on Mergify PRs.

Instead, we might want it to *only* run on Mergify PRs.

2022-03-07 22:18 UTC, gustavovalverde commented
We would actually require 2 reviews to be sure, and use a bot to automate 1 review when all other checks (previous this one) are in a green state.

2022-03-07 22:47 UTC, teor2345 commented
> We would actually require 2 reviews to be sure, and use a bot to automate 1 review when all other checks (previous this one) are in a green state.
> 
> Edit: or also do as @teor2345 suggested. On Mergify PR, but we'd have to go back to allow mergify to merge-in-place (on the same PR), to have the check status reported on the PR that triggered the merge.

I think we can filter the job by the Mergify queue branch name, see:
- #3773

2022-03-08 03:28 UTC, dconnolly commented
> > We would actually require 2 reviews to be sure, and use a bot to automate 1 review when all other checks (previous this one) are in a green state.
> > Edit: or also do as @teor2345 suggested. On Mergify PR, but we'd have to go back to allow mergify to merge-in-place (on the same PR), to have the check status reported on the PR that triggered the merge.
> 
> I think we can filter the job by the Mergify queue branch name, see:
> 
> * [fix(ci): only run the full sync test on mergify queue PRs #3773](https://github.com/ZcashFoundation/zebra/pull/3773)

I think this is defunct now 👍

2022-03-08 03:28 UTC, closed without merging