s/pd-extreme/pd-ssd/ to avoid quotas
ZcashFoundation/zebra pull request #3823
Opened 2022-03-09 21:27 UTC by dconnolly

## Motivation

We are hitting gcloud quota limits for use of `pd-extreme` disks per region/zone in `us-central1`.

## Solution

Switch `test-full-sync.yml` to use `pd-ssd` instead, which has more amenable limits.

## Review

@gustavovalverde 

### Reviewer Checklist

  - [ ] Full sync test doesn't slow down too much

2022-03-09 22:40 UTC, teor2345 requested changes
I'd like to try https://github.com/ZcashFoundation/zebra/pull/3766 and the quota increase first.

pd-ssd might cause performance issues, can you run a manual full sync test to check?

2022-03-09 23:49 UTC, dconnolly commented
> I'd like to try #3766 and the quota increase first.
> 
> pd-ssd might cause performance issues, can you run a manual full sync test to check?

Marked as do-not-merge for now while we test both of these

2022-03-09 23:52 UTC, dconnolly commented
> > I'd like to try #3766 and the quota increase first.
> > pd-ssd might cause performance issues, can you run a manual full sync test to check?
> 
> Marked as do-not-merge for now while we test both of these

Kicked off full sync test: https://github.com/ZcashFoundation/zebra/actions/runs/1960310775

2022-03-10 11:39 UTC, gustavovalverde commented
Failed at **%99.988**

2022-03-10 21:42 UTC, dconnolly commented
@gustavovalverde @teor2345 I could close this for now

2022-03-10 22:01 UTC, gustavovalverde commented
I think we'll have to fallback to `pd-ssd`, as a ~90% of our billing cost so far this month is being caused just by `pd-extreme`

2022-03-10 22:03 UTC, gustavovalverde approved these changes

2022-03-10 22:04 UTC, gustavovalverde commented
I'm approving, I'll leave the decision to remove the `do-not-merge` label to you. But I don't see keeping `pd-extreme` as cost effective.

2022-03-10 22:07 UTC, teor2345 commented
> I think we'll have to fallback to `pd-ssd`, as a ~90% of our billing cost so far this month is being caused just by `pd-extreme` 😓

I was going to ask about disks in the engineering sync we just had. But I didn't get a chance.

This seems like a good idea, we should fix performance issues by changing Zebra code.

2022-03-10 22:07 UTC, teor2345 approved these changes
I'm happy with this change now.

2022-03-10 22:08 UTC, teor2345 commented
> Failed at **%99.988**

`pd-ssd` is about the same as `pd-extreme`, so this change shouldn't have any CI performance impacts.

2022-03-10 22:10 UTC, merged