Disallow Orchard ivk = 0 on IncomingViewingKey::from & SpendingKey generation
ZcashFoundation/zebra pull request #3962
Opened 2022-03-25 05:09 UTC by dconnolly

## Motivation

### Specifications

```
if ivk ∈ {0, ⊥}, discard this key and repeat with a new sk.
```

https://zips.z.cash/protocol/protocol.pdf#orchardkeycomponents

<img width="791" alt="image" src="https://user-images.githubusercontent.com/552961/160057504-28e84c9e-6078-4015-bd07-08ef82009d2b.png">

## Solution

Update `impl From<FullViewingKey> for IncomingViewingKey` to become a `TryFrom`, and return `Result::Err` if we get ⊥ or the possible `pallas::Scalar` value is `0` in the scalar field.

Update `SpendingKey::new()` to also check that a prospective `sk` doesn't lead to an invalid `IncomingViewingKey`.

Also implement `TryFrom<[u8; 64]> for IncomingViewingKey` to enforce that parsing of the raw encoding checks for and rejects the same values.

Closes #3869 

## Review

This is low priority because it is not an NU5 consensus rule, but an Orchard protocol check for keygen and ingesting of keys/addresses. 

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

2022-03-25 06:29 UTC, teor2345 commented
I'm marking this as "do not merge", until we work out how risky it is.
(Or until we've tagged the NU5 testnet rollback code.)

2022-03-25 15:28 UTC, jvff approved these changes, later dismissed
Looks good. I added some ideas, but they are optional.

2022-03-25 15:28 UTC, jvff commented on zebra-chain/src/orchard/keys.rs
> +            // "if ivk = {0, ⊥ }, discard this key and repeat with a new sk"
Should the method documentation be updated as well?

2022-03-25 15:28 UTC, jvff commented on zebra-chain/src/orchard/arbitrary.rs
> +                let incoming_viewing_key = keys::IncomingViewingKey::try_from(full_viewing_key)
Optional idea: this could also use a `prop_filter` step to avoid the panic.

2022-03-25 15:28 UTC, jvff commented on zebra-chain/src/orchard/keys.rs
> +        ivk_bytes[..].copy_from_slice(&bytes[32..]);
Tiny nit for consistency:

```suggestion
        ivk_bytes.copy_from_slice(&bytes[32..]);
```

2022-03-25 22:04 UTC, dconnolly commented
> I'm marking this as "do not merge", until we work out how risky it is. (Or until we've tagged the NU5 testnet rollback code.)

All of our shielded key code beyond what is serialized/deserialized on chain/in P2P network messages is currently not being used beyond testing and conformance, until we use it for wallet functionality or whatever. That includes Orchard `IncomingViewingKey` and `SpendingKey` derivation. I would consider this a low-risk change.

2022-03-25 22:10 UTC, dconnolly commented
> I'm marking this as "do not merge", until we work out how risky it is. (Or until we've tagged the NU5 testnet rollback code.)

Definitely willing to hold as :do-not-merge: until we tag as it is low priority

2022-03-28 00:58 UTC, teor2345 commented on zebra-network/proptest-regressions/peer_set/set/tests/prop.txt
> +cc a1098eb7e8d9970d8624949e224c398cc3f522a3da8669906cda4dbe27977da8 # shrinks to total_number_of_peers = 2
This proptest failure seems unrelated to this change, can we leave it out?

(Sometimes the network tests panic when `cargo watch` restarts a test, when the network connection is unreliable, or when there are multiple tests running at the same time.)

2022-03-28 14:00 UTC, daira commented on zebra-chain/src/orchard/keys.rs
> +            // "if ivk = {0, ⊥ }, discard this key and repeat with a new sk"
```suggestion
            // "if ivk ∈ {0, ⊥}, discard this key and repeat with a new sk"
```

2022-04-26 23:21 UTC, teor2345 commented
@mergifyio update

2022-05-11 00:38 UTC, dconnolly commented
@Mergifyio update

2022-05-21 18:50 UTC, dconnolly commented
@mergify rebase

2022-05-25 03:09 UTC, teor2345 commented
@dconnolly this PR hasn't changed in 2 months, can we consider turning it into a ticket as part of the Cryptography triage?

2022-06-04 13:41 UTC, dconnolly commented
> @dconnolly this PR hasn't changed in 2 months, can we consider turning it into a ticket as part of the Cryptography triage?

I have fixed it, there was a API change in `bitslice` that was causing trouble, and rebased on main

2022-06-06 04:11 UTC, teor2345 reviewed
Looks good to me, but I'd like someone who is familiar with the spec changes to review it as well.

2022-06-09 19:37 UTC, conradoplg approved these changes, later dismissed
Looks good

2022-06-16 01:08 UTC, dconnolly commented
https://github.com/Mergifyio update

2022-06-23 17:39 UTC, dconnolly commented
[Mergifyio](https://github.com/Mergifyio) update

2022-06-28 03:30 UTC, teor2345 commented
@mergifyio update

2022-06-28 03:33 UTC, teor2345 approved these changes
Re-approving based on previous approvals

2022-06-28 04:39 UTC, daira approved these changes, later dismissed
Untested ACK.

2022-06-28 06:11 UTC, teor2345 requested changes
This PR needs `clippy::unwrap-in-result` fixes:
https://github.com/ZcashFoundation/zebra/runs/7086134368?check_suite_focus=true#step:7:543

2022-07-03 06:02 UTC, daira approved these changes
re-untested ACK

2022-07-25 22:02 UTC, teor2345 approved these changes
Thanks for these clippy fixes, sorry no-one reviewed this PR until now!

2022-08-01 02:35 UTC, teor2345 commented
@mergofyio update

2022-08-01 02:35 UTC, teor2345 commented
@mergifyio update

2022-08-01 09:06 UTC, merged