fix(sync): Add an extra block retry, to speed up the initial sync
ZcashFoundation/zebra pull request #4185
Opened 2022-04-25 07:06 UTC by teor2345

## Motivation

As part of #4155, we want to speed up the `zebrad` initial sync.

If Zebra can't fetch a block, it restarts the sync, causing an expensive timeout. It's cheaper to just retry downloading the block again.

## Solution

- Retry each block download 3 times, rather than 2 times

## Review

Anyone can review this PR. If it makes the full sync faster, it's an urgent CI fix.

This PR is based on PR #4183.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

2022-04-25 07:07 UTC, teor2345 commented
I'm running a full sync test here:
https://github.com/ZcashFoundation/zebra/actions/runs/2218556843

This PR might be faster than the checkpoint PR, but it could be slower if the extra retries slow down a significant number of block downloads.

2022-04-25 17:34 UTC, conradoplg requested changes
Didn't seem to improve sync time, and requires adjusting the `ensure_timeouts_consistent` test

2022-04-25 20:21 UTC, teor2345 commented
> This PR might be faster than the checkpoint PR, but it could be slower if the extra retries slow down a significant number of block downloads.

This took 5h42m, an improvement of about 10 minutes from the checkpoint PR.

2022-04-25 20:23 UTC, teor2345 commented
> Didn't seem to improve sync time, and requires adjusting the `ensure_timeouts_consistent` test

@conradoplg I see an improvement of 10 minutes between this PR and the full sync test on #4183.

I fixed the test, the failing check was obsolete.

2022-04-26 15:16 UTC, conradoplg approved these changes
Looks good, we'll just need to fix the CI issue ("`Error: No such container: klt-sync-checkpoint-4185-merge-8323730-zars`")

> @conradoplg I see an improvement of 10 minutes between this PR and the full sync test on #4183.

Ah sorry, I was looking at the total time 
![image](https://user-images.githubusercontent.com/35766/165334045-d37bf860-9321-42fc-a7df-e75cf7a0eac8.png)

2022-04-26 16:28 UTC, merged