Give each build image and its job a unique name
ZcashFoundation/zebra pull request #4237
Opened 2022-04-28 09:12 UTC by teor2345

## Motivation

We currently have 4 jobs named "Build images", and 2 images named "zebrad-test".

We're also seeing some weird CI failures like:
- #4234 

Previous bugs like #3991 were caused by conflicting operations on the same image. So if we make all our image and job names unique, we can rule out duplicate names as a cause of these bugs. (And any other future bugs.)

We want to merge this PR after the zcash-params build fix:
Depends-On: #4235

## Solution

- Name each image with a unique name
- Name each job with a unique name, using the image name

This is a quick fix for duplicate names. We can choose better names in PR #3941.

I also stopped requiring the "Build Images" job in GitHub branch protection, because it wasn't really working anyway.

## Review

Anyone can review this urgent PR - the #4234 failures seem to be happening a lot lately.

### Reviewer Checklist

  - [ ] All the jobs pass on the PR and merge queue
  - [ ] The zcash-params job passes after merging

2022-04-28 10:24 UTC, gustavovalverde approved these changes
I'll approve this as a quick-fix. But we need to name (most things) a bit better in https://github.com/ZcashFoundation/zebra/pull/3941

2022-04-28 15:53 UTC, gustavovalverde requested changes
This is failing as it seems we can't use an env variable in a job name.

I'll start working on this one to solve this and other issues https://github.com/ZcashFoundation/zebra/issues/4239

2022-04-28 22:42 UTC, teor2345 commented on .github/workflows/docker-image-build.yml
>      name: Build images
```suggestion
    name: Build ${{ inputs.image_name }} images
```

2022-04-28 22:56 UTC, teor2345 commented
> This is failing as it seems we can't use an env variable in a job name.

@gustavovalverde I removed the env var, and fixed the job conditions so the workflows run in PRs where they are modified.

You can see the new job name here:
https://github.com/ZcashFoundation/zebra/runs/6219878355?check_suite_focus=true

> I'll start working on this one to solve this and other issues #4239

I'm not sure if fixing test names or refactoring CI is a high priority.

In the test meeting, we agreed that we'd start by putting one new lightwalletd integration test in CI - the `test-fully-synced-rpc` test. That will unblock all the other tests.

So I'd like to focus on getting part of PR #4223 done first.

2022-04-29 01:06 UTC, teor2345 commented
This PR doesn't seem to fix #4234, so it's not critical:
> error: failed to solve: failed to fetch oauth token: unexpected status: 401 Unauthorized

https://github.com/ZcashFoundation/zebra/runs/6219878355?check_suite_focus=true#step:9:2164

2022-05-01 15:43 UTC, gustavovalverde reviewed
I've implemented https://github.com/ZcashFoundation/zebra/pull/4254 which helps a lot with:
https://github.com/ZcashFoundation/zebra/issues/4234

I'd prefer to merge that one first.

2022-05-03 22:34 UTC, teor2345 commented
Obsoleted by #4271

2022-05-03 22:34 UTC, closed without merging