Breaking: fix(rpc): Add a config for multi-threaded RPC server requests
ZcashFoundation/zebra pull request #5013
Opened 2022-08-31 04:02 UTC by teor2345

## Changelog

See the README changes in this PR for a changelog breaking change notice.

## Motivation

Our users have asked for multi-threaded RPCs.

## Solution

- Add a config for multi-threaded RPCs
- Add tests for multi and single threaded RPC calls
- Run `lightwalletd` tests with multi-threaded RPCs

Depends-On: #4806
Fixes #5012

## Review

This is a routine bug fix.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

2022-08-31 22:06 UTC, arya2 requested changes
Looks good, one small fix suggested for the `rpc_sever_spawn_parallel_threads()` test

2022-08-31 22:06 UTC, arya2 commented on zebra-rpc/src/server/tests/vectors.rs
> +        parallel_cpu_threads: 1,
```suggestion
        parallel_cpu_threads: if parallel_cpu_threads { 0 } else { 1 },
```

2022-09-01 01:34 UTC, teor2345 commented on zebra-rpc/src/server/tests/vectors.rs
> +        parallel_cpu_threads: 1,
Thanks for catching this!

I fixed it in 0bcbcc87d26f2c1f38cc4bf9d0bc45da51df947f.
I also squashed the fixup commits (and rebased on the latest `main` branch).

2022-09-01 11:58 UTC, arya2 approved these changes, later dismissed
Looks good

2022-09-01 18:18 UTC, arya2 commented
[isolate-rpcs](https://github.com/ZcashFoundation/zebra/tree/isolate-rpcs) merged, should probably target main now

2022-09-04 01:25 UTC, oxarbitrage approved these changes
Already approved before by @arya2 , i also checked the PR and looks good to me too so i am re approving so it can gets merged.

2022-09-04 05:03 UTC, merged