fix(docker): Add latest and edge tags to Docker images
ZcashFoundation/zebra pull request #5312
Opened 2022-10-03 02:00 UTC by teor2345

## Motivation

`latest` is the default Docker tag, but it's missing from published Zebra images.

### Specifications

https://github.com/docker/metadata-action#latest-tag

## Solution

- Add `latest` and `edge` tags to published Docker images

## Review

Anyone can review this PR.

It is only a release blocker if we want users to be able to easily use Docker images.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

2022-10-03 17:33 UTC, gustavovalverde requested changes
I wouldn't add a `latest` tag to non-stable releases.

When a `<pre-release>` information is included in the image tag, the `latest` tag won't be automatically added as those are, by default, reserved for stable images.

For example, we will release `1.0.0` and this will also auto-add the `latest` tag, but if we then publish `1.0.1-alpha.1`, we wouldn't want users to download an alpha version if they add the `latest` tag, but instead keep downloading `1.0.0` until `1.0.1` is published

This is explained with more detail here: https://github.com/ZcashFoundation/zebra/pull/5138#discussion_r971425816

2022-10-03 20:00 UTC, teor2345 commented
> I wouldn't add a `latest` tag to non-stable releases.
> 
> When a `<pre-release>` information is included in the image tag, the `latest` tag won't be automatically added as this one is, by default, reserved for stable images.
> 
> For example, we will release `1.0.0` and this will also auto-add the `latest` tag, but if we then publish `1.0.1-alpha.1`, we wouldn't want users to download an alpha version if they add the `latest` tag, but instead keep downloading `1.0.0` until `1.0.1` is published
> 
> This is explained with more detail here: [#5138 (comment)](https://github.com/ZcashFoundation/zebra/pull/5138#discussion_r971425816)

Thanks, I summarised that explanation next to the config that will create the `latest` tag.

2022-10-03 20:02 UTC, gustavovalverde submitted a review, later dismissed
LGTM

2022-10-04 04:14 UTC, teor2345 commented
Some jobs didn't run on this PR, but the workflow rules contain `.github/workflows/build-docker-image.yml`.

I'll try re-running it, maybe GitHub is having issues.

2022-10-04 04:14 UTC, teor2345 commented
@mergifyio update

2022-10-04 04:19 UTC, teor2345 commented
Jobs seem to be totally unresponsive to branch pushes as well:
![2662F1CE-5393-445D-B5CA-8D9DB64549EC](https://user-images.githubusercontent.com/8951843/193733379-c02a1be0-54cc-49fa-abf0-f8e1e716af2c.jpeg)

2022-10-04 04:19 UTC, teor2345 commented
Ok, closing and re-opening seemed to work.

2022-10-04 06:26 UTC, teor2345 commented on .github/workflows/build-docker-image.yml
> +            type=edge,enable=${{ !env.USE_DOCKERHUB && is_default_branch }}
```suggestion
            type=edge,enable=${{ !env.USE_DOCKERHUB && {{is_default_branch}} }}
```

2022-10-04 06:28 UTC, teor2345 commented
Looks like the workflow syntax was wrong, but the error only showed up on the workflow details screen, because the mistake was in a sub-workflow.

2022-10-04 06:37 UTC, teor2345 commented
@mergifyio update

2022-10-04 06:45 UTC, teor2345 commented
Ok, that should all be fixed now, some of my changes didn't work.

2022-10-04 19:44 UTC, gustavovalverde approved these changes

2022-10-05 12:24 UTC, gustavovalverde commented
@Mergifyio update

2022-10-05 20:54 UTC, teor2345 commented
@mergifyio update

2022-10-05 20:56 UTC, teor2345 commented
It looks like some of the instances for this PR got deleted about 10 hours ago, before the tests had finished. I'm not sure why, the instance delete job wasn't running.
> Error: google-github-actions/ssh-compute failed with: failed to execute gcloud command `gcloud compute ssh lwd-grpc-wallet-5312-merge-9e47110 --zone us-central1-a ...
> - The resource 'projects/zealous-zebra/zones/us-central1-a/instances/lwd-grpc-wallet-5312-merge-9e47110' was not found

https://github.com/ZcashFoundation/zebra/actions/runs/3189762463/jobs/5209366519#step:6:99
https://github.com/ZcashFoundation/zebra/actions/runs/3189762463/jobs/5209407086#step:6:99

2022-10-06 10:36 UTC, merged