fix(ci): fix full sync failure by adding a job for 1810k blocks
ZcashFoundation/zebra pull request #5391
Opened 2022-10-12 16:03 UTC by arya2

## Motivation

This is the standard fix for when a full sync job runs too long (`logs-checkpoint` needs to sync ~45k blocks as of the latest checkpoint update).

## Solution

- Add full sync job for 1810k blocks

See [fixing-ci-sync-timeouts](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-integration.md#fixing-ci-sync-timeouts)

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

2022-10-12 16:03 UTC, arya2 commented
The checkpoint step took 4-5 hours to get to [1810k blocks](https://github.com/ZcashFoundation/zebra/actions/runs/3223410431/jobs/5291373001#step:6:812) (timed out after ~1817k)

2022-10-12 18:03 UTC, arya2 commented
ssh failure in `logs-checkpoint`:
https://github.com/ZcashFoundation/zebra/actions/runs/3236318547/jobs/5302131447#step:6:777

2022-10-12 20:51 UTC, teor2345 commented
> ssh failure in `logs-checkpoint`: https://github.com/ZcashFoundation/zebra/actions/runs/3236318547/jobs/5302131447#step:6:777

There are lots of different ways `ssh` can fail, can you please quote the actual failure log?

> Timeout, server 34.123.232.71 not responding.

2022-10-12 20:56 UTC, teor2345 requested changes
I also saw these sync warnings in the logs:
> 2022-10-11T03:59:58.369043Z  WARN {net="Main"}: zebrad::components::sync::progress: chain updates have stalled, state height has not increased for 30 minutes. Hint: check your network connection, and your computer clock and time zone sync_percent=31.016% current_height=Height(572486) network_upgrade=Sapling time_since_last_state_block=30m target_block_spacing=PT75S max_block_spacing=None is_syncer_stopped=false

https://github.com/ZcashFoundation/zebra/actions/runs/3223410431/jobs/5295854595#step:6:2844

Every time they happen, the sync takes half an hour longer waiting for a single block. So maybe we could drop the timeout back down to 10 minutes first?

(We might still need this PR.)

2022-10-12 21:02 UTC, teor2345 commented
> Every time they happen, the sync takes half an hour longer waiting for a single block. So maybe we could drop the timeout back down to 10 minutes first?

Let's see how #5397 goes, then try this one?

There is also a timeout in the Rust test we might need to fix.

2022-10-13 00:48 UTC, arya2 commented
> I also saw these sync warnings in the logs:
> 
> > 2022-10-11T03:59:58.369043Z  WARN {net="Main"}: zebrad::components::sync::progress: chain updates have stalled, state height has not increased for 30 minutes. Hint: check your network connection, and your computer clock and time zone sync_percent=31.016% current_height=Height(572486) network_upgrade=Sapling time_since_last_state_block=30m target_block_spacing=PT75S max_block_spacing=None is_syncer_stopped=false
> 
> https://github.com/ZcashFoundation/zebra/actions/runs/3223410431/jobs/5295854595#step:6:2844
> 
> Every time they happen, the sync takes half an hour longer waiting for a single block. So maybe we could drop the timeout back down to 10 minutes first?

We should definitely fix that first.

> (We might still need this PR.)

It's doubtful it'll make it from 1790k to ~1834k, though we might be able to replace `logs-1790k` (~2h 40m) with `logs-1800k` (seems to be another ~2h 20m) instead of adding a new step.

2022-10-18 20:48 UTC, gustavovalverde commented
@arya2 do we still need this PR?

2022-10-18 22:01 UTC, gustavovalverde commented
Seems like we are still having timeouts in the `main` branch, but I'll left @teor2345 the last call here even though is a standard change, as I'm not sure if there are other works in progress to fix it another way

2022-10-18 22:19 UTC, arya2 commented
> do we still need this PR?

I believe we do, but I'll just quickly check the logs for the timeouts and perhaps replace `logs-1790k` with `logs-1800k`.

2022-10-19 05:28 UTC, teor2345 commented
> Seems like we are still having timeouts in the `main` branch, but I'll left @teor2345 the last call here even though is a standard change, as I'm not sure if there are other works in progress to fix it another way

We're done with the fixes due to PR #5257, it should all be standard fixes from now on.

2022-10-19 18:28 UTC, gustavovalverde approved these changes, later dismissed
LGTM

2022-10-19 20:14 UTC, teor2345 requested changes
I think the regexes might be wrong here?

2022-10-19 20:14 UTC, teor2345 commented on .github/workflows/deploy-gcp-tests.yml
> +          -e 'estimated progress.*current_height.*=.*180[0-9][0-9][0-9][0-9].*remaining_sync_blocks' \
This line is actually redundant, 1,800,000 - 1,809,999 is covered by the next regex.

```suggestion
```

2022-10-19 20:14 UTC, teor2345 commented on .github/workflows/deploy-gcp-tests.yml
> +          -e 'estimated progress.*current_height.*=.*1[8-9][2-9][0-9][0-9][0-9][0-9].*remaining_sync_blocks' \
These regexes look like they might be incorrect, they seem to be skipping 1,900,000 - 1,919,999.

We want to match:
- 1,820,000 - 1,899,999
- 1,900,000 - 1,999,999

```suggestion
          -e 'estimated progress.*current_height.*=.*18[2-9][0-9][0-9][0-9][0-9].*remaining_sync_blocks' \
          -e 'estimated progress.*current_height.*=.*19[0-9][0-9][0-9][0-9][0-9].*remaining_sync_blocks' \
```

2022-10-20 09:34 UTC, mpguerra commented
is there an github issue that this is related to that I can link in?

2022-10-20 16:20 UTC, arya2 commented
> is there a github issue that this is related to that I can link in?

No, this was ad-hoc and trivial.

2022-10-21 01:02 UTC, teor2345 approved these changes
Thanks!

2022-10-21 02:19 UTC, teor2345 commented
@mergifyio update

2022-10-21 06:01 UTC, merged