docs(release): add information on how we tag and release
ZcashFoundation/zebra pull request #5392
Opened 2022-10-12 16:23 UTC by gustavovalverde

## Motivation

We want to document the process we decided for audits and new features. We also want to write down the goals we're trying to satisfy.

Closes #5259

## Solution

Improve the documentation from our [Zebra versioning and releases](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/release-process.md) 

## Review

This is a draft for revision. I started a whole document but then I realized I was repeating most of the information already available in the Release process and the [release checklist](https://github.com/ZcashFoundation/zebra/blob/main/.github/PULL_REQUEST_TEMPLATE/release-checklist.md)

As @arya2 and @teor2345 recently made the first release candidate, they might have more fresh ideas to add here.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

2022-10-13 00:58 UTC, teor2345 requested changes
Looks good!

We talked about audit tags and audit branches, but they aren't mentioned in this document.
Can you add a short section based on what we decided in the meeting:
- we'll give the latest `rc` tag to the auditors to review
- when we get the audit report, if the auditors want to review a separate branch with just the audit fixes, we'll make a branch from the audit tag, and make fixes there

2022-10-13 00:58 UTC, teor2345 commented on book/src/dev/release-process.md
> +To keep the `main` branch in a releasable state, breaking changes and experimental features must be gated behind a [feature flag](https://doc.rust-lang.org/cargo/reference/features.html).
Some breaking changes are needed immediately.

```suggestion
To keep the `main` branch in a releasable state, experimental features must be gated behind a [Rust feature flag](https://doc.rust-lang.org/cargo/reference/features.html).
Breaking changes should also be gated behind a feature flag, unless the team decides they are urgent.
(For example, security fixes which also break backwards compatibility.)
```

2022-10-13 00:58 UTC, teor2345 commented on book/src/dev/release-process.md
> +## Decision making
This seems like a rough draft analysis, does it belong in a separate document?
Can we add a key that explains what each symbol means, and a description of what the table is used for?

(Let me know if you'd like me to help, I wrote up the table!)

2022-10-13 00:58 UTC, teor2345 commented on book/src/dev/release-process.md
> +Zebra version numbers indicate the level of changes that are introduced by the release and are composed of three parts: `major.minor.patch`.
```suggestion
Zebra version numbers show the impact of the changes in a release. They are composed of three parts: `major.minor.patch`.
```

2022-10-13 00:58 UTC, teor2345 commented on book/src/dev/release-process.md
> +| rc     | The most recent release candidate of Zebra, meant to become a stable version. |
```suggestion
| rc     | The most recent release candidate of Zebra, meant to become a stable version. May not always exist. |
```

2022-10-16 12:14 UTC, gustavovalverde commented on book/src/dev/release-process.md
> +## Decision making
Yes, I'd appreciate your intervention with this part.

2022-10-19 05:40 UTC, teor2345 commented on book/src/dev/release-process.md
> +## Decision making
I decided to remove it, I wasn't quite sure how to turn it into a useful document, without a lot of extra work.

2022-10-19 05:41 UTC, teor2345 commented
@gustavovalverde did you want help with the audit part, or did you want to do that in a separate PR?

2022-10-19 18:17 UTC, gustavovalverde commented
> @gustavovalverde did you want help with the audit part, or did you want to do that in a separate PR?

I created a ticket for the specific audit part https://github.com/ZcashFoundation/zebra/issues/5431

2022-10-19 19:06 UTC, teor2345 commented
> > @gustavovalverde did you want help with the audit part, or did you want to do that in a separate PR?
> 
> I created a ticket for the specific audit part #5431

Fair enough, I think that will also be covered by #5395, which mentions the audit tag and dependencies.

2022-10-19 19:08 UTC, teor2345 approved these changes
Thanks!

2022-10-19 19:31 UTC, merged