ci(sync): only run the `lightwalletd` full sync on the `main` branch
ZcashFoundation/zebra pull request #5393
Opened 2022-10-12 16:40 UTC by gustavovalverde

## Previous behavior
In PR #5164, we made lightwalletd sync all the way to the tip in its full sync test.

This increases that test's time from 1 hour to 4 hours, which makes the CI we run on each PR change increase from 3 hours to 6 hours.

## Expected behavior
Run the lightwalletd full sync just on `main` or if a state disk for the actual version is not found.

## Solution
Add the `github.event_name == 'push' && github.ref_name == 'main'` condition to the `lightwalletd-full-sync` test.

Fixes #5316

## Review

Anyone from the DevOps team

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

2022-10-12 18:10 UTC, arya2 submitted a review, later dismissed
LGTM!

2022-10-12 20:55 UTC, gustavovalverde commented
Protection rules updated to allow this and other PRs to be merged

2022-10-12 21:27 UTC, teor2345 requested changes
> Protection rules updated to allow this and other PRs to be merged

You disabled the requirement for the `lwd` full sync job, but we added a patch job for the `zebrad` full sync job.

<img width="822" alt="Screen Shot 2022-10-13 at 07 25 07" src="https://user-images.githubusercontent.com/8951843/195450954-6a6fc60f-565c-4445-8588-9bde28be3800.png">

https://github.com/ZcashFoundation/zebra/blob/8646a03e03b9dda190c46f05fd64631a99c9da9d/.github/workflows/continous-integration-docker.patch-always.yml#L18-L22

Can we choose one way to do it, and make it consistent?

2022-10-12 21:41 UTC, teor2345 requested changes
I'm not sure about the conditions here, I think we might want to match the full sync job almost exactly?

I'll also push a PR with some more suggestions.

2022-10-12 21:41 UTC, teor2345 commented on .github/workflows/continous-integration-docker.yml
> +    if: ${{ (!cancelled() && !failure() && (github.event_name == 'push' && github.ref_name == 'main') && github.event.inputs.regenerate-disks != 'true' && github.event.inputs.run-full-sync != 'true')
I'm wondering about the logic here:
- `!cancelled() && !failure()` - we must have success or skip for previous jobs, regardless of any other conditions, so I think these conditions need to be `&&` with all the rest of the conditions or triggers
- `github.event.inputs.regenerate-disks != 'true' && github.event.inputs.run-full-sync != 'true'` - these inputs will never be true on a push event, they are only set for manual workflow runs, so we can remove them
- I think we'll want to be able to manually trigger this job, like the zebrad checkpoint and full sync jobs (I'll open a PR for this)

So we might want to use the same conditions as the zebrad full sync, with an extra `!cancelled() && !failure()` at the start:
```suggestion
    if: ${{ !cancelled() && !failure() && ((github.event_name == 'push' && github.ref_name == 'main') || !fromJSON(needs.get-available-disks.outputs.lwd_tip_disk)) }}
```

Here are the zebrad full sync conditions, for comparison:
https://github.com/ZcashFoundation/zebra/blob/8646a03e03b9dda190c46f05fd64631a99c9da9d/.github/workflows/continous-integration-docker.yml#L321

2022-10-12 22:11 UTC, teor2345 commented
I opened PRs #5399 and #5400, feel free to merge them into this PR, or merge them into `main` separately.

PR #5400 will conflict with my job condition suggestion above, because it adds to that same line.

2022-10-16 12:11 UTC, gustavovalverde commented
This has been updated accordingly

2022-10-19 05:37 UTC, teor2345 commented
> > Protection rules updated to allow this and other PRs to be merged
> 
> This PR disables the requirement for the `lwd` full sync job, but we added a patch job for the `zebrad` full sync job.

I added an "always" patch job, and re-added the branch protection rule.

2022-10-19 05:37 UTC, teor2345 approved these changes
Thanks, I think we're good to go here.

2022-10-19 12:01 UTC, merged