fix(ci): Make "test all" log output shorter
ZcashFoundation/zebra pull request #5521
Opened 2022-11-01 00:28 UTC by teor2345

## Motivation

Sometimes GitHub truncates the log output of "test all", which makes it hard to find the actual failure.

This impacts some release candidate PRs, and it happens pretty often, so I just went ahead and fixed it.

Part of #5518, but we still need to fix the full sync logs.

## Solution

- Turn off `--nocapture` for "test all" in OS and Docker tests
- Split Docker "test all" job into a basic and ignored-by-default step

## Review

This is something @gustavovalverde and I discussed today.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

- Fix the full sync logs

2022-11-01 03:40 UTC, teor2345 commented
@mergifyio update

2022-11-01 06:08 UTC, teor2345 commented on .github/workflows/continous-integration-docker.yml
> +          docker run --name zebrad-tests -t ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests" --workspace --
```suggestion
          docker run --name zebrad-tests-ignored -t ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests" --workspace -- --ignored
```

2022-11-01 06:09 UTC, teor2345 commented on .github/workflows/continous-integration-docker.yml
> +          docker run --name zebrad-tests -t ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests getblocktemplat
```suggestion
          docker run --name zebrad-tests--ignored --tag ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests getblocktemplate-rpcs" --workspace -- --ignored
```

2022-11-01 06:12 UTC, teor2345 commented on .github/workflows/continous-integration-docker.yml
> +          docker run --name zebrad-tests -t ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests" --workspace
```suggestion
          docker run --name zebrad-tests --tag ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests" --workspace
```

2022-11-01 06:12 UTC, teor2345 commented on .github/workflows/continous-integration-docker.yml
> +          docker run --name zebrad-tests -t ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests getblocktemplat
```suggestion
          docker run --name zebrad-tests --tag ${{ env.GAR_BASE }}/${{ env.IMAGE_NAME }}:sha-${{ env.GITHUB_SHA_SHORT }} cargo test --locked --release --features "lightwalletd-grpc-tests getblocktemplate-rpcs" --workspace
```

2022-11-01 20:42 UTC, dconnolly commented
I lost the log snapshot but I restarted the CI jobs for 'disk full' messages on the OS jobs (linux and macos)

2022-11-01 21:37 UTC, dconnolly approved these changes
Does not recognize `--tag`:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/552961/199346507-ecfb8a64-dd57-45ea-aaa2-d7a5c6bffc86.png">

2022-11-01 21:37 UTC, dconnolly requested changes
Does not recognize `--tag`:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/552961/199346546-a3ca8e59-64cd-4aba-9c73-ca68736007ce.png">

2022-11-01 22:26 UTC, teor2345 commented
> Does not recognize `--tag`:
> 
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/552961/199346546-a3ca8e59-64cd-4aba-9c73-ca68736007ce.png">

Thanks, the options should be fixed now.

2022-11-02 04:00 UTC, teor2345 commented
Opened bug #5532 and updated bug #5494 for test failures.

2022-11-02 04:00 UTC, teor2345 commented
@mergifyio update

2022-11-03 22:03 UTC, teor2345 commented
It seems like @dconnolly is busy, @gustavovalverde would you mind reviewing this PR?

2022-11-03 22:05 UTC, dconnolly approved these changes, later dismissed
passing, looks good

2022-11-04 00:23 UTC, dconnolly commented
Re-running the fail: 

<img width="905" alt="image" src="https://user-images.githubusercontent.com/552961/199858998-d8253cd2-4263-41ad-b16a-6d4ad230c9e1.png">

2022-11-04 02:18 UTC, teor2345 commented
@mergifyio update

2022-11-04 02:25 UTC, dconnolly approved these changes, later dismissed

2022-11-04 02:28 UTC, teor2345 commented
I merged in the changes from PR #5549, then only applied --nocapture to the on-by-default tests.

2022-11-04 02:53 UTC, dconnolly approved these changes

2022-11-04 04:50 UTC, teor2345 commented
@mergifyio refresh

2022-11-04 06:57 UTC, merged