change(rpc): check contextual validity of getblocktemplate response
ZcashFoundation/zebra pull request #5630
Opened 2022-11-15 00:03 UTC by arya2

## Motivation

The getblocktemplate response must be contextually valid based on the best tip in the state.

This is a draft PR for now because there's currently a placeholder for the `block_commitments_hash` field of `GetBlockTemplate` and tests are panicking with:

> the history tree of the previous block must exist since the current block has a ChainHistoryBlockTxAuthCommitment

Closes #5376

## Solution

- Add a new state request for checking the contextual validity of a prepared block without committing it.
- Make a prepared block with default `nonce` and `solution` fields to use the new state request

## Review

This PR is part of regular scheduled work.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

2022-11-17 18:02 UTC, arya2 commented on zebra-state/src/service.rs
> +                .insert_chain(Arc::clone(best_chain))
qualifying the `Arc::clone` so it's obvious that nothing's being copied without looking at the type.

2022-11-18 18:07 UTC, arya2 commented
@Mergifyio update

2022-11-20 15:43 UTC, oxarbitrage commented
This one will conflict with https://github.com/ZcashFoundation/zebra/pull/5659 in the tests as i added some stuff from this PR there. I will prefer https://github.com/ZcashFoundation/zebra/pull/5659 to go first just because i have another PR to push that is based on it and it will be easier for me to do it that way.

2022-11-21 00:21 UTC, arya2 commented
> This one will conflict with #5659 in the tests as i added some stuff from this PR there. I will prefer #5659 to go first just because i have another PR to push that is based on it and it will be easier for me to do it that way.

Sounds good, I'd also prefer #5659 go first so this PR could use the populated `target` field for the `difficulty_threshold` of the prepared block.

2022-11-21 01:01 UTC, teor2345 requested changes
I think the ticket for this PR was a bit confusing. We need to change how the mempool checks transactions, so it always uses the best chain.

If we wait until the transactions are in the `getblocktemplate` response, it is too late, because all we can do is return an error to the caller. We don't know which transactions to remove to make the block valid.

Edit: It is also going to be tricky to verify the block, because the solution in the header requires Proof of Work. (Correct equihash solutions are expensive to create, so we can't do that in tests or in the RPC.)

We might want to turn this PR into a ticket, because the code looks like it could be useful for testing.

I'll add some specific notes to the ticket about where we want to change things.

2022-11-21 19:39 UTC, arya2 commented
> I think the ticket for this PR was a bit confusing. We need to change how the mempool checks transactions, so it always uses the best chain.
> 
> If we wait until the transactions are in the `getblocktemplate` response, it is too late, because all we can do is return an error to the caller. We don't know which transactions to remove to make the block valid.

Oops. 🤦 I thought I just hadn't come across the code that was checking the nullifiers, I understand now.

> It is also going to be tricky to verify the block, because the solution in the header requires Proof of Work. (Correct equihash solutions are expensive to create, so we can't do that in tests or in the RPC.)
>
> The code looks like it could be useful for testing.

I believe block solutions are only checked in the block verifier. I created issue #5681 for adding this as a test.

I'm closing this because it would needlessly hurt performance in production.

2022-11-21 19:39 UTC, closed without merging