ci: filter READY images before using them on test machines
ZcashFoundation/zebra pull request #5696
Opened 2022-11-22 21:36 UTC by gustavovalverde

## Motivation

We've had multiple PRs fail with:
> Run gcloud compute instances create-with-container "update-to-tip-5020-merge-5690565" \
> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
> - The resource 'projects/zealous-zebra/global/images/zebrad-cache-main-bc7294f-v25-mainnet-tip-u-0901230920' is not ready

Fixes #5044

### Designs

- When selecting images for tests, add a `status: READY` filter
- When selecting the 2 images to keep, add a `status: READY` filter
- When selecting images to delete, _*do not*_ add a `status: READY` filter, because we are already filtering out recent 

## Solution

Add `--filter="status=READY` to our existing filter.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

2022-11-22 22:45 UTC, teor2345 requested changes
Looks good!

> * When selecting the 2 images to keep, add a `status: READY` filter

I think this part got missed?

Here's the syntax for getting multiple values, and turning them into a formatted string:
https://github.com/ZcashFoundation/zebra/blob/cbc2e393caacaf82af3ac46603be344bd5cb2ea0/.github/workflows/delete-gcp-resources.yml#L92

Or it might be ok to merge this as-is. Is it possible for an image to still be un-READY after 2 days? Maybe if the process creating it crashed?

2022-11-22 22:53 UTC, gustavovalverde commented
@teor2345 images are commonly unready minutes after creation. I would merge as-is and any other scenario we can tackle it later. But leaving the last decision to you, I don't mind improving it tomorrow

2022-11-22 22:54 UTC, teor2345 approved these changes
Let's merge and open another ticket if we hit that edge case

2022-11-23 02:05 UTC, teor2345 commented
@mergifyio refresh

2022-11-23 03:53 UTC, merged