fix(ci): remove warnings caused by missing `actions/checkout` step
ZcashFoundation/zebra pull request #5874
Opened 2022-12-19 14:13 UTC by gustavovalverde

## Motivation

We get this warning when running the `continous-delivery.yml` workflow:

> Deploy single instance
> The "create_credentials_file" option is true, but the current GitHub workspace is empty. Did you forget to use "actions/checkout" before this step? If you do not intend to share authentication with future steps in this job, set "create_credentials_file" to false.

Fixes #5729

## Solution

Add missing `actions/checkout` steps  to allow the credentials file to be written correctly

## Review

Anyone can review this

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

2022-12-19 18:30 UTC, arya2 commented
Running the workflow here: https://github.com/ZcashFoundation/zebra/actions/runs/3734154152

2022-12-19 18:47 UTC, arya2 commented
> WARNING: Default device-name for disk name [auto-delete=yes] will be [auto-delete=yes] because it is being mounted to a container with [`--container-mount-disk`]
> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
>  - Invalid value for field 'resource.disks[1].deviceName': 'auto-delete=yes'. Must be a match of regex '(^$|\w[\w.-]{0,254})'

https://github.com/ZcashFoundation/zebra/actions/runs/3734154152/jobs/6335869442#step:6:74

2022-12-21 17:47 UTC, arya2 commented
> > WARNING: Default device-name for disk name [auto-delete=yes] will be [auto-delete=yes] because it is being mounted to a container with [`--container-mount-disk`]
> > ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
> > 
> > * Invalid value for field 'resource.disks[1].deviceName': 'auto-delete=yes'. Must be a match of regex '(^$|\w[\w.-]{0,254})'
> 
> https://github.com/ZcashFoundation/zebra/actions/runs/3734154152/jobs/6335869442#step:6:74

@gustavovalverde I don't see why this PR would cause this issue, but it's not happening on the main branch or anywhere else.

2022-12-21 18:57 UTC, arya2 commented on .github/workflows/continous-delivery.yml
> +          persist-credentials: false
Could we try setting "create_credentials_file" to false in google-github-actions/auth instead of adding this if it works without this step?

2023-01-04 03:22 UTC, teor2345 requested changes
> > > WARNING: Default device-name for disk name [auto-delete=yes] will be [auto-delete=yes] because it is being mounted to a container with [`--container-mount-disk`]
> > > ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
> > > 
> > > * Invalid value for field 'resource.disks[1].deviceName': 'auto-delete=yes'. Must be a match of regex '(^$|\w[\w.-]{0,254})'
> > 
> > 
> > https://github.com/ZcashFoundation/zebra/actions/runs/3734154152/jobs/6335869442#step:6:74
> 
> @gustavovalverde I don't see why this PR would cause this issue, but it's not happening on the main branch or anywhere else.

This seems to be an existing bug in the workflow, which is only triggered by a `workflow_dispatch`.

The `name=` field is missing for manual dispatch:
https://github.com/ZcashFoundation/zebra/blob/53e836efdcb6f25319403d8e43daaff92408b009/.github/workflows/continous-delivery.yml#L220

This is what it should be like:
https://github.com/ZcashFoundation/zebra/blob/53e836efdcb6f25319403d8e43daaff92408b009/.github/workflows/continous-delivery.yml#L139

This seems like a blocker for this PR, because we can't test the PR without fixing it.

2023-01-09 20:30 UTC, gustavovalverde commented
Working once again https://github.com/ZcashFoundation/zebra/actions/runs/3877453287/jobs/6612495110

2023-01-09 22:41 UTC, teor2345 commented
Is this warning a problem?
> WARNING: Default device-name for disk name [None] will be [None] because it is being mounted to a container with [`--container-mount-disk`]

https://github.com/ZcashFoundation/zebra/actions/runs/3877453287/jobs/6612495110#step:6:75

2023-01-09 22:41 UTC, teor2345 approved these changes
Looks good otherwise!

2023-01-10 01:40 UTC, gustavovalverde commented
> Is this warning a problem?
> 
> >

That's part of the issues with the GCP documentation that I reported to them

2023-01-10 10:11 UTC, merged