Hard-Coded Checkpoint Lists
ZcashFoundation/zebra pull request #674
Opened 2020-07-16 11:20 UTC by teor2345

This PR is based on #663 and #670.

I implemented the checkpoint calculations using some bash scripts, and committed them to zebra-utils. We can re-implement them in Rust when we have time.

I'm opening this PR for an initial review, and to try to answer some of the open questions from #564:
- [ ] Is 256 MB spacing too high? Do we need to impose a maximum number of blocks as well?
- [ ] Should we remove any checkpoints after Heartwood activation?

The block spacing range for 256 MB checkpoints is:
  - Mainnet: 400 - 50,000
  - Testnet: 10,000 - 250,000

Heartwood activated at:
  - Mainnet: 903000 (16 July 2020)
  - Testnet: 903800 (4 May 2020)

Our initial draft list of checkpoints was created before Heartwood on mainnet, but after Heartwood on testnet. The testnet checkpoints include a post-Heartwood block.

2020-07-16 11:22 UTC, teor2345 commented
The first new commit is c561827.

(The commit will change when #663 and #670 are updated or merged.)

2020-07-16 18:01 UTC, hdevalence commented
I think that the block spacing might be too long.  I think that setting the sync lookahead limit to twice the maximum checkpoint distance is a good way to be safe while downloading blocks (choosing 2*d rather than d guards against aliasing the checkpoint interval), and downloading 100k blocks at a time seems less than ideal.  We could try to do some plumbing to feed data from the checkpoint verifier to the syncer, but that seems much more complex compared to hardcoding additional hashes.

My guess is that a 2000 block distance limit would be reasonable to start.

It would be convenient if the bash script did the hex-reversal, even if it's somewhat slower.

2020-07-16 21:52 UTC, teor2345 commented
> It would be convenient if the bash script did the hex-reversal, even if it's somewhat slower.

The calculate-checkpoints.sh bash script does the hex reversal.

Doing the reversal on every block hash would take at least 15 hours, but it should be a lot faster after #679 is merged. For the full calculation, see:
https://github.com/ZcashFoundation/zebra/pull/670#issuecomment-659668194

2020-07-16 22:38 UTC, teor2345 commented
I rebased onto main after the PRs merged.

> My guess is that a 2000 block distance limit would be reasonable to start.

See 1df13a8f9b8a10bf79d14d5b931f783f3b0da329 for the script update, and 9774315b08a62fd00dd60b59c5a35dfb4cbc6e1c for the new lists.

I squashed the list updates together, because they didn't have any checkpoints in common. So the diffs weren't useful.

2020-07-16 22:41 UTC, teor2345 commented
Oh, and I still have this open question:
- [ ] Should we remove any checkpoints after Heartwood activation?

2020-07-16 22:48 UTC, hdevalence commented
Great! I'd be happy to merge this whenever.  I think it would be nice if we could generate Rust source code directly but maybe this is better done later -- personally I think it would be fine to create the initial checkpoint list by copypasting the text files into a `.rs` and filling in syntax.

2020-07-16 23:05 UTC, teor2345 commented
I'll edit the scripts to reference LOOKAHEAD_LIMIT.

And then I think I want to parse them, so I can check they actually work.

Then I think we can merge.

2020-07-16 23:07 UTC, teor2345 commented
> (choosing 2*d rather than d guards against aliasing the checkpoint interval)

Can you explain this a bit more?
I'm not sure exactly what you mean.

2020-07-16 23:31 UTC, hdevalence commented
@teor2345 I didn't think it through precisely, but I was thinking of something like the Nyquist limit, with the checkpoint frequency aliasing the lookahead frequency (? or something?) but I'm not sure this makes sense.  However if we do `2*d` rather than `d` then the syncer will attempt to download the next interval while the current interval is downloading, so that we don't pause downloads.

2020-07-17 00:05 UTC, teor2345 commented
I think it's a good idea. It should help avoid stalls, and a whole class of similar issues, such as off-by-one errors and thundering herds.

2020-07-20 04:39 UTC, teor2345 commented
I parsed the lists, and added some tests.

I also tweaked the CheckpointList and CheckpointVerifier initialisation functions, so callers can just ask for a verifier with the hard-coded list.

2020-07-20 23:02 UTC, yaahc requested changes
Looks good, I didn't carefully review the bash because I assume we're going to rewrite it in rust soon but the rust looks good. There is one error message I'd like to update but other than that this looks good to me. I like the bit where we use the first checkpoint in the list to determine the network it should be from :D

2020-07-20 23:02 UTC, yaahc commented on zebra-consensus/src/checkpoint/list.rs
> +                Err(format!("Checkpoint list parse failure. Expected 2 space-separated fields on checkpoint line: '{}'", checkpoint))?;
```suggestion
                Err(format!("Invalid checkpoint format: expected 2 space-separated fields but found {}: '{}'", fields.len(), checkpoint))?;
```

2020-07-21 01:25 UTC, teor2345 commented
> I didn't carefully review the bash because I assume we're going to rewrite it in rust soon

Does anyone carefully review bash? 😄

I think we're pretty safe here, because the CheckpointVerifier is very flexible. The exact heights aren't important, just as long as the heights and hashes match, and there is a genesis checkpoint.

> I like the bit where we use the first checkpoint in the list to determine the network it should be from :D

"Make invalid states un-representable", but for function arguments.

Daira previously suggested that we should use the actual consensus parameters as much as possible. (Rather than passing a network enum around everywhere.) So I removed or replaced most network references, and converted from the network as soon as I could. Right now, nothing in `zebra-consensus` keeps a persistent copy of the network.

2020-07-21 13:11 UTC, merged

2020-07-21 13:12 UTC, teor2345 commented
(I merged this because the last change was trivial, and I wanted to make new PRs based on this PR.)