build: update locked dependencies
ZcashFoundation/zebra pull request #6878
Opened 2023-06-08 19:51 UTC by dconnolly

## Missed Dependency Updates

Sometimes `dependabot` misses some dependency updates, or we accidentally turned them off.

Here's how we make sure we got everything:
- [ ] Run `cargo update` on the latest `main` branch, and keep the output
- [ ] If needed, update [deny.toml](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-integration.md#fixing-duplicate-dependencies-in-check-denytoml-bans)
- [ ] Open a separate PR with the changes, and add the output of `cargo update` to that PR as a comment

2023-06-08 21:12 UTC, teor2345 requested changes
This needs to be regenerated after PR #6881 and any other dependency updates merge.

2023-06-08 21:14 UTC, dconnolly commented
> This needs to be regenerated after PR #6881 and any other dependency updates merge.

Correct

2023-06-12 00:47 UTC, teor2345 commented
Coverage failed due to #5823, I re-opened that ticket.

2023-06-12 00:48 UTC, teor2345 approved these changes
Great, this is the outcome I had hoped we would get after doing the missed updates a few times.

2023-06-12 04:19 UTC, teor2345 commented
@mergifyio refresh

2023-06-12 06:31 UTC, merged