fix(state): Remove workarounds for storing trees
ZcashFoundation/zebra pull request #7218
Opened 2023-07-15 21:56 UTC by upbqdn

## Motivation

We were using some workarounds for committing trees into the non-finalized state. Namely, we turned off asserting that we don't commit more than a single tree at a particular height in tests. It would be great to have this resolved before we do the tree deduplication.

## Solution

This PR removes the workarounds and fixes tests so they don't push more than a single block at a particular height.

## Review

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

2023-07-16 22:28 UTC, teor2345 commented on zebra-state/src/service/non_finalized_state/tests/vectors.rs
> +        .expect("Block 434873 should have its height in its coibase tx.");
```suggestion
        .expect("Block 434873 should have its height in its coinbase tx.");
```

2023-07-16 22:28 UTC, teor2345 approved these changes
Thanks for these fixes!

I just committed one typo fix.

2023-07-17 03:04 UTC, teor2345 requested changes
Hmm, looks like 3 proptests failed for 3 different reasons?

> ---- service::non_finalized_state::tests::prop::forked_equals_pushed_genesis stdout ----
> The application panicked (crashed).
> Message:  hash is present
> Location: zebra-state/src/service/non_finalized_state/tests/prop.rs:206

https://github.com/ZcashFoundation/zebra/actions/runs/5570108032/jobs/10174308429?pr=7218#step:4:4059

We didn't get a proptest seed out of these tests, so we might need to run a few tests to make sure we've fixed this completely.

2023-07-17 18:51 UTC, upbqdn commented
It looks like it's two proptests, but the log contains three entries because one of the tests panicked in an `expect`, which got reported, and that made the test fail, which got reported again.

I ran both protests five times locally, and none of them failed once. :/ I think I found the issue though. I pushed a fix.

2023-07-17 19:24 UTC, teor2345 commented
> I ran both protests five times locally, and none of them failed once. :/ I think I found the issue for both failures, though. I pushed a fix.

I usually run all the related proptests in a loop for a few thousand iterations, overnight or while I'm doing other work.

2023-07-17 19:25 UTC, teor2345 approved these changes
Let's try it and see

2023-07-17 22:51 UTC, teor2345 commented
This is marked with `extra-reviews` because it contains the word "remove", but it doesn't actually remove any user-visible features.

2023-07-18 04:54 UTC, merged