Network Sustainability Mechanism - ZIP 234 & 235 implementation
ZcashFoundation/zebra pull request #8948
Opened 2024-10-18 13:14 UTC by mariopil

## Motivation

This PR implements [ZIP-234](https://github.com/zcash/zips/pull/914) and [ZIP-235](https://github.com/zcash/zips/pull/915).

### Specifications & References

 [ZIP-234](https://github.com/zcash/zips/pull/914), [ZIP-235](https://github.com/zcash/zips/pull/915)

## Solution

This PR is implemented above #8930 which implements the ZIP-233. It smoothes the issuance curve (ZIP-234) and introduces the split between miner fees (40%) and the amount that is burned (60%, ZIP-235). Some of the code used in the block semantical verification for block subsidy calculation has been moved into the write task, as now the block subsidy calculation relies on the current amount of `money_reserve` which is obtained from pool value balance at `height-1`- therefore the previous block must be already present at least in the non-finalized best chain. 

### Tests

For testing purposes, a local testnet network was set up. It contained two nodes—a zebra and a zcashd one (with the ZIP-234 & 235 implemented, too, PR https://github.com/zcash/zcash/pull/6970). A transaction in a new format containing the `burn_amount` field was created and added to the block by zcashd. The zebra node synced with zcashd without any errors and accepted the block.

A couple of unit tests were also added.

### Follow-up Work

### PR Author's Checklist

- [x] The PR name will make sense to users.
- [x] The PR provides a CHANGELOG summary.
- [x] The solution is tested.
- [x] The documentation is up to date.
- [ ] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

2025-01-16 09:36 UTC, jackgavigan commented
@mariopil Does this PR need to be refreshed when the ZIP is finalized?

2025-01-16 09:40 UTC, mariopil commented
> @mariopil Does this PR need to be refreshed when the NSM ZIPs are finalized?

Yes. Currently, the implementation of both 234 and 235 zips is under one feature flag, but they will be covered by separate feature flags.

2025-01-16 17:20 UTC, conradoplg reviewed
This is a first pass review, I mostly looked into the feature gating and overall structure

2025-01-16 17:20 UTC, conradoplg commented on zebra-chain/src/parameters/network_upgrade.rs
> +    // TODO: Update NU6 activation height once it's been specified.
```suggestion
```

2025-01-16 17:20 UTC, conradoplg commented on zebra-chain/src/transaction.rs
> +    }
"burn" reference

2025-01-16 17:20 UTC, conradoplg commented on zebra-chain/src/transaction/builder.rs
> +            burn_amount: burn_amount.unwrap_or_else(|| ((miner_fee * 6).unwrap() / 10).unwrap()),
"burn" mentioned

2025-01-16 17:20 UTC, conradoplg commented on zebra-chain/src/transaction/serialize.rs
> +                let burn_amount = (&mut limited_reader).zcash_deserialize_into()?;
"burn" mentioned

2025-01-16 17:20 UTC, conradoplg commented on zebra-chain/src/transaction/unmined.rs
> +            Witnessed(id) => f.debug_tuple("WtxId").field(id).finish(),
```suggestion
            Witnessed(_id) => f.debug_tuple("WtxId").field(&"private").finish(),
```

Please don't change unrelated code

2025-01-16 17:20 UTC, conradoplg commented on zebra-chain/src/value_balance.rs
> +use crate::amount::MAX_MONEY;
Need to gate the import to avoid "unused import" warnings

2025-01-16 17:20 UTC, conradoplg commented on zebra-consensus/src/block.rs
> +                .map_err(|err| VerifyBlockError::Transaction(TransactionError::Coinbase(err)))?;
Was the `subsidy_is_valid` check moved elsewhere?

2025-01-16 17:20 UTC, conradoplg commented on zebra-consensus/src/block.rs
> -
Where was this check moved to?

2025-01-16 17:20 UTC, conradoplg commented on zebra-consensus/src/block.rs
> -
Where was this check moved to?

2025-01-16 17:20 UTC, conradoplg commented on zebra-consensus/src/checkpoint.rs
> -
Why was this removed?

2025-01-16 17:20 UTC, conradoplg commented on zebra-consensus/src/transaction.rs
> +            let burn_amount = match *tx {
"burn" mentioned

2025-01-16 17:20 UTC, conradoplg commented on zebra-consensus/src/transaction.rs
> +                Transaction::ZFuture{ .. } => tx.burn_amount(),
"burn" mentioned - sorry, at this point it's better for you to simply search for all instances of it

2025-01-16 17:20 UTC, conradoplg commented on zebra-consensus/src/transaction/tests/prop.rs
> +        transaction_version in 4_u8..=6,
Needs to be feature-gated

2025-01-16 17:20 UTC, conradoplg commented on zebra-state/src/service/write.rs
> +    prepared: &mut SemanticallyVerifiedBlock,
Document what is modified in the block

2025-01-17 08:50 UTC, mariopil commented on zebra-consensus/src/block.rs
> +                .map_err(|err| VerifyBlockError::Transaction(TransactionError::Coinbase(err)))?;
This was moved to `zebra-state/src/service/check.rs`. In the ZIP-234 implementation block subsidy is calculated using the latest pool values. These can be obtained from the best chain of non-finalized state, or from finalized tip height (see the changes in `initial_contextual_validity()`), so after the blocks are already processed.

2025-01-17 08:51 UTC, mariopil commented on zebra-consensus/src/block.rs
> -
Similar case as above, `zebra-state/src/service/check.rs`

2025-01-17 08:51 UTC, mariopil commented on zebra-consensus/src/block.rs
> -
Similar case as above, `zebra-state/src/service/check.rs`

2025-01-17 08:56 UTC, mariopil commented on zebra-consensus/src/checkpoint.rs
> -
Moved to `zebra-state/src/service/write.rs write`,  `write_blocks_from_channels()`.

2025-01-17 09:30 UTC, giddie commented on zebra-consensus/src/transaction.rs
> +                Transaction::ZFuture{ .. } => tx.burn_amount(),
Yeah, the ZIPs were only just changed. We've not adjusted this code yet, especially since only 233 is targeted for inclusion in NU7.

2025-11-10 22:18 UTC, conradoplg commented
Needs rebasing/conflict solving

2025-11-18 12:48 UTC, mariopil commented on zebra-consensus/src/block/check.rs
> -pub fn coinbase_is_first(block: &Block) -> Result<Arc<transaction::Transaction>, BlockError> {
Moved to `zebra-state/src/service/check.rs`

2025-11-18 12:49 UTC, mariopil commented on zebra-consensus/src/block/check.rs
> -pub fn miner_fees_are_valid(
Moved to `zebra-state/src/service/check.rs`

2025-11-18 12:49 UTC, mariopil commented on zebra-consensus/src/block/check.rs
> -pub fn subsidy_is_valid(
Moved to `zebra-state/src/service/check.rs`

2025-11-18 13:12 UTC, mariopil commented
The PR has been rebased and updated

2025-12-11 16:36 UTC, judah-caruso commented
Requesting review from @conradoplg @arya2 @giddie after rebase + linting fixes. Thanks!

2025-12-15 21:14 UTC, daira commented on zebra-state/src/service/check.rs
> +            .map_err(|e| SubsidyError::Other(format!("invalid coinbase transaction: {e}")))?;
Consider adding a more specific error case, e.g. `CoinbaseNotFirst`.

2025-12-15 21:19 UTC, daira commented on zebra-state/src/service/check.rs
> +            .map_err(|err| SubsidyError::Other(err.to_string()))?;
Consider adding a more specific error case, e.g. `InvalidFundingStreams`.

2025-12-15 21:20 UTC, daira commented on zebra-state/src/service/check.rs
> +            .map_err(|e| SubsidyError::Other(format!("invalid deferred pool amount: {e}")))?;
Consider adding a more specific error case, e.g. `InvalidDeferredPoolAmount`.

2025-12-15 21:22 UTC, daira commented on zebra-state/src/service/check.rs
> +                    SubsidyError::Other(format!(
```suggestion
                    SubsidyError::InvalidFundingStreams(format!(
```

2025-12-15 21:27 UTC, daira commented on zebra-state/src/service/check.rs
> +        .map_err(|e| SubsidyError::Other(format!("invalid transparent value balance: {e}")))?;
```suggestion
        .map(|sum| sum.constrain())
        .map_err(|_| SubsidyError::SumOverflow)?;
```
or if that doesn't work,
```suggestion
        .map_err(|_| SubsidyError::SumOverflow)?
        .constrain()
        .map_err(|_| SubsidyError::SumOverflow)?;
```

2025-12-18 19:15 UTC, judah-caruso commented on zebra-state/src/service/check.rs
> +            .map_err(|e| SubsidyError::Other(format!("invalid coinbase transaction: {e}")))?;
Fixed! I replaced all cases of `SubsidyError::Other` with more specific errors. Thanks for the suggestion!

2025-12-19 21:21 UTC, conradoplg commented
@judah-caruso would you mind syncing this with `main`? For some reason GitHub is showing me a lot of unrelated stuff in the diff

2025-12-19 21:23 UTC, judah-caruso commented
> @judah-caruso would you mind syncing this with `main`? For some reason GitHub is showing me a lot of unrelated stuff in the diff

Sure, just did it! I think it's because the branch lives on our forked repo which was behind a few commits.

2026-01-14 23:18 UTC, conradoplg requested changes
Hi, thanks for your patience on this PR. I finally completed a more thorough review and I'm a bit confused by the overall approach though.

To implement issuance smoothing, it computes the money reserve by subtracting the other pools from total issuance. However, that adds a dependency on being able to read the pool amounts.

This is done by setting the `deferred_pool_balance_change` field of the `SemanticallyVerifiedBlock` later on. This decision however ripples in many places, since it requires having a `mut` `SemanticallyVerifiedBlock`. I'm concerned about things change being fragile and the field being forgot to be set in some code paths or after later refactorings.

I would rather simply move the subsidy check to be a contextual check, i.e. when a `SemanticallyVerifiedBlock` is turned into a `ContextuallyVerifiedBlock` in `NonFinalizedState::validate_and_commit()`. This would better align with the overall Zebra design, and would prevent requiring a two-state `SemanticallyVerifiedBlock` (with or without `deferred_pool_balance_change` set).  I haven't worked out if that change would pose other challenges, though.

~~There is another important thing to point out, though. As far as I understand this PR does not implement the logic of considering NSM deposits into the issuance calculation. Which in principle would be fine, but that particular change might require a lot of changes (I think a DB update might be required? I remember this being discussed and Shielded Labs arguing that it is not, but I did not really understand the explanation at the time), which makes me wonder why bother reviewing and merging something that might be completely changed soon.~~ Nevermind, I finally got it, see next comment

~~And if the idea was to simply do things in parts, then the whole change above is not required, since if we don't consider the NSM deposits into the subsidy calculation, then AFAIK it is possible to compute it without context checks, from only the block height, making the big code change in this PR simply not required.~~

Please consider the feedback above (also keep in mind that I could be wrong about some of the stuff, it is a complicated PR) and let us know how you would like to proceed.

2026-01-14 23:18 UTC, conradoplg commented on zebra-chain/src/block.rs
> +pub mod error;
Why pub?

2026-01-14 23:18 UTC, conradoplg commented on zebra-state/src/service/write.rs
> +            ordered_block.0.deferred_pool_balance_change = deferred_pool_balance_change;
I don't understand why this is done. Where the `deferred_pool_balance_change` is required when committing checkpointed blocks?

2026-01-15 12:51 UTC, conradoplg commented
OK, I think I finally got it: MAX_MONEY minus the rest of the pools is exactly the sum of the old unissued amount and NSM deposits.

Then my feedback boils down to trying to make it fully a contextual check next to the other contextual checks, and not having to deal with `mut SemanticallyVerifiedBlocks` if possible

2026-01-16 16:18 UTC, judah-caruso commented on zebra-chain/src/block.rs
> +pub mod error;
Looks like this was left over from the original work. Didn't need to be public, so I've removed it!

2026-01-16 16:19 UTC, judah-caruso commented
> I would rather simply move the subsidy check to be a contextual check, i.e. when a `SemanticallyVerifiedBlock` is turned into a `ContextuallyVerifiedBlock` in `NonFinalizedState::validate_and_commit()`. This would better align with the overall Zebra design, and would prevent requiring a two-state `SemanticallyVerifiedBlock` (with or without `deferred_pool_balance_change` set). I haven't worked out if that change would pose other challenges, though.

This sounds like a reasonable change, and I've been looking into refactoring the code to be more inline with this!

2026-01-19 20:16 UTC, judah-caruso commented on zebra-state/src/service/write.rs
> +            ordered_block.0.deferred_pool_balance_change = deferred_pool_balance_change;
After making the change you outlined above, this wasn't needed anymore - so it has been removed!

2026-01-19 20:18 UTC, judah-caruso commented
> Then my feedback boils down to trying to make it fully a contextual check next to the other contextual checks, and not having to deal with mut SemanticallyVerifiedBlocks if possible

@conradoplg Just made the change! Didn't require much refactoring, but definitely let me know if anything was missed or looks out of place. Thanks!

2026-01-29 21:35 UTC, conradoplg requested changes
The move to a contextual checks is looking good, but it introduces some difficulty with tracking the `deferred_pool_balance_change` field (which now requires context to be computed) and passing it around is a bit confusing. In two places of the code it passes `None` which does not seem correct.

I am really not sure what is the best approach here, sorry. I have the feeling that some refactoring could greatly simplify this but I am not sure what.

I was planning on suggesting removing the field from `CheckpointVerifiedBlock` (which _is_ the tricky part) and using a logic similar to how `treestate` is handled (e.g. in `FinalizedBlock::from_checkpoint_verified()` it is passed as an argument), but I am not sure if that would be a better approach, but it may be worth looking into.

2026-01-29 21:35 UTC, conradoplg commented on zebra-state/proptest-regressions/service/check/tests/nullifier.txt
This should be removed unless they are test cases that have shown bugs, which I think is not the case

2026-01-29 21:35 UTC, conradoplg commented on zebra-state/src/service/check.rs
> +    semantically_verified: &mut SemanticallyVerifiedBlock,
Should be no longer needed

```suggestion
    semantically_verified: &SemanticallyVerifiedBlock,
```

2026-01-29 21:35 UTC, conradoplg commented on zebra-state/src/service/check/tests/anchors.rs
The `mut`s in this file should be no longer needed

2026-01-29 21:35 UTC, conradoplg commented on zebra-state/src/service/write.rs
> +    prepared: &mut SemanticallyVerifiedBlock,
Should be no longer needed

```suggestion
    prepared: &SemanticallyVerifiedBlock,
```

2026-01-29 21:35 UTC, conradoplg commented on zebra-state/src/service/write.rs
> +    prepared: &mut SemanticallyVerifiedBlock,
As well as `mut`s below

2026-01-29 21:35 UTC, conradoplg commented on zebra-state/src/service/non_finalized_state/backup.rs
Should be able to remove `mut`s

2026-01-29 21:35 UTC, conradoplg commented on zebra-state/src/request.rs
> +            deferred_pool_balance_change: None,
This does not seem right to me, it should take a `deferred_pool_balance_change` like `new()`

2026-01-29 21:35 UTC, conradoplg commented on zebra-consensus/src/checkpoint.rs
> +        let block = CheckpointVerifiedBlock::new(block, Some(hash), None);
I don't think this is correct, it needs the correct `deferred_pool_balance_change` otherwise it will eventually corrupt the value pools index in `DiskWriteBatch::prepare_chain_value_pools_batch()`

2026-03-02 16:58 UTC, judah-caruso commented
After further discussion, it was agreed that ZIP-234 and ZIP-235 should be split into two separate PRs.

This is due to implementation details around ZIP-234 not being finalized and needing more research/work.

Discussion should be continued here:
- ZIP-235: https://github.com/ZcashFoundation/zebra/pull/10357

2026-03-09 10:26 UTC, mpguerra commented
@judah-caruso would you like us to close this PR or will you use it for the ZIP 234 implementation only?

2026-04-01 21:29 UTC, conradoplg commented
I'll close this for now, let us know if you want to reuse the PR and we can reopen it.

2026-04-01 21:29 UTC, closed without merging

2026-04-02 15:03 UTC, judah-caruso commented
> @judah-caruso would you like us to close this PR or will you use it for the ZIP 234 implementation only?

Hi, sorry! The notification for this never appeared in my GitHub inbox