Remove `scan-start-where-left-test` from CI
ZcashFoundation/zebra pull request #9026
Opened 2024-11-15 17:29 UTC by oxarbitrage

## Motivation

The `scan_start_where_left` test is failing our CI apparently for [this reason](https://github.com/ZcashFoundation/zebra/pull/8987#issuecomment-2455438148).

## Solution

Instead of fixing it we want to disable the test from the workflow keeping the rust test available for local run.

### Tests

CI should not fail in this workflow as it will not be there anymore.

### PR Author's Checklist

- [ ] The PR name will make sense to users.
- [ ] The PR provides a CHANGELOG summary.
- [ ] The solution is tested.
- [ ] The documentation is up to date.
- [ ] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

2024-11-15 18:42 UTC, arya2 submitted a review, later dismissed

2024-11-15 23:13 UTC, arya2 submitted a review, later dismissed

2024-11-18 08:57 UTC, mpguerra commented
@mergify refresh

2024-11-18 14:32 UTC, arya2 commented on .github/workflows/sub-ci-integration-tests-gcp.yml
> +      force_save_to_disk: false
```suggestion
      needs_zebra_state: true
      needs_lwd_state: true
      saves_to_disk: true
      force_save_to_disk: true
```

2024-11-18 14:32 UTC, arya2 commented on .github/workflows/sub-ci-integration-tests-gcp.yml
>        test_variables: "-e NETWORK=${{ inputs.network || vars.ZCASH_NETWORK }} -e TEST_LWD_UPDATE_SYNC=1 -e ZEBRA_TEST_LIGHTWALLETD=1 -e ZEBRA_FORCE_USE_COLOR=1 -e ZEBRA_CACHED_STATE_DIR=/var/cache/ze
Removing `ZEBRA_TEST_LIGHTWALLETD=1` here should work.

2024-11-18 14:36 UTC, gustavovalverde requested changes

2024-11-18 14:36 UTC, gustavovalverde commented on .github/workflows/ci-tests.patch-external.yml
> +    if: ${{ startsWith(github.event_name, 'pull') && github.event.pull_request.head.repo.fork }}
As agree, let's remove this changes and let's leave it for a different PR

2024-11-18 14:36 UTC, gustavovalverde commented on .github/workflows/sub-ci-integration-tests-gcp.yml
> -    needs: [lightwalletd-full-sync, get-available-disks]
As agreed, let's remove this changes from this file and let's leave it for a different PR

2024-11-18 15:46 UTC, gustavovalverde approved these changes

2024-11-19 09:25 UTC, merged