Improve zebra-consensus logging and metrics
ZcashFoundation/zebra pull request #989
Opened 2020-09-02 01:33 UTC by teor2345

These logging and metrics changes help us diagnose sync and verify issues.

2020-09-02 07:03 UTC, teor2345 commented on zebra-consensus/src/chain.rs
> +
Actually, I'll want to delete this in #969, so I'd best do it now.
```suggestion
```

2020-09-02 07:04 UTC, teor2345 commented on zebra-consensus/src/chain.rs
> +
Hmm actually no I want to keep this, so we have a single metric which covers checkpoints and blocks.

2020-09-03 00:30 UTC, yaahc requested changes
looks good, I have two style comments and 1 actually important comment I think, if not for the 3rd comment I'd be approving this.

2020-09-03 00:30 UTC, yaahc commented on zebra-consensus/src/block.rs
> +                    Err("Invalid block: height is 0, but previous block hash is not null.")?;
This is a style that rustc / clippy use for errors but I think its a good one to adopt here as well, no capitalization or punctuation in the error messages:

```suggestion
                    Err("invalid block: height is 0, but previous block hash is not null")?;
```

Hmm, I wonder if clippy could lint for this...

2020-09-03 00:30 UTC, yaahc commented on zebra-consensus/src/block.rs
>                      Err("Invalid block height: must be 1 more than the previous block height.")?;
```suggestion
                    Err("invalid block height: must be 1 more than the previous block height")?;
```

2020-09-03 00:30 UTC, yaahc commented on zebra-consensus/src/chain.rs
> +        let span = tracing::debug_span!("block_verify", ?height, ?hash,);
I think this needs to be entered unless I'm missing where it's used later.
```suggestion
        let span = tracing::debug_span!("block_verify", ?height, ?hash,);
        let _guard = span.enter();
```

2020-09-03 01:39 UTC, teor2345 commented on zebra-consensus/src/chain.rs
> +        let span = tracing::debug_span!("block_verify", ?height, ?hash,);
I think you're right, we must have missed that in a much earlier review.

2020-09-03 01:58 UTC, teor2345 commented on zebra-consensus/src/chain.rs
> +        let span = tracing::debug_span!("block_verify", ?height, ?hash,);
Actually, no, the span is used to instrument the future:
https://github.com/ZcashFoundation/zebra/pull/989/files#diff-9ce8cedb3963941e6cffe1a307d9dafcL183

2020-09-03 19:20 UTC, yaahc commented on zebra-consensus/src/chain.rs
> +        let span = tracing::debug_span!("block_verify", ?height, ?hash,);
aah yea there it is, just outside of the diff, lol

2020-09-03 19:21 UTC, yaahc approved these changes

2020-09-03 22:06 UTC, merged